@ER//qCOODsDCN0R1NNM8se8R4R3UmMbCRseCHOVHNF0HMHRpLssN$mR5e3p2
R//qCOODsDCNFRBbH$soRE05RO2.6jj-j.jnq3RDsDRH0oE#CRs#PCsC
83
bRRNlsNCs0CR#N#C_s0MCNlR"=Rq 11)]a_q1h7] qi"
;
RHR`MkOD8"CR#_08F_PD0	N#3
E"
V`H8RCVm_epq 11)ma_hR

RsbNN0lCC)sR qT_B1i_aaq)RRRR='R.L;jj
bRRNlsNCs0CRT) _iqB_QWqaRRRRRR=.j'L4R;
RsbNN0lCC)sR qT_B i_)R)RRRRR='R.L;4j
bRRNlsNCs0CRT) _iqB_q7 1)1 aRR=.4'L4
;
RCRso4Rr:Rj9s0_#N;0C
sRRCroR49:jRss__N#00
C;RCRso_Rss;CJ
sRRCsoR_	NO;R
RHCM0oRCsHR;
R0HMCsoCR
[;
V`H8RCVm_epX B]Bmi_wRw
R/R/7MFRFH0EM`o
CCD#
`RRHCV8VeRmpv_QuBpQQXa_BB] iw_mwR
RR/R/7MFRFH0EMRo
RD`C#RC
RsIHCNRPD_H8s;CJ
IRRHRsCPHND8O_N	
;
R#RN#MHoRDPNHs8_C=JRRR~5sRCJ^CRsJ;R2
NRR#o#HMNRPD_H8NRO	=5R~R	NORN^RO2	R;`
RCHM8V/R/Rpme_uQvpQQBaB_X]i B_wmw
M`C8RHV/m/ReXp_BB] iw_mwR

`8HVCmVReQp_h_Qav
1tRRRRH0MHH
NDRRRRRPRFDM_HHl0_#0o_;/R/RDBNDER0C#RzC7sRCMVHCQ8RMRH0v#C#NRoC)0FkH
MCRM`C8RHV/e/mph_QQva_1
t
RMRHHN0HDCRLo
HMRRRRs0_#N=0C)_ Tq_Bi1)aqaR;
RsRR_#s_0CN0=T) _iqB_q1a)
a;RRRRsC_sJ;=j
RRRRNs_Oj	=;R
RRRRH=;Rj
RRRR=[RR
j;RMRC8R

RINDNR$#@b@5F8#CoOCRDR	2LHCoMR
RRRRRH5VR`pme_1)  1a_Qqthp=R!RL4'jL2RCMoHRR//NHO0PDCRFsIRC0#C
RRRRRRRR#ONCsR5_N#00
C2RRRRRRRRR R)TB_qia_1q:)aRR
RRRRRRRRRRCRLo
HMRRRRRRRRRRRRRVRHRl55NNG_OD	_C0MoE=R!RRj2&N&RO=	R='R4L&4R&_RsNRO	=4=R'2L4RR
RRRRRRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRRRRR[<[=R+
4;RRRRRRRRRRRRRRRRRVRHRR5[>l=RNNG_OD	_C0MoE
2RRRRRRRRRRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRRRRRRRRRs0_#NR0C<)=R qT_B i_)
);RRRRRRRRRRRRRRRRRRRRRPRFDs_Cs_Fs075"k0sNHRFMFOVRFHM0MkkF##RN#0CsC#8R0CN0RRFVNMO	FCID8RoCPDHFN#0CRC#bOHHVCl8RNlGHkNlROl	_NDG_C0MoE$ROO#DC"
2;RRRRRRRRRRRRRRRRRRRRC
M8RRRRRRRRRRRRRRRRC
M8RRRRRRRRRRRRRDRC#HCRV5R5l_NGN_O	DoCM0!ER=2RjRR&&NRO	=4=R'RLj2R
RRRRRRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRRRRR[<j=R;R
RRRRRRRRRRRRRRMRC8R
RRRRRRRRRRRRRCCD#RRHV5N5lGO_N	C_DMEo0RR!=j&2R&ORN	=R=RL4'4&R&RNs_O=	R='R4LRj2
RRRRRRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRRRRRR<[R=;R4
RRRRRRRRRRRRRRRR8CM
R
RRRRRRRRRRRRRH5VRsRCJ=4=R'2L4RoLCHRM
RRRRRRRRRRRRRHRRVsR5_	NORR==44'LRR&&NRO	=4=R'RL4&s&R_JsCRR==4j'L2CRLo
HMRRRRRRRRRRRRRRRRR_Rs#00NC=R<RT) _iqB_) );R
RRRRRRRRRRRRRRRRRF_PDCFsss5_0"IhCRJsCk0C#RsNsH#PCRVLCFRsCbPsCH#FkRJsCk0C#RRH#NMO	FCID88oC"
2;RRRRRRRRRRRRRRRRC
M8RRRRRRRRRRRRRRRRCCD#RRHV5N8C#s#C0F_OkRM0!j=RRR&&sC_sJ=R=RL4'4&R&RJsCRR==44'LRR&&
RRRRRRRRRRRRRRRRRRRRNs_O=	R='R4LR42LHCoMR
RRRRRRRRRRRRRRRRRH5VR8#CN#0Cs_kOFM=0R='R4LR42LHCoMR
RRRRRRRRRRRRRRRRRR_Rs#00NC=R<RT) _iqB_) );R
RRRRRRRRRRRRRRRRRRPRFDs_Cs_Fs075"k0sNHRFMFOVRFHM0MkkF##RN#0CsC#8R0CN0RRFVskCJCR#0PDHFN#0CRC#bOHHVC88RC#N#C_s0OMFk0$ROO#DC"
2;RRRRRRRRRRRRRRRRRMRC8R
RRRRRRRRRRRRRRRRRCCD#RoLCHRM
RRRRRRRRRRRRRRRRRsRR_N#00<CR= R)TB_qi _7q 11)
a;RRRRRRRRRRRRRRRRRRRRH=R<RN8C#s#C0F_Ok-M04R;
RRRRRRRRRRRRRRRRR8CM
RRRRRRRRRRRRRRRR8CM
RRRRRRRRRRRRRRRR#CDCVRHRO5N	=R=RL4'4&R&RNs_O=	R='R4L&jR&_RssRCJ=4=R'2L4RR
RRRRRRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRRRRRR_Rs#00NC=R<RT) _iqB_) );R
RRRRRRRRRRRRRRRRRRPRFDs_Cs_Fs0q5"OF	MI8DCoNCRsPsHCI#RHF0EkN0RRMbC8oHMRJsCk0C#"
2;RRRRRRRRRRRRRRRRRMRC8R
RRRRRRRRRRRRRRDRC#HCRV5R5l_HMN_O	OD$OC=R!RRj2&N&RO&	R&_RsNRO	=4=R'2LjRR
RRRRRRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRRRRRR_Rs#00NC=R<RT) _iqB_) );R
RRRRRRRRRRRRRRRRRRPRFDs_Cs_Fs0q5"OF	MI8DCoNCR#s#C0RC8LFCVsCCRD#NbCVRFRC#bOHHVCl8RHlMHkllRHNM_OO	_$CODROO$DRC#VlsFRJsCk0C#"
2;RRRRRRRRRRRRRRRRRMRC8R
RRRRRRRRRRRRRRDRC#HCRVNR5O=	R='R4L&jR&_RssRCJ=R==4j'L2CRLo
HMRRRRRRRRRRRRRRRRR_Rs#00NC=R<RT) _iqB_QWqaR;
RRRRRRRRRRRRRRRRR<HR=;R4
RRRRRRRRRRRRRRRR[RRRR<=jR;
RRRRRRRRRRRRRCRRMR8RR
RRRRRRRRRRRRRRRMRC8R
RRRRRRRRRRRRRCCD#RoLCHRM
RRRRRRRRRRRRRHRRVNR5O=	R='R4L&4R&_RsNRO	=4=R'2LjRoLCHRM
RRRRRRRRRRRRRRRRR#s_0CN0RR<=)_ Tq_Bi ;))
RRRRRRRRRRRRRRRRFRRPCD_sssF_"05qMO	FCID8RoCNHssPRC#IEH0FRk0NCRbMM8HoCRsJ#kC0;"2
RRRRRRRRRRRRRRRR8CM
RRRRRRRRRRRRCRRMR8
RRRRRRRRRCRRMR8
RRRRRRRRRT) _iqB_QWqa
:RRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRH=R<R+HRR
4;RRRRRRRRRRRRRVRHRO5N	L2RCMoH
RRRRRRRRRRRRRRRR#s_0CN0RR<=)_ Tq_Bi1)aqaR;
RRRRRRRRRRRRR[RRRR<=4R;
RRRRRRRRRRRRR8CM
R
RRRRRRRRRRRRRH5VR5MlH_	NO_OO$D!CR=2RjRR&&5<HRRMlH_	NO_OO$DRC2&
&RSNSSO=	R='R4LR42LHCoMR
RRRRRRRRRRRRRR_Rs#00NC=R<RT) _iqB_) );R
RRRRRRRRRRRRRRPRFDs_Cs_Fs0q5"OF	MI8DCoNCR#s#C0RC8LFCVsCCRD#NbCVRFRC#bOHHVCl8RHlMHkllRHNM_OO	_$CODROO$DRC#VlsFRJsCk0C#"
2;RRRRRRRRRRRRRMRC8R
RRRRRRRRRRRRRCCD#RRHV5N5!OR	2&5&Rl_NGN_O	OD$OC=R!RRj2&H&RRR>=l_NGN_O	OD$OCL2RCMoH
R
RRRRRRRRRRRRRR_Rs#00NC=R<RT) _iqB_) );R
RRRRRRRRRRRRRRPRFDs_Cs_Fs0q5"OF	MI8DCoHCR#FRM0#RN#0CsCI8RHH0EMbR#CVOHHRC8lHNGlRkll_NGN_O	OD$OC$ROO#DCRFVslCRsJ#kC0;"2
RRRRRRRRRRRRCRRMR8
RRRRRRRRRRRRR#CDCVRHRC5sJs_8F=bR='R4L&4R&CRsJ=R=RL4'jL2RCMoH
RRRRRRRRRRRRRRRR#s_0CN0RR<=)_ Tq_Bi ;))
RRRRRRRRRRRRRRRRDFP_sCsF0s_5C")J#kC0#RHRN8C#s#C0RC8LFCVsNCROF	MI8DCoCClMN0RsPsHC2#";R
RRRRRRRRRRRRRC
M8RRRRRRRRRRRRRDRC#HCRVsR5C=JR='R4L&4R&_RssRCJ=4=R'2LjRoLCHRM
RRRRRRRRRRRRRsRR_N#00<CR= R)TB_qi)_ )R;
RRRRRRRRRRRRRFRRPCD_sssF_"05hRCIskCJCR#0NHssPRC#LFCVsbCRsHCPFRk#skCJCR#0HN#ROF	MI8DCo"C82R;
RRRRRRRRRRRRR8CM
RRRRRRRRRRRR8CMRR
RRRRRRRRR)_ Tq_Bi :))RR
RRRRRRRRRRCRLo
HMRRRRRRRRRRRRRVRHRC5sJ=R=RL4'4&R&R	NORR==4j'LRR&&sC_sJ=R=RL4'jL2RCMoH
RRRRRRRRRRRRRRRR#s_0CN0RR<=)_ Tq_BiWaqQ;R
RRRRRRRRRRRRRRRRH<4=R;R
RRRRRRRRRRRRRRRR[<j=R;R
RRRRRRRRRRRRRC
M8RRRRRRRRRRRRRDRC#HCRVsR5C=JR='R4L&4R&_RssRCJ=4=R'RLj&N&RO=	R='R4L&4R&_RsNRO	=4=R'2Lj
RRRRRRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRRRRRRRHV5MlH_	NO_OO$D!CR=2Rj
RRRRRRRRRRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRRRRRRRRRRDFP_sCsF0s_5O"q	IMFDoC8C#RN#0CsCL8RCsVFCDRCNCb#RRFV#ObCHCVH8HRlMkHllHRlMO_N	$_OORDCOD$OCV#RsRFlskCJC"#02R;
RRRRRRRRRRRRRRRRRCRRMR8
RRRRRRRRRRRRRRRRR#CDCR
RRRRRRRRRRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRRRRRRR_Rs#00NC=R<RT) _iqB_q1a)
a;RRRRRRRRRRRRRRRRRRRRRRRH<4=R;R
RRRRRRRRRRRRRRRRRRRRR[=R<R
4;RRRRRRRRRRRRRRRRRRRRC
M8RRRRRRRRRRRRRRRRC
M8RRRRRRRRRRRRRDRC#HCRVNR5O=	R='R4LRj2LHCoMR
RRRRRRRRRRRRRR_Rs#00NC=R<RT) _iqB_q1a)
a;RRRRRRRRRRRRRRRRH=R<R
j;RRRRRRRRRRRRRRRR[=R<R
j;RRRRRRRRRRRRRMRC8R
RRRRRRRRRRMRC8RR
RRRRRRRRRT) _iqB_q7 1)1 a
:RRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRH=R<R4H-;R

RRRRRRRRRRRRR5HVRJsCRR==4j'LRR2
RRRRRRRRRRRRRLRRCMoH
RRRRRRRRRRRRRRRRsRR_N#00<CR= R)TB_qia_1q;)a
RRRRRRRRRRRRRRRRHRRRR<=jR;
RRRRRRRRRRRRRCRRMR8
RRRRRRRRRRRRR#CDCVRH5C5sJ=R=RL4'4&2R&HR5RR==4R22
RRRRRRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRRRRRR#s_0CN0RR<=)_ Tq_Bi ;))
RRRRRRRRRRRRRRRRFRRPCD_sssF_"057Nks0MHFRRFVO0FMHFMkkN#R#s#C0RC8#00NCVRFRJsCk0C#RFPHDCN0#bR#CVOHHRC88#CN#0Cs_kOFMO0R$COD#;"2
RRRRRRRRRRRRRRRR8CM
R
RRRRRRRRRRRRRH5VR5GlN_	NO_MDCoR0E!j=R2&R&R	NORR==44'LRR&&sO_N	=R=RL4'4
2RRRRRRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRRRRR[=R<R4[+;R
RRRRRRRRRRRRRRRRRH5VR[=R>RGlN_	NO_MDCo20ERR
RRRRRRRRRRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRRRRRRR_Rs#00NC=R<RT) _iqB_) );R
RRRRRRRRRRRRRRRRRRRRRF_PDCFsss5_0"s7kNF0HMVRFRMOF0kHMFRk#NC##s80CRN#00FCRVORN	IMFDoC8CHRPF0DNC##RbHCOV8HCRGlNHllkR	NO_GlN_MDCoR0EOD$OC2#";R
RRRRRRRRRRRRRRRRRRMRC8R
RRRRRRRRRRRRRRMRC8R
RRRRRRRRRRRRRCCD#RRHV5N5lGO_N	C_DMEo0RR!=j&2R&ORN	=R=RL4'j
R2RRRRRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRRRRR[=R<R
j;RRRRRRRRRRRRRRRRC
M8RRRRRRRRRRRRRDRC#HCRV5R5l_NGN_O	DoCM0!ER=2RjRR&&NRO	=4=R'RL4&s&R_	NORR==4j'L2RR
RRRRRRRRRRRRRLRRCMoH
RRRRRRRRRRRRRRRRsRR_N#00<CR= R)TB_qi)_ )R;
RRRRRRRRRRRRRRRRRDFP_sCsF0s_5O"q	IMFDoC8CsRNsCHP#HRI0kEF0RRNb8CMHRMoskCJC"#02R;
RRRRRRRRRRRRRCRRMR8
RRRRRRRRRCRRMR8RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
RRRRRRRRRRCOM8N
#CRRRRRRRRs__s#00NC=R<R#s_0CN0;R
RRRRRR_RsNRO	<N=RO
	;RRRRRRRRsC_sJ=R<RJsC;`

HCV8VeRmpB_X]i B_wmw
RRR/F/7R0MFEoHM
D`C#RC
RV`H8RCVm_epQpvuQaBQ_]XB _Bim
wwRRRR/F/7R0MFEoHM
`RRCCD#
R
RRRRRRVRHRP5RN8DH_JsCRR==44'LRR2
RRRRRRRRRoLCHRM
RRRRRRRRR/RR/R7FMEF0H
MoRRRRRRRRRMRC8R
RRRRRRDRC#RC
RRRRRRRRRoLCHRM
RRRRRRRRRFRRPCD_sssF_"05sRCJO0FMN#HMRFXRs"RZ2R;
RRRRRRRRR8CM
R
RRRRRRVRHRP5RN8DH_	NORR==44'LRR2
RRRRRRRRRoLCHRM
RRRRRRRRR/RR/R7FMEF0H
MoRRRRRRRRRMRC8R
RRRRRRDRC#RC
RRRRRRRRRoLCHRM
RRRRRRRRRFRRPCD_sssF_"05NRO	O0FMN#HMRFXRs"RZ2R;
RRRRRRRRR8CM
`
RCHM8V/R/Rpme_uQvpQQBaB_X]i B_wmw
M`C8RHV/m/ReXp_BB] iw_mw

RRRRRRMRC8R
RRRRRCCD#RoLCHRM
RRRRRRRRs0_#NR0C<)=R qT_B1i_aaq);R
RRRRRRsRR_#s_0CN0RR<=)_ Tq_Bi1)aqaR;
RRRRRRRRsO_N	=R<R
j;RRRRRRRRRss_C<JR=;Rj
RRRRRRRRRRH<j=R;R
RRRRRR[RRRR<=jR;
RRRRR8CM
R
RCRM8/N/RD$IN#RRRRRRRRRRRR`

CHM8V/R/Rpme_1q1 _)am
h
`8HVCmVReBp_m)e _
mh
sRRCboRs_CPs,CJRCbsPO_N	
;
RDRNI#N$R5@@bCF#8RoCO2D	RoLCHRM
RVRHRm5`e)p_ a1 _t1QhRqp!4=R'2LjRoLCHRM
RHRRVOR5FsPCN_oCDCCPD=R!Re`mpm_Be_ )h mh2CRLo
HM
RRRRVRHRe5mpm_Be_ )AQq1Bh_m2CRLoRHM/N/L#RHOOCFPsCNo
RRRRRRRRCbsPC_sJ=R<RJsC;R
RRRRRRsRbCNP_O<	R=ORN	R;
RRRRRHRRVbR5s_CPsRCJ!s=RC&JR&sRbCsP_C=JR='R4LRj2LHCoMR
RRRRRRRRRF_PDOCFPs5_0"JsC_#N#CCs08FROPCCs8;"2
RRRRRRRR8CM
RRRRRRRRRHV5CbsPO_N	=R!R	NORR&&bPsC_	NORR==4j'L2CRLo
HMRRRRRRRRRPRFDF_OP_Cs0N5"ON	_#s#C0RC8OCFPs"C82R;
RRRRRCRRMR8
RRRRCRM8/N/L#RHOOCFPsCNo
R
RRMRC8/R/m_epB me)m_hhR 
RMRC8R
RR#CDCCRLo
HM`8HVCmVReQp_h_Qa)
 tRRRRRCbsPC_sJ=R<R
j;RRRRRCbsPO_N	=R<R
j;`8CMHRV
RMRC8R
RCRM8/D/NI#N$
C
`MV8HRR//m_epB me)h_m




