@ER//qCOODsDCN0R1NNM8se8R4R3UmMbCRseCHOVHNF0HMHRpLssN$mR5e3p2
R//qCOODsDCNFRBbH$soRE05RO2.6jj-j.jnq3RDsDRH0oE#CRs#PCsC
83
bRRNlsNCs0CR#N#C_s0MCNlR"=Rq 11)Ta_z1Q Ba h_q1aa; "
R
R`OHMDCk8R0"#8P_FDN_0#E	3"`

HCV8VeRmpB_X]i B_wmw
RRR/F/7R0MFEoHM
D`C#RC
RV`H8RCVm_epQpvuQaBQ_]XB _Bim
wwRRRR/F/7R0MFEoHM
`RRCCD#
IRRHRsCPHND8N_#lCbD_CCPM
0;RHRIsPCRN8DH_N#00CC_G;bs
IRRHRsCPHND8E_OC_O	PkNDC
;
R#RN#MHoRDPNH#8_NDlbCP_CCRM0=5R~#bNlDCC_P0CM^l#Nb_DCCMPC0
2;R#RN#MHoRDPNH#8_0CN0_bCGsRR=~^55#00NCG_Cb^s250^#N_0CCsGb2
2;R#RN#MHoRDPNHO8_E	CO_DPNk=CRR5~5^COEOP	_NCDk2^^5OOEC	N_PD2kC2
;
RV`H8RCVm_ep _h7m1w_QpvzqmaQhR
RICHsRDPNH 8_m
1;R#RN#MHoRDPNH 8_m=1RR`~5m_ep _h7m1w_QpvzqmaQhRR^`pme_7 h__mw1zQvpQqam;h2
CR`MV8HRR//m_ep _h7m1w_QpvzqmaQh`
RCHM8V/R/Rpme_uQvpQQBaB_X]i B_wmw
M`C8RHV/m/ReXp_BB] iw_mw`

HCV8VeRmph_QQva_1Rt
RHRRMHH0NRD
RRRRRDFP_HHM0#_lo;_0RR//BDNDRC0ERCz#sCR7VCHM8MRQHv0RCN##o)CRFHk0M`C
CHM8V/R/m_epQahQ_tv1
H
`VV8CRpme_]XB _Bim
wwR/RR/R7FMEF0H
Mo`#CDCR
R`8HVCmVReQp_vQupB_QaX B]Bmi_wRw
R/RR/R7FMEF0H
MoRCR`D
#CRCRsoNRPD_H8sN_#lCbD_CCPM
0;RV`H8RCVm_ep _h7m1w_QpvzqmaQhR
RsRCoPHND8__s ;m1
CR`MV8HRR//m_ep _h7m1w_QpvzqmaQhR
RNNDI$@#R@F5b#oC8CDRO	sRFRoMCCC8oRe`mp _)1_ a1hQtq
p2RRRRLHCoMR
RRRRRH5VR`pme_1)  1a_Qqthp=R!RL4'4R2
RRRRRLRRCMoH
RRRRRRRRPRRN8DH_#s_NDlbCP_CCRM0<4=R';L4
HR`VV8CRpme_7 h__mw1zQvpQqamRh
RRRRRRRRRDPNHs8__1 mRR<=44'L;`
RCHM8V/R/Rpme_7 h__mw1zQvpQqamRh
RRRRRCRRMR8
RRRRR#CDCR
RRRRRRCRLo
HMRRRRRRRRRNRPD_H8sN_#lCbD_CCPM<0R=NRPD_H8#bNlDCC_P0CM;`
RHCV8VeRmph_ 7w_m_v1QzapqQ
mhRRRRRRRRRNRPD_H8sm_ 1=R<RDPNH 8_m
1;RM`C8RHV/m/Re p_hm7_wQ_1vqzpahQm
RRRRRRRR8CM
RRRR8CM
CR`MV8HRR//m_epQpvuQaBQ_]XB _Bim
ww`8CMH/VR/eRmpB_X]i B_wmw
H
`VV8CRpme_1q1 _)am
h
RCRso_Rs#bNlDCC_P0CM;R

RINDNR$#@b@5F8#CoOCRDR	2LHCoMR
RRHRRV`R5m_ep)  1aQ_1tphqRR!=4j'L2CRLo
HMRRRRRRRRsN_#lCbD_CCPM<0R=NR#lCbD_CCPM
0;RRRRR8CM
RRRRDRC#LCRCMoH
V`H8RCVm_epQahQ_t) 
RRRRRRRR#s_NDlbCP_CCRM0<j=R;C
`MV8H
RRRRMRC8R
RC
M8
HR`VV8CRpme_7 h__mw1zQvpQqamRh
RsRRCsoR_1 m;R
RRDRNI#N$R5@@bCF#8RoCO2D	R s_m<1R=mR`e p_hm7_wQ_1vqzpahQm;`
RCHM8V/R/m_ep _h7m1w_QpvzqmaQhR

RINDNR$#@b@5F8#CoOCRDR	2LHCoMR
RRVRHRm5`e)p_ a1 _t1QhRqp!4=R'2LjRoLCHRM
`8HVCmVRe p_hm7_wQ_1vqzpahQm
RRRRRRRRRHV5s55_1 mRR==4j'LRR&&`pme_7 h__mw1zQvpQqam=hR=L4'4|2R|RR
RRRRRRRRRRRR5#s_NDlbCP_CCRM0=4=R'RLj&#&RNDlbCP_CCRM0=4=R'2L42&R&RS
S5N#00CC_GRbsRR!=OOEC	N_PD2kC2CRLo
HMRD`C#RC
RRRRRHRRV5R5sN_#lCbD_CCPM=0R='R4L&jR&NR#lCbD_CCPM=0R='R4LR42&
&RS#S50CN0_bCGs!RR=EROC_O	PkNDCR22LHCoM`
RCHM8V/R/m_ep _h7m1w_QpvzqmaQhR
RRRRRRRRRF_PDCFsss5_0"N100CCRGCbs#F#HM#RHR0MFRkCJN0DRFEROC_O	PkNDCERIHRDC#bNlDCCRP0CMRRH#NC##s80C"
2;RRRRRRRRC
M8
H
`VV8CRpme_]XB _Bim
wwR/RR/R7FMEF0H
Mo`#CDCR
R`8HVCmVReQp_vQupB_QaX B]Bmi_wRw
R/RR/R7FMEF0H
MoRCR`D
#CRHR`VV8CRpme_7 h__mw1zQvpQqamRh
RRRRRHRRV5R55 s_m=1R='R4L&jR&mR`e p_hm7_wQ_1vqzpahQmR4=='2L4R
||RRRRRRRRRRRRR_5s#bNlDCC_P0CMRR==4j'LRR&&#bNlDCC_P0CMRR==44'L2
22RCR`D
#CRRRRRRRRH5VR5#s_NDlbCP_CCRM0=4=R'RLj&#&RNDlbCP_CCRM0=4=R'2L42R
R`8CMH/VR/pme_7 h__mw1zQvpQqamRh
RRRRRRRRRoLCHRM
RRRRRRRRRHRRVPR5N8DH_N#00CC_GRbs=4=R'2L4
RRRRRRRRRRRRLRRCMoH
RRRRRRRRRRRRRRRR8//FFRM0MEHoR
RRRRRRRRRRRRRC
M8RRRRRRRRRRRRCCD#
RRRRRRRRRRRRLRRCMoH
RRRRRRRRRRRRRRRRDFP_sCsF0s_50"#N_0CCsGbRMOF0MNH#RRXFZsR"
2;RRRRRRRRRRRRRMRC8R
RRRRRRRRRC
M8
`RRHCV8VeRmph_ 7w_m_v1QzapqQ
mhRRRRRRRRH5VR5_5s Rm1=4=R'RLj&`&Rm_ep _h7m1w_QpvzqmaQh=R=44'L2|R|
RRRRRRRRRRRRsR5_l#Nb_DCCMPC0=R=RL4'j&R&Rl#Nb_DCCMPC0=R=RL4'4222
`RRCCD#
RRRRRRRRRHV5_5s#bNlDCC_P0CMRR==4j'LRR&&#bNlDCC_P0CMRR==44'L2R2
RM`C8RHV/m/Re p_hm7_wQ_1vqzpahQm
RRRRRRRRLRRCMoH
RRRRRRRRRRRRRHV5DPNHO8_E	CO_DPNk=CR='R4L
42RRRRRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRR/F/8R0MFEoHM
RRRRRRRRRRRRCRRMR8
RRRRRRRRRCRRD
#CRRRRRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRRF_PDCFsss5_0"COEOP	_NCDkRMOF0MNH#RRXFZsR"
2;RRRRRRRRRRRRRMRC8R
RRRRRRRRRC
M8
RRRRRRRRRHV5DPNHs8__l#Nb_DCCMPC0=R=RL4'4R2
RRRRRRRRRoLCHRM
RRRRRRRRRHRRVsR5_l#Nb_DCCMPC0=R=RL4'jR2
RRRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRRHRRVPR5N8DH_l#Nb_DCCMPC0=R=RL4'4R2
RRRRRRRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRRRRRR/RR/FR7R0hFEoHM
RRRRRRRRRRRRRRRRCRRMR8
RRRRRRRRRRRRRCRRD
#CRRRRRRRRRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRRRRRRF_PDCFsss5_0"l#Nb_DCCMPC0FROMH0NMX#RRRFsZ;"2
RRRRRRRRRRRRRRRRCRRMR8
RRRRRRRRRRRRR8CM
RRRRRRRRCRRMR8
RRRRRCRRDR#CH5VRPHND8N_#lCbD_CCPM=0R='R4L
42RRRRRRRRRCRLo
HMRRRRRRRRRRRRH5VR#bNlDCC_P0CMRR==44'L2R
RRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRRPRFDs_Cs_Fs0#5"NDlbCP_CCRM0O0FMN#HMRFXRs"RZ2R;
RRRRRRRRRRRRR8CM
RRRRRRRRCRRMR8
RRRRRCRRD
#CRRRRRRRRRCRLo
HMRRRRRRRRRRRRF_PDCFsss5_0"l#Nb_DCCMPC0FROMH0NMX#RRRFsZ;"2
RRRRRRRRCRRM
8
RHR`VV8CRpme_7 h__mw1zQvpQqamRh
RRRRRHRRVPR5N8DH_ s_m=1R='R4L
42RRRRRRRRRCRLo
HMRRRRRRRRRRRRH5VRsm_ 1=R=RL4'jR2
RRRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRRHRRVPR5N8DH_1 mRR==44'L2R
RRRRRRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRRRRRR/R/RR7FhEF0H
MoRRRRRRRRRRRRRRRRRMRC8R
RRRRRRRRRRRRRRDRC#RC
RRRRRRRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRRRRRRFRRPCD_sssF_"05`pme_7 h__mw1zQvpQqamOhRFNM0HRM#XsRFR2Z";R
RRRRRRRRRRRRRRRRRC
M8RRRRRRRRRRRRRMRC8R
RRRRRRRRRC
M8RRRRRRRRCCD#RRHV5DPNH 8_m=1R='R4L
42RRRRRRRRRCRLo
HMRRRRRRRRRRRRH5VR`pme_7 h__mw1zQvpQqam=hR='R4L
42RRRRRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRRF_PDCFsss5_0"e`mph_ 7w_m_v1QzapqQRmhO0FMN#HMRFXRs"RZ2R;
RRRRRRRRRRRRR8CM
RRRRRRRRCRRMR8
RRRRRCRRD
#CRRRRRRRRRCRLo
HMRRRRRRRRRRRRF_PDCFsss5_0"e`mph_ 7w_m_v1QzapqQRmhO0FMN#HMRFXRs"RZ2R;
RRRRRRRRR8CM
`RRCHM8V/R/Rpme_7 h__mw1zQvpQqamRh
`8CMH/VR/eRmpv_QuBpQQXa_BB] iw_mwC
`MV8HRR//m_epX B]Bmi_w
w

RRRR8CM
CRRM
8
`8CMH/VR/eRmp1_q1a )_
mh
