@ER//qCOODsDCN0R1NNM8se8R4R3UmMbCRseCHOVHNF0HMHRpLssN$mR5e3p2
R//qCOODsDCNFRBbH$soRE05RO2.6jj-j.jnq3RDsDRH0oE#CRs#PCsC
83
bRRNlsNCs0CRqB]h_t 1)aqaRR=4j'L;R
RbNNslCC0s]RBq ht_ B]B=iRRL4'4
;
RCRso_RsOMENo
C;RCRsoIRrHE80-j4:9_Rs00C#_bCGsR;
RosCR#s_0CN0;R
RHCM0oRCsH
;
`8HVCmVReXp_BB] iw_mwR
RR7//FFRM0MEHoC
`D
#CRHR`VV8CRpme_uQvpQQBaB_X]i B_wmw
RRRR7//FFRM0MEHoR
R`#CDCR
RICHsRDPNH#8_00Ns_CCPM
0;RHRIsPCRN8DH_#0C0G_Cb
s;R#RN#MHoRDPNH#8_00Ns_CCPM=0RR#~500Ns_CCPM#0^00Ns_CCPM;02
NRR#o#HMNRPD_H800C#_bCGsRR=~^5500C#_bCGs52^^#0C0G_Cb2s2;`
RCHM8V/R/Rpme_uQvpQQBaB_X]i B_wmw
M`C8RHV/m/ReXp_BB] iw_mw


RMRHHN0HDCRLo
HMRRRRH5VR~N55OF0HMM_F_IMC_N#0s=0R=mR`eQp_t)hm  _hWa_1q2)aR
||RRRRRRRRRNR5OF0HMM_F_IMC_N#0s=0R=mR`e)p_ a1 __mhh_ W1)aqa|2R|R
RRRRRRRRR50NOH_FMFMM_C#I_00NsRR==`pme_) )mm)_h _hWa_1q2)a2L2RCMoH
RRRRFRRPCD_sssF_"05QCDDoRNDPkNDCCR#0FRVsNRbsCNl0RCsNHO0FFM_MC_MI0_#N"s02R;
RCRRMR8
RsRR_N#00BC=]tqh a_1q;)a
RRRROs_EoNMC'=4L
j;RMRC8R

RsbNN0lCCNsR#s#C0N_Ml=CRR1"q1a )_qB]h"t ;R

RM`HO8DkC#R"0F8_P0D_N3#	E
"
`8HVCmVReQp_h_Qav
1tRRRRH0MHH
NDRRRRRPRFDM_HHl0_#0o_;/R/RDBNDER0C#RzC7sRCMVHCQ8RMRH0v#C#NRoC)0FkH
MC`8CMH/VR/pme_QQha1_vt`

HCV8VeRmp]_1q7) _7Bm R

RINDNR$#@b@5F8#CoOCRDR	2LHCoMR
RRRRRH5VR`pme_1)  1a_Qqthp=R!RL4'jL2RCMoHRR//NHO0PDCRFsIRC0#C
RRRRRRRR#ONCsR5_N#00
C2RRRRRRRRR]RBq ht_q1a)Ra:LHCoM`

HCV8VeRmpB_X]i B_wmw
RRR/F/7R0MFEoHM
D`C#RC
RV`H8RCVm_epQpvuQaBQ_]XB _Bim
wwRRRR/F/7R0MFEoHM
`RRCCD#
`RRHCV8VeRmp1_q1a )_
mhRRRR/7/RFER0C/RGxEROCHO	MRo
RRRRRRRRRHRRVPR5N8DH_N#0sC0_P0CMRR==44'L2R
RRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRR/R/RR7FMEF0H
MoRRRRRRRRRRRRRMRC8R
RRRRRRRRRRDRC#RC
RRRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRRRRRRDFP_sCsF0s_50"#N_s0CMPC0FROMH0NMX#RRRFsZ;"2
RRRRRRRRRRRRCRRMR8
RM`C8RHV/m/Reqp_1)1 ah_m
CR`MV8HRR//m_epQpvuQaBQ_]XB _Bim
ww`8CMH/VR/eRmpB_X]i B_wmw
R
RRRRRRRRRRVRHR05#N_s0CMPC0=R=RL4'4L2RCMoH
RRRRRRRRRRRRsRR_NOEMRoC<4=R';Lj
RRRRRRRRRRRRsRR_N#00<CR=]RBq ht_ B]B
i;RRRRRRRRRRRRR_Rs00C#_bCGs=R<R#0C0G_Cb
s;RRRRRRRRRRRRRRRH<M=RkOl_	
#;
V`H8RCVm_epX B]Bmi_wRw
R/R/7MFRFH0EM`o
CCD#
`RRHCV8VeRmpv_QuBpQQXa_BB] iw_mwR
RR/R/7MFRFH0EMRo
RD`C#RC
RV`H8RCVm_epq 11)ma_hR
RRRRRRRRRRVRHRN5PD_H800C#_bCGs=R=RL4'4R2
RRRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRR/RR/FR7R0MFEoHM
RRRRRRRRRRRRCRRMR8
RRRRRRRRRCRRD
#CRRRRRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRRRPRFDs_Cs_Fs005"C_#0CsGbRMOF0MNH#RRXFZsR"
2;RRRRRRRRRRRRRMRC8R
R`8CMH/VR/eRmp1_q1a )_
mhRM`C8RHV/m/ReQp_vQupB_QaX B]Bmi_w`w
CHM8V/R/Rpme_]XB _Bim
ww
`
RHCV8VeRmpm_Be_ )mRh
RRRRRRRRRRRRRRHV5POFCosNCC_DPRCD!`=Rm_epB me)m_hhR 2LHCoMR
RRRRRRRRRRRRRRRHV5pme_eBm A)_qB1Q_2mhRoLCH/MR/#LNHOORFsPCN
oCRRRRRRRRRRRRRRRRF_PDOCFPs5_0"MIH8_FIFMbCRPOFC8sC"
2;RRRRRRRRRRRRRCRRMR8
RRRRRRRRRRRRR8CM
CR`MV8HRR//m_epB me)h_m
RRRRRRRRRRRR8CM
R
RRRRRRRRRC
M8RRRRRRRRR]RBq ht_ B]BRi:LHCoM`

HCV8VeRmpB_X]i B_wmw
RRR/F/7R0MFEoHM
D`C#RC
RV`H8RCVm_epQpvuQaBQ_]XB _Bim
wwRRRR/F/7R0MFEoHM
`RRCCD#
`RRHCV8VeRmp1_q1a )_
mhRRRR/7/RFER0C/RGxEROCHO	MRo
RRRRRRRRRHRRVNR5OF0HMM_F_IMC_N#0s!0R=mR`eQp_t)hm  _hWa_1q2)a
RRRRRRRRRRRRLRRCMoH
RRRRRRRRRRRRRRRRRHV5DPNH#8_00Ns_CCPM=0R='R4L
42RRRRRRRRRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRRRRRR/7/RFFRM0MEHoR
RRRRRRRRRRRRRRRRRC
M8RRRRRRRRRRRRRRRRCCD#
RRRRRRRRRRRRRRRRLRRCMoH
RRRRRRRRRRRRRRRRRRRRDFP_sCsF0s_50"#N_s0CMPC0FROMH0NMX#RRRFsZ;"2
RRRRRRRRRRRRRRRRCRRMR8
RRRRRRRRRRRRR8CM
RRRRRRRRRRRRRHV5DPNH08_C_#0CsGbRR==44'L2R
RRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRR/R/RR7FMEF0H
MoRRRRRRRRRRRRRMRC8R
RRRRRRRRRRDRC#RC
RRRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRRRRRRDFP_sCsF0s_5C"0#C0_GRbsO0FMN#HMRFXRs"RZ2R;
RRRRRRRRRRRRR8CM
`RRCHM8V/R/Rpme_1q1 _)amRh
`8CMH/VR/eRmpv_QuBpQQXa_BB] iw_mwC
`MV8HRR//m_epX B]Bmi_w
w
RRRRRRRRRRRRR/R/RkBFMO0RD	FORO0H	R#
RRRRRRRRRRRRRRHV5N#0sC0_P0CMRR==44'L2CRLo
HMRRRRRRRRRRRRRRRRH5VRNHO0FFM_MC_MI0_#NRs0=`=Rm_epQmth)h _ 1W_aaq)RR&&HRR>jR2
RRRRRRRRRRRRRRRRR<HR=-RH4R;
RRRRRRRRRRRRRCRRDR#CH5VRNHO0FFM_MC_MI0_#NRs0=`=Rm_ep)  1ah_m_Wh _q1a)Ra2LHCoMR
RRRRRRRRRRRRRRRRRsE_ONCMoRR<=4j'L;R
RRRRRRRRRRRRRRRRRH=R<RlMk_#O	;R
RRRRRRRRRRRRRRRRR`8HVCmVReBp_m)e _
mhRRRRRRRRRRRRRRRRRVRHRF5OPNCsoDC_CDPCRR!=`pme_eBm h)_m2h RoLCHRM
RRRRRRRRRRRRRRRRRVRHRe5mpm_Be_ )Bhm) m)_hL2RCMoHRO//FCsMsFROPNCsoRC
RRRRRRRRRRRRRRRRRHRRVNR5OF0HMM_F_IMC_N#0s=0R=mR`e)p_ a1 __mhh_ W1)aqaL2RCMoH
RRRRRRRRRRRRRRRRRRRRFRRPOD_FsPC_"05I8HMFsI_C0#C#FROPCCs8;"2
RRRRRRRRRRRRRRRRRRRR8CM
RRRRRRRRRRRRRRRRRRRC
M8RRRRRRRRRRRRRRRRRMRC8R
RRRRRRRRRRRRRRRRR`8CMH/VR/eRmpm_Be_ )mRh
RRRRRRRRRRRRRCRRMR8
RRRRRRRRRRRRRCRRDR#CH5VRNHO0FFM_MC_MI0_#NRs0=`=Rm_ep m)))h_m_Wh _q1a)Ra2LHCoMR
RRRRRRRRRRRRRRRRRH=R<R4H-;R
RRRRRRRRRRRRRRRRR`8HVCmVReqp_1)1 ah_m
RRRRRRRRRRRRRRRRFRRPCD_sssF_"051s0N0PRCCRM0CDPNkCN08)RazL RCsVFCCR0#C0RGCbs#F#HMERONCMo8;"2
RRRRRRRRRRRRRRRR`RRCHM8V/R/Rpme_1q1 _)amRh
RRRRRRRRRRRRRCRRM
8RRRRRRRRRRRRRRMRC8R
RRRRRRRRRRRRRCCD#RRHV5>HRR
j2RRRRRRRRRRRRRRRRH=R<R4H-;R

RRRRRRRRRRRRRRHV50s_C_#0CsGbRR!=00C#_bCGs&R&R#!500Ns_CCPM=0R='R4L&4R&R
RRRRRRRRRRRRRRRRRRRRRRRRRNHO0FFM_MC_MI0_#NRs0=`=Rm_ep)  1ah_m_Wh _q1a)2a2RoLCHRM
RRRRRRRRRRRRRsRR_NOEMRoC<4=R';L4
RRRRRRRRRRRRCRRM
8
RRRRRRRRRRRRR/R/RRoF0#FR00NsRN#00FCRMNRD#O0RE	CO
RRRRRRRRRRRRHRRVHR5RR==4&R&R#!500Ns_CCPM=0R='R4L&4R&R
RRRRRRRRRRRRRRRRRRRRRRRRRNHO0FFM_MC_MI0_#NRs0=`=Rm_ep)  1ah_m_Wh _q1a)2a2RoLCHRM
RRRRRRRRRRRRRsRR_N#00<CR=]RBq ht_q1a)
a;
RRRRRRRRRRRRRRRRV`H8RCVm_epB me)h_m
RRRRRRRRRRRRRRRRRHV5POFCosNCC_DPRCD!`=Rm_epB me)m_hhR 2LHCoMR
RRRRRRRRRRRRRRHRRVmR5eBp_m)e _1AqQmB_hL2RCMoHRL//NO#HRPOFCosNCRR
RRRRRRRRRRRRRRRRRDFP_POFC0s_5H"IMI8F_FOD#OCRFsPCC28";R
RRRRRRRRRRRRRRCRRM
8RRRRRRRRRRRRRRRRRC
M8RRRRRRRRRRRRRRRR`8CMH/VR/eRmpm_Be_ )m
h
RRRRRRRRRRRRRRRR/B/RE	CORN0E0ER0CsRbFsbC0H$R#sR0kRC
RRRRRRRRRRRRR`RRHCV8VeRmp1_q1a )_
mhRRRRRRRRRRRRRRRRH5VR5Os_EoNMC=R!RL4'4&2R&sR5_#0C0G_Cb=sR=CR0#C0_G2bs2CRLo
HMRRRRRRRRRRRRRRRRRPRFDs_Cs_Fs0a5"CR#0CsGbCH##F8MRHM8RFO0REoNMCNRPDRkCIEH0HMMRkOl_	O#R$COD#VRN0RCs#s0N0PRCC"M02R;
RRRRRRRRRRRRRCRRMR8
RRRRRRRRRRRRR`RRCHM8V/R/Rpme_1q1 _)amRh
RRRRRRRRRRRRR8CM
RRRRRRRRRRRRsRR_#0C0G_Cb<sR=CR0#C0_G;bs
R
RRRRRRRRRC
M8RRRRRRRRCOM8N
#CRRRRRMRC8R
RRRRRCCD#RoLCHRM
RRRRRRRRs0_#NR0C<B=R]tqh a_1q;)a
RRRRRRRR_RsOMENo<CR='R4L
j;RRRRRRRRR<HR=;Rj
V`H8RCVm_epQahQ_t) 
RRRRRRRR_Rs00C#_bCGs=R<RH{I8{0E4j'L}
};`8CMHRV
RRRRR8CM
CRRM/8R/DRNI#N$RRRRRRRRRRRR
C
`MV8HRR//m_ep1)]q B7_m
7 
