//DSP56_12X12SUM
@E8lFkRDC761un._4X14.z5vR7amz,qRB1Rm,qRj,ARj,qR4,AR4,BQq1,BRqBqpm7q,R7z71AB,RpRi,BR ,)  1a
2;
sbNN0lCCqsRjt) _iBpR"=RAqYu1;1"RR//"uAYq"11,p"Bi,j""iBp4b"
NlsNCs0CR)qj Bt_ RR="jB "/;R/BR" ,j""4B "N
bsCNl0RCsq j)t _)1R a=)R" a1 jR";/)/" a1 jR","1)  "a4
N
bsCNl0RCsq 4)tp_BiRR="uAYq"11;/R/RY"Au1q1"B,"p"ij,p"Bi
4"bNNslCC0s4Rq)_ tB= RR "BjR";/"/RB" j, "B4b"
NlsNCs0CR)q4 )t_ a1 R"=R)  1a;j"R"//)  1a,j"R ")14 a"b

NlsNCs0CR)Aj Bt_p=iRRY"Au1q1"/;R/AR"Y1uq1"",Bjpi"B,"p"i4
sbNN0lCCAsRjt) _RB =BR" ;j"RR//"jB "B," 
4"bNNslCC0sjRA)_ t)  1aRR="1)  "aj;/R/"1)  "aj,)R" a1 4
"
bNNslCC0s4RA)_ tBRpi=AR"Y1uq1R";/"/RAqYu1,1""iBpj"",B4pi"N
bsCNl0RCsA 4)t _BR"=RB" j;/R/R "Bj"",B" 4
sbNN0lCCAsR4t) _1)  =aRR ")1j a"/;R/ ")1j a"",R)  1a
4"
sbNN0lCCqsRBmBpqQ7_)_ tBRpi=AR"Y1uq1R";/"/RAqYu1,1""iBpj"",B4pi"N
bsCNl0RCsqpBBm_q7Qt) _RB =BR" ;j"RR//"jB "B," 
4"bNNslCC0sBRqBqpm7)_Q )t_ a1 R"=R)  1a;j"R"//)  1a,j"R ")14 a"b

NlsNCs0CR7q71jzA_ Q)tp_BiRR="uAYq"11;/R/RY"Au1q1"B,"p"ij,p"Bi
4"bNNslCC0s7Rq7A1zj)_Q Bt_ RR="jB "/;R/BR" ,j""4B "N
bsCNl0RCsq177z_AjQt) _1)  =aRR ")1j a"/;R/ ")1j a"",R)  1a
4"
sbNN0lCCqsR7z71AQ4_)_ tBRpi=AR"Y1uq1R";/"/RAqYu1,1""iBpj"",B4pi"N
bsCNl0RCsq177z_A4Qt) _RB =BR" ;j"RR//"jB "B," 
4"bNNslCC0s7Rq7A1z4)_Q )t_ a1 R"=R)  1a;j"R"//)  1a,j"R ")14 a"b

NlsNCs0CR u)tBj_p=iRRY"Au1q1"/;R/AR"Y1uq1"",Bjpi"B,"p"i4RRRRRl//kjD0RbbHCMDHCCRso0H#Cbs
NlsNCs0CR u)tBj_ RR="jB "/;R/BR" ,j""4B "N
bsCNl0RCsut) j _)1R a=)R" a1 jR";/)/" a1 jR","1)  "a4
N
bsCNl0RCsut) 4p_BiRR="uAYq"11;/R/RY"Au1q1"B,"p"ij,p"BiR4"RRRR/k/lDR04bCHbDCHMRosCHC#0sN
bsCNl0RCsut) 4 _BR"=RB" j;/R/R "Bj"",B" 4
sbNN0lCCusR)4 t_1)  =aRR ")1j a"/;R/ ")1j a"",R)  1a
4"
sbNN0lCCwsRA)_u =tRRL4'j/;R/'R4L"j,AqYu1;1"44'L,h" q Ap"RRRR/RR/CVC8OLN	ORNOHRbbHCDMsCRC#oH0,Cs#CNlR	OD//OCsCC#0#RNR m)tb

NlsNCs0CRBqBp7mq_ u)tp_BiRR="uAYq"11;/R/RY"Au1q1"B,"p"ij,p"Bi
4"bNNslCC0sBRqBqpm7)_u Bt_ RR="jB "/;R/BR" ,j""4B "N
bsCNl0RCsqpBBm_q7ut) _1)  =aRR ")1j a"/;R/ ")1j a"",R)  1a
4"
sbNN0lCCqsR7z71Auj_)_ tBRpi=AR"Y1uq1R";/"/RAqYu1,1""iBpj"",B4pi"N
bsCNl0RCsq177z_Ajut) _RB =BR" ;j"RR//"jB "B," 
4"bNNslCC0s7Rq7A1zj)_u )t_ a1 R"=R)  1a;j"R"//)  1a,j"R ")14 a"b

NlsNCs0CR7q714zA_ u)tp_BiRR="uAYq"11;/R/RY"Au1q1"B,"p"ij,p"Bi
4"bNNslCC0s7Rq7A1z4)_u Bt_ RR="jB "/;R/BR" ,j""4B "N
bsCNl0RCsq177z_A4ut) _1)  =aRR ")1j a"/;R/ ")1j a"",R)  1a
4"
sbNN0lCCmsR)_ tBRpi=AR"Y1uq1R";/"/RAqYu1,1""iBpj"",B4pi"N
bsCNl0RCsmt) _RB =BR" ;j"RR//"jB "B," 
4"bNNslCC0s)Rm )t_ a1 R"=R)  1a;j"R"//)  1a,j"R ")14 a"b

NlsNCs0CRpvza _)1_ av m7R"=R1BYh"/;/Rh1YB1,qY
hBbNNslCC0s)Ru m_pq=7RR'6n8
j;bNNslCC0sqRB1 Q_hRR="pwq1; "/w/"q p1"8:RHL#NDOCRN5#HjR2;"za) C":MDNLCNRO#OH5N2#H
F

kk0b06Rr69:jRz7maB,Rq;1m
bHMkR0Rr:44jq9RjA,Rjq,R4A,R4H;
M0bkR6Rr69:jR1BqQH;
M0bkRBRqBqpm7H;
M0bkR4Rr:Rj9q177z
A;HkMb0rRR49:jRiBp, RB, R)1; a
C
sojRq_iBp,_qjBq ,j _)1, aqB4_pqi,4 _B,_q4)  1aj,A_iBp,_AjBA ,j _)1, aAB4_pAi,4 _B,_A4)  1aB,qBqpm7B_Qpqi,BmBpqQ7_Bq ,BmBpqQ7_)  1a7,q7A1zjB_Qpqi,7z71AQj_Bq ,7z71AQj_)  1a7,q7A1z4B_Qpqi,7z71AQ4_Bq ,7z71AQ4_)  1aj,u_iBp,_ujBu ,j _)1, auB4_pui,4 _B,_u4)  1aB,qBqpm7B_upqi,BmBpqu7_Bq ,BmBpqu7_)  1a7,q7A1zjB_upqi,7z71Auj_Bq ,7z71Auj_)  1a7,q7A1z4B_upqi,7z71Au4_Bq ,7z71Au4_)  1a_,mB,pim _B,)m_ a1 ;C
so4Rr49:jRNHMjC_so#_N$,MOHjMN_osC_M#$OM,HNs4_CNo_#O$M,NHM4C_so$_#MHO,M,NjHjMN_osC,NHM4M,HNs4_CHo,MbN_s_CoNM#$OM,HNs_bC#o_$,MOH_MNbosC,#N_s
O;sRCor:44jH9RM_Ljs_CoNM#$OM,HLsj_C#o_$,MOH4ML_osC_$N#MHO,M_L4s_Co#O$M,LHMjM,HLsj_CHo,M,L4H4ML_osC;C
soNRROFODN_8js_CoNM#$OO,NONDF8sj_C#o_$,MONDOOF_N8jO,NONDF8sj_CNo,OFODN_84s_CoNM#$OO,NONDF8s4_C#o_$,MONDOOF_N84O,NONDF8s4_C
o;sRCoN#88k_LjsjCo_$N#MNO,8k8#Lsj_C_oj#O$M,8N8#jkL_osCj8,N8L#kj,_jN#88k_Ljs4Co_$N#MNO,8k8#Lsj_C_o4#O$M,8N8#jkL_osC48,N8L#kj;_4
osCR8N8#4kL_osCj#_N$,MON#88k_L4sjCo_M#$O8,N8L#k4C_soNj,8k8#Lj4_,8N8#4kL_osC4#_N$,MON#88k_L4s4Co_M#$O8,N8L#k4C_soN4,8k8#L44_;H
IsrCR.jd:9jRN,,Ljl0kD_0Fkj4,N,,L4l0kD_0Fk4s;
CroR.jd:9kRF0sj_CNo_#O$M,0FkjC_so$_#MFO,k,0jFjk0_osC,0Fk4C_so#_N$,MOF4k0_osC_M#$Ok,F0F4,k_04s;Co
osCRnr6:Rj98k_F0k,F0s_bCNo_#O$M,0Fk_Cbso$_#MFO,kb0_s,Co80Fk_osC,kND_0Fk;H
IsrCR6j6:9_RlFjk0,Fl_k,04N_OOD8FN,O8_N;#H
osCRnr6:Rj9F_k0s_CoNM#$Ok,F0C_so$_#MFO,ks0_C
o;
I//HRsCo0s#MRR=t31)tm1);k
#b$bDjhRt7
;R#bkbDR$4e;BBRI
RHRsCo0s#M/;R/RR=t31)tm1);N
R#o#HMsRo#R0M=BReB
;

INDNR$#@H@5M_Njs_CoNM#$OsRFRNHMjC_so$_#MFORsMRHNs4_CNo_#O$MRRFsH4MN_osC_M#$OsRFRLHMjC_so#_N$RMOFHsRM_Ljs_Co#O$MRRFsH4ML_osC_$N#MFORsMRHLs4_C#o_$RMOFHsRMbN_s_CoNM#$OsRFRNHM_Cbso$_#MFORsORNONDF8sj_CNo_#O$MRRFsNDOOFjN8_osC_M#$OsRFRONOD8FN4C_so#_N$RMOFNsROFODN_84s_Co#O$MRRFsN#88k_LjsjCo_$N#MFORs8RN8L#kjC_so#j_$RMOFNsR8k8#Lsj_C_o4NM#$OsRFR8N8#jkL_osC4$_#MFORs8RN8L#k4C_soNj_#O$MRRFsN#88k_L4sjCo_M#$OsRFR8N8#4kL_osC4#_N$RMOFNsR8k8#Ls4_C_o4#O$MRRFsFjk0_osC_$N#MFORskRF0sj_C#o_$RMOFFsRk_04s_CoNM#$OsRFR0Fk4C_so$_#MFORskRF0s_bCNo_#O$MRRFsF_k0bosC_M#$OsRFR0Fk_osC_M#$OsRFR0Fk_osC_$N#M
O2RRRRLHCoMR
RRRRRRVRHRz5vp)a_ a1 _7vm =R=R1"qY"hB2R
RRRRRRCRLo
HMRRRRRRRRRRRRHjMN_osCRR<=HjMN_osC_$N#M
O;RRRRRRRRRRRRH4MN_osCRR<=H4MN_osC_$N#M
O;RRRRRRRRRRRRHjML_osCRR<=HjML_osC_$N#M
O;RRRRRRRRRRRRH4ML_osCRR<=H4ML_osC_$N#M
O;RRRRRRRRRRRRNDOOFjN8_osCRR<=NDOOFjN8_osC_$N#M
O;RRRRRRRRRRRRNDOOF4N8_osCRR<=NDOOF4N8_osC_$N#M
O;RRRRRRRRRRRRN#88k_LjsjCoRR<=N#88k_LjsjCo_$N#M
O;RRRRRRRRRRRRN#88k_Ljs4CoRR<=N#88k_Ljs4Co_$N#M
O;RRRRRRRRRRRRN#88k_L4sjCoRR<=N#88k_L4sjCo_$N#M
O;RRRRRRRRRRRRN#88k_L4s4CoRR<=N#88k_L4s4Co_$N#M
O;RRRRRRRRRRRRFjk0_osCRR<=Fjk0_osC_$N#M
O;RRRRRRRRRRRRF4k0_osCRR<=F4k0_osC_$N#M
O;RRRRRRRRRRRRF_k0bosCRR<=F_k0bosC_$N#M
O;RRRRRRRRRRRRH_MNbosCRR<=H_MNbosC_$N#M
O;RRRRRRRRRRRRF_k0sRCo<F=Rks0_CNo_#O$M;R
RRRRRRMRC8R
RRRRRRDRC#HCRVvR5z_pa)  1am_v7= R=1R"Y"hB2R
RRRRRRCRLo
HMRRRRRRRRRRRRHjMN_osCRR<=HjMN_osC_M#$OR;
RRRRRRRRRHRRM_N4sRCo<H=RM_N4s_Co#O$M;R
RRRRRRRRRRMRHLsj_C<oR=MRHLsj_C#o_$;MO
RRRRRRRRRRRRLHM4C_so=R<RLHM4C_so$_#M
O;RRRRRRRRRRRRNDOOFjN8_osCRR<=NDOOFjN8_osC_M#$OR;
RRRRRRRRRNRROFODN_84sRCo<N=ROFODN_84s_Co#O$M;R
RRRRRRRRRR8RN8L#kjC_so<jR=8RN8L#kjC_so#j_$;MO
RRRRRRRRRRRR8N8#jkL_osC4=R<R8N8#jkL_osC4$_#M
O;RRRRRRRRRRRRN#88k_L4sjCoRR<=N#88k_L4sjCo_M#$OR;
RRRRRRRRRNRR8k8#Ls4_CRo4<N=R8k8#Ls4_C_o4#O$M;R
RRRRRRRRRRkRF0sj_C<oR=kRF0sj_C#o_$;MO
RRRRRRRRRRRR0Fk4C_so=R<R0Fk4C_so$_#M
O;RRRRRRRRRRRRF_k0bosCRR<=F_k0bosC_M#$OR;
RRRRRRRRRHRRMbN_sRCo<H=RMbN_s_Co#O$M;R
RRRRRRRRRRkRF0C_so=R<R0Fk_osC_M#$OR;
RRRRRCRRMR8
RCRRM
8
RRRR/D/O	C,O,#sCCl0RkRG
R/RR/)qj Rt
RNRRD$IN#@R@5iBp2R
RRCRLo
HMRRRRRRRRH5VRq j)tp_Bi=R=Rp"Bi2j"
RRRRRRRRRRRR_qjBRpi=pRBi9rj;R
RRRRRRDRC#HCRVqR5jt) _iBpRR=="iBp4
"2RRRRRRRRRRRRqBj_p=iRRiBpr;49
RRRR8CM
R
RRDRNI#N$R5@@B
 2RRRRLHCoMR
RRRRRRVRHRj5q)_ tB= R=BR" 2j"
RRRRRRRRRRRR_qjB= RRrB j
9;RRRRRRRRCCD#RRHV5)qj Bt_ =R=R "B4
"2RRRRRRRRRRRRqBj_ RR=B4 r9R;
RCRRM
8
RRRRNNDI$@#R@ 5)12 a
RRRRoLCHRM
RRRRRHRRVqR5jt) _1)  =aR=)R" a1 j
"2RRRRRRRRRRRRq)j_ a1 R)=R a1 r;j9
RRRRRRRR#CDCVRHRj5q)_ t)  1a=R=R ")14 a"R2
RRRRRRRRRqRRj _)1R a= R)1r a4
9;RRRRC
M8
RRRRq//4t) 
RRRRINDNR$#@B@5p
i2RRRRLHCoMR
RRRRRRVRHR45q)_ tBRpi="=RBjpi"R2
RRRRRRRRRqRR4p_BiRR=Brpij
9;RRRRRRRRCCD#RRHV5)q4 Bt_p=iR=BR"p"i42R
RRRRRRRRRR4Rq_iBpRB=Rp4ir9R;
RCRRM
8
RRRRNNDI$@#R@ 5B2R
RRCRLo
HMRRRRRRRRH5VRq 4)t _BRR=="jB "R2
RRRRRRRRRqRR4 _BRB=R 9rj;R
RRRRRRDRC#HCRVqR54t) _RB ="=RB" 42R
RRRRRRRRRR4Rq_RB = RBr;49
RRRR8CM
R
RRDRNI#N$R5@@)  1aR2
RLRRCMoH
RRRRRRRRRHV5)q4 )t_ a1 RR=="1)  "aj2R
RRRRRRRRRR4Rq_1)  =aRR1)  jar9R;
RRRRRCRRDR#CH5VRq 4)t _)1R a="=R)  1a24"
RRRRRRRRRRRR_q4)  1aRR=)  1a9r4;R
RRMRC8R

R/RR/)Aj Rt
RNRRD$IN#@R@5iBp2R
RRCRLo
HMRRRRRRRRH5VRA j)tp_Bi=R=Rp"Bi2j"
RRRRRRRRRRRR_AjBRpi=pRBi9rj;R
RRRRRRDRC#HCRVAR5jt) _iBpRR=="iBp4
"2RRRRRRRRRRRRABj_p=iRRiBpr;49
RRRR8CM
R
RRDRNI#N$R5@@B
 2RRRRLHCoMR
RRRRRRVRHRj5A)_ tB= R=BR" 2j"
RRRRRRRRRRRR_AjB= RRrB j
9;RRRRRRRRCCD#RRHV5)Aj Bt_ =R=R "B4
"2RRRRRRRRRRRRABj_ RR=B4 r9R;
RCRRM
8
RRRRNNDI$@#R@ 5)12 a
RRRRoLCHRM
RRRRRHRRVAR5jt) _1)  =aR=)R" a1 j
"2RRRRRRRRRRRRA)j_ a1 R)=R a1 r;j9
RRRRRRRR#CDCVRHRj5A)_ t)  1a=R=R ")14 a"R2
RRRRRRRRRARRj _)1R a= R)1r a4
9;RRRRC
M8
RRRRA//4t) 
RRRRINDNR$#@B@5p
i2RRRRLHCoMR
RRRRRRVRHR45A)_ tBRpi="=RBjpi"R2
RRRRRRRRRARR4p_BiRR=Brpij
9;RRRRRRRRCCD#RRHV5)A4 Bt_p=iR=BR"p"i42R
RRRRRRRRRR4RA_iBpRB=Rp4ir9R;
RCRRM
8
RRRRNNDI$@#R@ 5B2R
RRCRLo
HMRRRRRRRRH5VRA 4)t _BRR=="jB "R2
RRRRRRRRRARR4 _BRB=R 9rj;R
RRRRRRDRC#HCRVAR54t) _RB ="=RB" 42R
RRRRRRRRRR4RA_RB = RBr;49
RRRR8CM
R
RRDRNI#N$R5@@)  1aR2
RLRRCMoH
RRRRRRRRRHV5)A4 )t_ a1 RR=="1)  "aj2R
RRRRRRRRRR4RA_1)  =aRR1)  jar9R;
RRRRRCRRDR#CH5VRA 4)t _)1R a="=R)  1a24"
RRRRRRRRRRRR_A4)  1aRR=)  1a9r4;R
RRMRC8R
RRRR
R/RR/ Q)tR
RRDRNI#N$R5@@B2pi
RRRRoLCHRM
RRRRRHRRVqR5BmBpqQ7_)_ tBRpi="=RBjpi"R2
RRRRRRRRRqRRBmBpqQ7_BRpi=pRBi9rj;R
RRRRRRDRC#HCRVqR5BmBpqQ7_)_ tBRpi="=RB4pi"R2
RRRRRRRRRqRRBmBpqQ7_BRpi=pRBi9r4;R
RRMRC8R

RNRRD$IN#@R@52B 
RRRRoLCHRM
RRRRRHRRVqR5BmBpqQ7_)_ tB= R=BR" 2j"
RRRRRRRRRRRRBqBp7mq_ QBRB=R 9rj;R
RRRRRRDRC#HCRVqR5BmBpqQ7_)_ tB= R=BR" 24"
RRRRRRRRRRRRBqBp7mq_ QBRB=R 9r4;R
RRMRC8R

RNRRD$IN#@R@51)  
a2RRRRLHCoMR
RRRRRRVRHRB5qBqpm7)_Q )t_ a1 RR=="1)  "aj2R
RRRRRRRRRRBRqBqpm7)_Q a1 R)=R a1 r;j9
RRRRRRRR#CDCVRHRB5qBqpm7)_Q )t_ a1 RR=="1)  "a42R
RRRRRRRRRRBRqBqpm7)_Q a1 R)=R a1 r;49
RRRR8CM
R
RRDRNI#N$R5@@B2pi
RRRRoLCHRM
RRRRRHRRVqR57z71AQj_)_ tBRpi="=RBjpi"R2
RRRRRRRRRqRR7z71AQj_BRpi=pRBi9rj;R
RRRRRRDRC#HCRVqR57z71AQj_)_ tBRpi="=RB4pi"R2
RRRRRRRRRqRR7z71AQj_BRpi=pRBi9r4;R
RRMRC8R

RNRRD$IN#@R@52B 
RRRRoLCHRM
RRRRRHRRVqR57z71AQj_)_ tB= R=BR" 2j"
RRRRRRRRRRRR7q71jzA_ QBRB=R 9rj;R
RRRRRRDRC#HCRVqR57z71AQj_)_ tB= R=BR" 24"
RRRRRRRRRRRR7q71jzA_ QBRB=R 9r4;R
RRMRC8R

RNRRD$IN#@R@51)  
a2RRRRLHCoMR
RRRRRRVRHR75q7A1zj)_Q )t_ a1 RR=="1)  "aj2R
RRRRRRRRRR7Rq7A1zj)_Q a1 R)=R a1 r;j9
RRRRRRRR#CDCVRHR75q7A1zj)_Q )t_ a1 RR=="1)  "a42R
RRRRRRRRRR7Rq7A1zj)_Q a1 R)=R a1 r;49
RRRR8CM
RRRRR
RRDRNI#N$R5@@B2pi
RRRRoLCHRM
RRRRRHRRVqR57z71AQ4_)_ tBRpi="=RBjpi"R2
RRRRRRRRRqRR7z71AQ4_BRpi=pRBi9rj;R
RRRRRRDRC#HCRVqR57z71AQ4_)_ tBRpi="=RB4pi"R2
RRRRRRRRRqRR7z71AQ4_BRpi=pRBi9r4;R
RRMRC8R

RNRRD$IN#@R@52B 
RRRRoLCHRM
RRRRRHRRVqR57z71AQ4_)_ tB= R=BR" 2j"
RRRRRRRRRRRR7q714zA_ QBRB=R 9rj;R
RRRRRRDRC#HCRVqR57z71AQ4_)_ tB= R=BR" 24"
RRRRRRRRRRRR7q714zA_ QBRB=R 9r4;R
RRMRC8R

RNRRD$IN#@R@51)  
a2RRRRLHCoMR
RRRRRRVRHR75q7A1z4)_Q )t_ a1 RR=="1)  "aj2R
RRRRRRRRRR7Rq7A1z4)_Q a1 R)=R a1 r;j9
RRRRRRRR#CDCVRHR75q7A1z4)_Q )t_ a1 RR=="1)  "a42R
RRRRRRRRRR7Rq7A1z4)_Q a1 R)=R a1 r;49
RRRR8CM
R
RR/R/ut) jR
RRDRNI#N$R5@@B2pi
RRRRoLCHRM
RRRRRHRRVuR5)j t_iBpRR=="iBpj
"2RRRRRRRRRRRRuBj_p=iRRiBpr;j9
RRRRRRRR#CDCVRHR)5u _tjBRpi="=RB4pi"R2
RRRRRRRRRuRRjp_BiRR=Brpi4
9;RRRRC
M8
RRRRINDNR$#@B@5 R2
RLRRCMoH
RRRRRRRRRHV5 u)tBj_ =R=R "Bj
"2RRRRRRRRRRRRuBj_ RR=Bj r9R;
RRRRRCRRDR#CH5VRut) j _BRR=="4B "R2
RRRRRRRRRuRRj _BRB=R 9r4;R
RRMRC8R

RNRRD$IN#@R@51)  
a2RRRRLHCoMR
RRRRRRVRHR)5u _tj)  1a=R=R ")1j a"R2
RRRRRRRRRuRRj _)1R a= R)1r aj
9;RRRRRRRRCCD#RRHV5 u)t)j_ a1 RR=="1)  "a42R
RRRRRRRRRRjRu_1)  =aRR1)  4ar9R;
RCRRM
8
RRRR/)/u 
t4RRRRNNDI$@#R@p5BiR2
RLRRCMoH
RRRRRRRRRHV5 u)tB4_p=iR=BR"p"ij2R
RRRRRRRRRR4Ru_iBpRB=Rpjir9R;
RRRRRCRRDR#CH5VRut) 4p_Bi=R=Rp"Bi24"
RRRRRRRRRRRR_u4BRpi=pRBi9r4;R
RRMRC8R

RNRRD$IN#@R@52B 
RRRRoLCHRM
RRRRRHRRVuR5)4 t_RB ="=RB" j2R
RRRRRRRRRR4Ru_RB = RBr;j9
RRRRRRRR#CDCVRHR)5u _t4B= R=BR" 24"
RRRRRRRRRRRR_u4B= RRrB 4
9;RRRRC
M8
RRRRINDNR$#@)@5 a1 2R
RRCRLo
HMRRRRRRRRH5VRut) 4 _)1R a="=R)  1a2j"
RRRRRRRRRRRR_u4)  1aRR=)  1a9rj;R
RRRRRRDRC#HCRVuR5)4 t_1)  =aR=)R" a1 4
"2RRRRRRRRRRRRu)4_ a1 R)=R a1 r;49
RRRR8CM
R
RR/R/ut) 
RRRRINDNR$#@B@5p
i2RRRRLHCoMR
RRRRRRVRHRB5qBqpm7)_u Bt_p=iR=BR"p"ij2R
RRRRRRRRRRBRqBqpm7B_up=iRRiBpr;j9
RRRRRRRR#CDCVRHRB5qBqpm7)_u Bt_p=iR=BR"p"i42R
RRRRRRRRRRBRqBqpm7B_up=iRRiBpr;49
RRRR8CM
R
RRDRNI#N$R5@@B
 2RRRRLHCoMR
RRRRRRVRHRB5qBqpm7)_u Bt_ =R=R "Bj
"2RRRRRRRRRRRRqpBBm_q7uRB = RBr;j9
RRRRRRRR#CDCVRHRB5qBqpm7)_u Bt_ =R=R "B4
"2RRRRRRRRRRRRqpBBm_q7uRB = RBr;49
RRRR8CM
R
RRDRNI#N$R5@@)  1aR2
RLRRCMoH
RRRRRRRRRHV5BqBp7mq_ u)t _)1R a="=R)  1a2j"
RRRRRRRRRRRRBqBp7mq_ u)1R a= R)1r aj
9;RRRRRRRRCCD#RRHV5BqBp7mq_ u)t _)1R a="=R)  1a24"
RRRRRRRRRRRRBqBp7mq_ u)1R a= R)1r a4
9;RRRRC
M8
RRRRINDNR$#@B@5p
i2RRRRLHCoMR
RRRRRRVRHR75q7A1zj)_u Bt_p=iR=BR"p"ij2R
RRRRRRRRRR7Rq7A1zjB_up=iRRiBpr;j9
RRRRRRRR#CDCVRHR75q7A1zj)_u Bt_p=iR=BR"p"i42R
RRRRRRRRRR7Rq7A1zjB_up=iRRiBpr;49
RRRR8CM
R
RRDRNI#N$R5@@B
 2RRRRLHCoMR
RRRRRRVRHR75q7A1zj)_u Bt_ =R=R "Bj
"2RRRRRRRRRRRRq177z_AjuRB = RBr;j9
RRRRRRRR#CDCVRHR75q7A1zj)_u Bt_ =R=R "B4
"2RRRRRRRRRRRRq177z_AjuRB = RBr;49
RRRR8CM
R
RRDRNI#N$R5@@)  1aR2
RLRRCMoH
RRRRRRRRRHV57q71jzA_ u)t _)1R a="=R)  1a2j"
RRRRRRRRRRRR7q71jzA_ u)1R a= R)1r aj
9;RRRRRRRRCCD#RRHV57q71jzA_ u)t _)1R a="=R)  1a24"
RRRRRRRRRRRR7q71jzA_ u)1R a= R)1r a4
9;RRRRC
M8
RRRRINDNR$#@B@5p
i2RRRRLHCoMR
RRRRRRVRHR75q7A1z4)_u Bt_p=iR=BR"p"ij2R
RRRRRRRRRR7Rq7A1z4B_up=iRRiBpr;j9
RRRRRRRR#CDCVRHR75q7A1z4)_u Bt_p=iR=BR"p"i42R
RRRRRRRRRR7Rq7A1z4B_up=iRRiBpr;49
RRRR8CM
R
RRDRNI#N$R5@@B
 2RRRRLHCoMR
RRRRRRVRHR75q7A1z4)_u Bt_ =R=R "Bj
"2RRRRRRRRRRRRq177z_A4uRB = RBr;j9
RRRRRRRR#CDCVRHR75q7A1z4)_u Bt_ =R=R "B4
"2RRRRRRRRRRRRq177z_A4uRB = RBr;49
RRRR8CM
R
RRDRNI#N$R5@@)  1aR2
RLRRCMoH
RRRRRRRRRHV57q714zA_ u)t _)1R a="=R)  1a2j"
RRRRRRRRRRRR7q714zA_ u)1R a= R)1r aj
9;RRRRRRRRCCD#RRHV57q714zA_ u)t _)1R a="=R)  1a24"
RRRRRRRRRRRR7q714zA_ u)1R a= R)1r a4
9;RRRRC
M8
RRRRm//)
 tRRRRNNDI$@#R@p5BiR2
RLRRCMoH
RRRRRRRRRHV5 m)tp_Bi=R=Rp"Bi2j"
RRRRRRRRRRRRBm_p=iRRiBpr;j9
RRRRRRRR#CDCVRHR)5m Bt_p=iR=BR"p"i42R
RRRRRRRRRR_RmBRpi=pRBi9r4;R
RRMRC8R

RNRRD$IN#@R@52B 
RRRRoLCHRM
RRRRRHRRVmR5)_ tB= R=BR" 2j"
RRRRRRRRRRRRBm_ RR=Bj r9R;
RRRRRCRRDR#CH5VRmt) _RB ="=RB" 42R
RRRRRRRRRR_RmB= RRrB 4
9;RRRRC
M8
RRRRINDNR$#@)@5 a1 2R
RRCRLo
HMRRRRRRRRH5VRmt) _1)  =aR=)R" a1 j
"2RRRRRRRRRRRRm _)1R a= R)1r aj
9;RRRRRRRRCCD#RRHV5 m)t _)1R a="=R)  1a24"
RRRRRRRRRRRR)m_ a1 R)=R a1 r;49
RRRR8CM
R
RR/R/RRHMs
CoRRRRNNDI$@#R@F5b#oC8CjRq_iBpRRFsbCF#8RoCq)j_ a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRHRRM_Njs_CoNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5_qj)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHMjC_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVqR5j _BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRHjMN_osC_$N#M<OR=jRq;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oR_qjBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHNsj_C#o_$RMO<j=R;RR
RRRRRCRRMC8RDR#CH5VRq)j_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRHjMN_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5_qjB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHNsj_C#o_$RMO<q=RjR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8C4Rq_iBpRRFsbCF#8RoCq)4_ a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRHRRM_N4s_CoNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5_q4)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHM4C_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVqR54 _BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH4MN_osC_$N#M<OR=4Rq;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oR_q4BRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHNs4_C#o_$RMO<j=R;RR
RRRRRCRRMC8RDR#CH5VRq)4_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH4MN_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5_q4B= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHNs4_C#o_$RMO<q=R4R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@j5qRRFsHjMN_osC2R
RRCRLo
HMRRRRRRRRH5VRq j)tp_Bi=R=RY"Au1q1"R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHMjRR=q
j;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRRHRRMRNj=MRHNsj_C
o;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@q@54sRFRNHM4C_soR2
RLRRCMoH
RRRRRRRRRHV5)q4 Bt_p=iR=AR"Y1uq1
"2RRRRRRRRLHCoMR
RRRRRRRRRRMRHN=4RR;q4
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRH4MNRH=RM_N4s;Co
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCABj_pFiRsFRb#oC8CjRA_1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRLHMjC_so#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRVAR5j _)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_Ljs_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5_AjB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHLsj_CNo_#O$MRR<=A
j;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoACRjp_BisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRHjML_osC_M#$O=R<RRj;
RRRRRRRR8CMR#CDCVRHRj5A_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHLsj_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVAR5j _BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRHjML_osC_M#$O=R<R;Aj
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCAB4_pFiRsFRb#oC8C4RA_1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRLHM4C_so#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRVAR54 _)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_L4s_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5_A4B= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHLs4_CNo_#O$MRR<=A
4;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoACR4p_BisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRH4ML_osC_M#$O=R<RRj;
RRRRRRRR8CMR#CDCVRHR45A_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHLs4_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVAR54 _BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH4ML_osC_M#$O=R<R;A4
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@AFjRsMRHLsj_C
o2RRRRLHCoMR
RRRRRRVRHRj5A)_ tBRpi="=RAqYu121"
RRRRRRRRoLCHRM
RRRRRRRRRHRRMRLj=jRA;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRRLHMjRR=HjML_osC;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5RA4FHsRM_L4s2Co
RRRRoLCHRM
RRRRRHRRVAR54t) _iBpRR=="uAYq"112R
RRRRRRCRLo
HMRRRRRRRRRRRRH4MLRA=R4R;
RRRRRCRRMC8RD
#CRRRRRRRRLHCoMR
RRRRRRRRRRMRHL=4RRLHM4C_soR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CBRqBqpm7B_QpFiRsFRb#oC8CBRqBqpm7)_Q a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRNRROFODN_8js_CoNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5BqBp7mq_ Q)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRROFODN_8js_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5BqBp7mq_ QBRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRNDOOFjN8_osC_$N#M<OR=BRqBqpm7R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CBRqBqpm7B_QpFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRONOD8FNjC_so$_#M<OR=;RjRR
RRRRRRMRC8DRC#HCRVqR5BmBpqQ7_)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FNjC_so$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHRB5qBqpm7B_Q =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FNjC_so$_#M<OR=BRqBqpm7R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@B5qBqpm7sRFRONOD8FNjC_soR2
RLRRCMoH
RRRRRRRRRHV5BqBp7mq_ Q)tp_Bi=R=RY"Au1q1"R2
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FN_<jR=BRqBqpm7R;
RRRRRCRRMC8RD
#CRRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8R_j<N=ROFODN_8js;Co
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCqpBBm_q7uiBpRRFsbCF#8RoCqpBBm_q7u1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRONOD8FN4C_so#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRVqR5BmBpqu7_)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FN4C_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVqR5BmBpqu7_B= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8s4_CNo_#O$MRR<=NDOOF_N8jR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CBRqBqpm7B_upFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRONOD8FN4C_so$_#M<OR=;RjRR
RRRRRRMRC8DRC#HCRVqR5BmBpqu7_)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FN4C_so$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHRB5qBqpm7B_u =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FN4C_so$_#M<OR=ORNONDF8;_j
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@NDOOF_N8jsRFRONOD8FN4C_soR2
RLRRCMoH
RRRRRRRRRHV5BqBp7mq_ u)tp_Bi=R=RY"Au1q1"R2
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FN_<4R=ORNONDF8;_j
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRNDOOF_N84=R<RONOD8FN4C_soR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8C7Rq7A1zjB_QpFiRsFRb#oC8C7Rq7A1zj)_Q a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRNRR8k8#Lsj_C_ojNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV57q71jzA_ Q)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#Lsj_C_ojNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV57q71jzA_ QBRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRN#88k_LjsjCo_$N#M<OR=7Rq7A1zr;j9
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCq177z_AjQiBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRNRR8k8#Lsj_C_oj#O$MRR<=j
;RRRRRRRRRCRM8CCD#RRHV57q71jzA_ Q)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#Lsj_C_oj#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRq177z_AjQRB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#Lsj_C_oj#O$MRR<=q177zjAr9R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@75q7A1zrRj9FNsR8k8#Lsj_C2oj
RRRRoLCHRM
RRRRRHRRVqR57z71AQj_)_ tBRpi="=RAqYu121"
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#Ljj_RR<=q177zjAr9R;
RRRRRCRRMC8RD
#CRRRRRRRRLHCoMR
RRRRRRRRRR8RN8L#kjR_j<N=R8k8#Lsj_C;oj
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCq177z_AjuiBpRRFsbCF#8RoCq177z_Aju1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR8N8#jkL_osC4#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRVqR57z71Auj_)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR8N8#jkL_osC4#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVqR57z71Auj_B= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRR8RN8L#kjC_soN4_#O$MRR<=N#88k_LjjR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8C7Rq7A1zjB_upFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR8N8#jkL_osC4$_#M<OR=;RjRR
RRRRRRMRC8DRC#HCRVqR57z71Auj_)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR8N8#jkL_osC4$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR75q7A1zjB_u =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR8N8#jkL_osC4$_#M<OR=8RN8L#kj;_j
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@N#88k_LjjsRFR8N8#jkL_osC4R2
RLRRCMoH
RRRRRRRRRHV57q71jzA_ u)tp_Bi=R=RY"Au1q1"R2
RRRRRLRRCMoH
RRRRRRRRRRRR8N8#jkL_<4R=8RN8L#kj;_j
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRN#88k_Lj4=R<R8N8#jkL_osC4R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8C7Rq7A1z4B_QpFiRsFRb#oC8C7Rq7A1z4)_Q a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRNRR8k8#Ls4_C_ojNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV57q714zA_ Q)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#Ls4_C_ojNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV57q714zA_ QBRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRN#88k_L4sjCo_$N#M<OR=7Rq7A1zr;49
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCq177z_A4QiBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRNRR8k8#Ls4_C_oj#O$MRR<=j
;RRRRRRRRRCRM8CCD#RRHV57q714zA_ Q)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#Ls4_C_oj#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRq177z_A4QRB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#Ls4_C_oj#O$MRR<=q177z4Ar9R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@75q7A1zrR49FNsR8k8#Ls4_C2oj
RRRRoLCHRM
RRRRRHRRVqR57z71AQ4_)_ tBRpi="=RAqYu121"
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#Lj4_RR<=q177z4Ar9R;
RRRRRCRRMC8RD
#CRRRRRRRRLHCoMR
RRRRRRRRRR8RN8L#k4R_j<N=R8k8#Ls4_C;oj
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCq177z_A4uiBpRRFsbCF#8RoCq177z_A4u1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR8N8#4kL_osC4#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRVqR57z71Au4_)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR8N8#4kL_osC4#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVqR57z71Au4_B= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRR8RN8L#k4C_soN4_#O$MRR<=N#88k_L4jR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8C7Rq7A1z4B_upFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR8N8#4kL_osC4$_#M<OR=;RjRR
RRRRRRMRC8DRC#HCRVqR57z71Au4_)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR8N8#4kL_osC4$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR75q7A1z4B_u =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR8N8#4kL_osC4$_#M<OR=8RN8L#k4;_j
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@N#88k_L4jsRFR8N8#4kL_osC4R2
RLRRCMoH
RRRRRRRRRHV57q714zA_ u)tp_Bi=R=RY"Au1q1"R2
RRRRRLRRCMoH
RRRRRRRRRRRR8N8#4kL_<4R=8RN8L#k4;_j
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRN#88k_L44=R<R8N8#4kL_osC4R;
RRRRRCRRMR8
RCRRM
8
RRRRNH##oNMRjdr.:Rj9={R{4H.{MrNj4}49}M,HN4jr49:j}R;
RNRR#o#HMjRLr:.dj=9RR4{{.M{HL4jr4}9},LHMj4r4:}j9;R
RR#RN#MHoRrN4.jd:9RR={.{4{NHM44r49,}}H4MNr:44j;9}
RRRR#N#HRoML.4rd9:jR{=R{{4.H4MLr944}H},MrL44j4:9
};
RRRR#N#HRoMl0kD_0FkjRR=5j!NRR||!2Lj?RRj:jRNRL*Rj
R;RRRRNH##olMRk_D0F4k0R5=R!RN4|!|RL?42R:jRRRN4*4RLR
;
RRRR/b/RHDbCHRMCs
CoRRRRNNDI$@#R@F5b#oC8CjRu_iBpRRFsbCF#8RoCu)j_ a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRFRRk_0js_CoNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5_uj)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0FkjC_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVuR5j _BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRFjk0_osC_$N#M<OR=kRlDF0_k;0j
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCuBj_pFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR0FkjC_so$_#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHRj5u_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0sj_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVuR5j _BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRFjk0_osC_M#$O=R<RDlk0k_F0
j;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CouCR4p_BisRFR#bFCC8oR_u4)  1asRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRF4k0_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR45u_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0s4_CNo_#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRuB4_ =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0Fk4C_so#_N$RMO<l=Rk_D0F4k0;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oR_u4BRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRkRF0s4_C#o_$RMO<j=R;R
RRRRRRMRC8DRC#HCRVuR54 _)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRk_04s_Co#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRuB4_ =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0Fk4C_so$_#M<OR=kRlDF0_k;04
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCmp_BisRFR#bFCC8oR)m_ a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRFRRkb0_s_CoNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5)m_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRF_k0bosC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5mB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0s_bCNo_#O$MRR<=8k_F0R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8C_RmBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRkRF0s_bC#o_$RMO<j=R;R
RRRRRRMRC8DRC#HCRVmR5_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0s_bC#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVmR5_RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRkb0_s_Co#O$MRR<=8k_F0R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@k5lDF0_kR0jFFsRk_0js2Co
RRRRoLCHRM
RRRRRHRRVuR5)j t_iBpRR=="uAYq"112R
RRRRRRCRLo
HMRRRRRRRRRRRRFjk0Rl=Rk_D0Fjk0;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRR0FkjRR=Fjk0_osC;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5Dlk0k_F0F4RskRF0s4_C
o2RRRRLHCoMR
RRRRRRVRHR)5u _t4BRpi="=RAqYu121"
RRRRRRRRoLCHRM
RRRRRRRRRFRRkR04=kRlDF0_k;04
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRF4k0RF=Rk_04s;Co
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@8k_F0sRFR0Fk_CbsoR2
RLRRCMoH
RRRRRRRRRHV5_wAut) RR==4j'L2R
RRRRRRCRLo
HMRRRRRRRRRRRR80Fk_osCR8=R_0Fk;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRRk8F0C_soRR=F_k0bosC;R
RRRRRRMRC8R
RRMRC8R

RNRR#o#HM_RlFjk0R{=R{{d.Fjk0r9.d}F},kr0j.jd:9
};RRRRNH##olMR_0Fk4RR={.{d{0Fk4dr.9,}}F4k0r:.dj;9}
R
RR#RN#MHoRONO_NDF8RR=5ONOD8FN_R42?FR8ks0_C:oRR u)_qpm7R;
RNRR#o#HM_R8OHN#R5=RBQq1_R h="=Ra )z"?2RR1BqQRR:6Ln'j
;
RRRRNNDI$@#R@O5NOF_DNF8Rs_RlFjk0RRFslk_F0F4Rs_R8OHN#RRFsN#88k_Lj4sRFR8N8#4kL_
42RRRRLHCoMR
RRRRRRVRH58N8#jkL_=4R='R4L&jR&8RN8L#k4R_4=4=R'2LjRoLCHRM
RRRRRRRRRNRRDFk_k=0RRONO_NDF8RR+lk_F0+jRRFl_kR04+_R8OHN#;R
RRRRRRMRC8DRC#HCRV85N8L#kjR_4=4=R'RLj&N&R8k8#L44_RR==44'L2CRLo
HMRRRRRRRRRRRRN_DkFRk0=ORNOF_DN+8RRFl_kR0j-_RlF4k0R8+R_#ONHR;RRRRRRRR
RRRRRCRRMC8RDR#CHNV58k8#L4j_RR==44'LRR&&N#88k_L44=R=RL4'jL2RCMoH
RRRRRRRRRRRRkND_0FkRN=RODO_FRN8-_RlFjk0Rl+R_0Fk4RR+8N_O#RH;RRRRR
RRRRRRRRRRCRM8CCD#R5HVN#88k_Lj4=R=RL4'4&R&R8N8#4kL_=4R='R4LR42LHCoMR
RRRRRRRRRRDRNkk_F0RR=N_OOD8FNRl-R_0FkjRR-lk_F0+4RRO8_N;#HRRRRRRRR
RRRRRRRR8CM
RRRR8CM
R
RR/R/R0FkbRk0s
CoRRRRNNDI$@#R@F5b#oC8C_RmBRpiFbsRF8#ComCR_1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR0Fk_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR_5m)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0Fk_osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5mB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0C_so#_N$RMO<N=RDFk_k
0;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#ComCR_iBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRFRRks0_C#o_$RMO<j=R;R
RRRRRRMRC8DRC#HCRVmR5_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0C_so$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5mB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0C_so$_#M<OR=DRNkk_F0R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@D5Nkk_F0sRFR0Fk_osC2R
RRCRLo
HMRRRRRRRRH5VRmt) _iBpRR=="uAYq"112R
RRRRRRCRLo
HMRRRRRRRRRRRR8k_F0RR=N_DkF;k0
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRR8k_F0RR=F_k0s;Co
RRRRRRRR8CM
RRRR8CM
R
RR#RN#MHoRz7maRR=8k_F06r6:;j9
RRRR#N#HRoMBmq1R8=R_0Fkr:66j
9;
8CMlkF8D
C
/1/7u_6n.4(XUF
l8CkDRu716.n_(UX4Rm57zRa,Bmq1,mR1qq,R,,RARRB,1,QqR1BqQq,R1, pRBqBp7mq,7Rq7A1z,pRBiB,R ),R a1 2
;
bNNslCC0s)Rq Bt_p=iRRY"Au1q1"/;R/AR"Y1uq1"",Bjpi"B,"p"i4
sbNN0lCCqsR)_ tB= RR "BjR";/"/RB" j, "B4b"
NlsNCs0CR q)t _)1R a=)R" a1 jR";/)/" a1 jR","1)  "a4
N
bsCNl0RCsAt) _iBpR"=RAqYu1;1"RR//"uAYq"11,p"Bi,j""iBp4b"
NlsNCs0CR A)t _BR"=RB" j;/R/R "Bj"",B" 4
sbNN0lCCAsR)_ t)  1aRR="1)  "aj;/R/"1)  "aj,)R" a1 4
"
bNNslCC0s)RB Bt_p=iRRY"Au1q1"/;R/AR"Y1uq1"",Bjpi"B,"p"i4
sbNN0lCCBsR)_ tB= RR "BjR";/"/RB" j, "B4b"
NlsNCs0CR B)t _)1R a=)R" a1 jR";/)/" a1 jR","1)  "a4
N
bsCNl0RCsq177zQA_)_ tBRpi=AR"Y1uq1R";/"/RAqYu1,1""iBpj"",B4pi"N
bsCNl0RCsq177zQA_)_ tB= RR "BjR";/"/RB" j, "B4b"
NlsNCs0CR7q71_zAQt) _1)  =aRR ")1j a"/;R/ ")1j a"",R)  1a
4"
sbNN0lCCqsRBmBpqQ7_)_ tBRpi=AR"Y1uq1R";/"/RAqYu1,1""iBpj"",B4pi"N
bsCNl0RCsqpBBm_q7Qt) _RB =BR" ;j"RR//"jB "B," 
4"bNNslCC0sBRqBqpm7)_Q )t_ a1 R"=R)  1a;j"R"//)  1a,j"R ")14 a"b

NlsNCs0CR u)tp_BiRR="uAYq"11;/R/RY"Au1q1"B,"p"ij,p"Bi
4"bNNslCC0s)Ru Bt_ RR="jB "/;R/BR" ,j""4B "N
bsCNl0RCsut) _1)  =aRR ")1j a"/;R/ ")1j a"",R)  1a
4"
sbNN0lCCqsR7z71A)_u Bt_p=iRRY"Au1q1"/;R/AR"Y1uq1"",Bjpi"B,"p"i4
sbNN0lCCqsR7z71A)_u Bt_ RR="jB "/;R/BR" ,j""4B "N
bsCNl0RCsq177zuA_)_ t)  1aRR="1)  "aj;/R/"1)  "aj,)R" a1 4
"
bNNslCC0sBRqBqpm7)_u Bt_p=iRRY"Au1q1"/;R/AR"Y1uq1"",Bjpi"B,"p"i4
sbNN0lCCqsRBmBpqu7_)_ tB= RR "BjR";/"/RB" j, "B4b"
NlsNCs0CRBqBp7mq_ u)t _)1R a=)R" a1 jR";/)/" a1 jR","1)  "a4
N
bsCNl0RCswuA_)R t='R4LRj;/4/R',Lj"uAYq"11;L4'4 ,"hpqA R"RRRRR/C/VCN8LON	RObORHDbCHRMCsHCo#s0C,l#NCDRO	C/O/#sCCN0R#)Rm bt
NlsNCs0CRq1m_ u)tRR=4j'L;4//',Lj"uAYq"11;L4'4 ,"hpqA R"RRRRRR#//FbNRHDbCHRMCsHCo#s0C,N,#lOCRDO	/CC/s#RC0Nq#R)
 t
sbNN0lCCmsR)_ tBRpi=AR"Y1uq1R";/"/RAqYu1,1""iBpj"",B4pi"N
bsCNl0RCsmt) _RB =BR" ;j"RR//"jB "B," 
4"bNNslCC0s)Rm )t_ a1 R"=R)  1a;j"R"//)  1a,j"R ")14 a"b

NlsNCs0CRpvza _)1_ av m7R"=R1BYh"/;/Rh1YB1,qY
hBbNNslCC0sqRB1 Q_hRR="pwq1; "/a/")"z ,q"wp"1 
sbNN0lCCusR)p _mRq7=nR6';8j
sbNN0lCCusRq_77 =hRRq"wp"1 ;"//a )z"w,"q p1"N
bsCNl0RCsu7q7_7q71RzA='R4L/j;/L4'jN:R8R8;44'L:kR#LF

kk0b06Rr69:jRz7maB,Rq;1m
0FkbRk0r:.nj19Rm
q;HkMb0rRR.jn:9,RqRq1Q;M
HbRk0R(r4:Rj9AH;
M0bkR.Rr69:jR
B;HkMb0rRR6j6:9qRB1
Q;HkMb0qRRBmBpqR7,qp1 ;M
HbRk0R7q71;zA
bHMkR0Rrj4:9pRBiB,R ),R a1 ;s

CqoR_iBp,Bq_ _,q)  1a_,AB,piA _B,)A_ a1 ,BB_pBi,_,B B _)1, aqpBBm_q7QiBp,BqBp7mq_ QB,BqBp7mq_ Q)1, aq177zQA_B,piq177zQA_Bq ,7z71A)_Q a1 ,Bu_pui,_,B u _)1, aqpBBm_q7uiBp,BqBp7mq_ uB,BqBp7mq_ u)1, aq177zuA_B,piq177zuA_Bq ,7z71A)_u a1 ,Bm_pmi,_,B m _)1; a
osCRnr.:Rj9H_MNs_CoNM#$OM,HNC_so$_#MHO,MHN,MsN_CNo,_O#s,HN_MM,HNs_bCNo_#O$M,NHM_Cbso$_#MHO,MbN_s,Co1;mq
sIHC.Rrn9:jRNHM_0CG,OHM_0CG;C
so4Rr(9:jRLHM_osC_$N#MHO,MsL_C#o_$,MOH,MLH_MLs;Co
osCR6r.:Rj9H_MOs_CoNM#$OM,HOC_so$_#MHO,MHO,MsO_C
o;sRCoRONOD8FNjC_so#_N$,MONDOOFjN8_osC_M#$OO,NONDF8,_jNDOOFjN8_osC,ONOD8FN4C_so#_N$,MONDOOF4N8_osC_M#$OO,NONDF8,_4NDOOF4N8_osC;C
so8RN8L#k_osCj#_N$,MON#88ksL_C_oj#O$M,8N8#_kLsjCo,8N8#_kLj8,N8L#k_osC4#_N$,MON#88ksL_C_o4#O$M,8N8#_kLs4Co,8N8#_kL4I;
HRsCr:ccjN9Rjj,L,Dlk0k_F0s;
CroRcjc:9kRF0sj_CNo_#O$M,0FkjC_so$_#MFO,k,0jFjk0_osC;C
so6Rrn9:jRF8_kF0,kb0_s_CoNM#$Ok,F0s_bC#o_$,MOF_k0bosC,k8F0C_soD,Nkk_F0I;
HRsCr:66jl9R_0FkjO,NOF_DN88,_#ONHs;
CroR6jn:9kRF0C_so#_N$,MOF_k0s_Co#O$M,0Fk_osC;/

/sIHCsRo#R0M=1Rt)13t)
m;#bkbDR$jt;h7Rk
#b$bD4BReB
;RRsIHCsRo#;0MRR//=1Rt)13t)
m;R#N#HRoMo0s#MRR=e;BB
D
NI#N$R5@@H_MNs_CoNM#$OsRFRNHM_osC_M#$OsRFRLHM_osC_$N#MFORsMRHLC_so$_#MFORsMRHOC_so#_N$RMOFHsRMsO_C#o_$RMOFNsROFODN_8js_CoNM#$OsRFRONOD8FNjC_so$_#MFORsORNONDF8s4_CNo_#O$MRRFsNDOOF4N8_osC_M#$OsRFR8N8#_kLsjCo_$N#MFORs8RN8L#k_osCj$_#MFORs8RN8L#k_osC4#_N$RMOFNsR8k8#LC_so#4_$RMOFFsRk_0js_CoNM#$OsRFR0FkjC_so$_#MFORskRF0s_bCNo_#O$MRRFsF_k0bosC_M#$OsRFRNHM_Cbso$_#MFORsMRHNs_bCNo_#O$MRRFsF_k0s_Co#O$MRRFsF_k0s_CoNM#$OR2
RLRRCMoH
RRRRRRRRRHV5pvza _)1_ av m7RR=="Yq1h2B"
RRRRRRRRoLCHRM
RRRRRRRRRHRRMsN_C<oR=MRHNC_so#_N$;MO
RRRRRRRRRRRRLHM_osCRR<=H_MLs_CoNM#$OR;
RRRRRRRRRHRRMsO_C<oR=MRHOC_so#_N$;MO
RRRRRRRRRRRRONOD8FNjC_so=R<RONOD8FNjC_so#_N$;MO
RRRRRRRRRRRRONOD8FN4C_so=R<RONOD8FN4C_so#_N$;MO
RRRRRRRRRRRR8N8#_kLsjCoRR<=N#88ksL_C_ojNM#$OR;
RRRRRRRRRNRR8k8#LC_so<4R=8RN8L#k_osC4#_N$;MO
RRRRRRRRRRRR0FkjC_so=R<R0FkjC_so#_N$;MO
RRRRRRRRRRRR0Fk_Cbso=R<R0Fk_Cbso#_N$;MO
RRRRRRRRRRRRNHM_Cbso=R<RNHM_Cbso#_N$;MO
RRRRRRRRRRRR0Fk_osCRR<=F_k0s_CoNM#$OR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRvazp_1)  va_mR7 ="=R1BYh"R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHM_osCRR<=H_MNs_Co#O$M;R
RRRRRRRRRRMRHLC_so=R<RLHM_osC_M#$OR;
RRRRRRRRRHRRMsO_C<oR=MRHOC_so$_#M
O;RRRRRRRRRRRRNDOOFjN8_osCRR<=NDOOFjN8_osC_M#$OR;
RRRRRRRRRNRROFODN_84sRCo<N=ROFODN_84s_Co#O$M;R
RRRRRRRRRR8RN8L#k_osCj=R<R8N8#_kLsjCo_M#$OR;
RRRRRRRRRNRR8k8#LC_so<4R=8RN8L#k_osC4$_#M
O;RRRRRRRRRRRRFjk0_osCRR<=Fjk0_osC_M#$OR;
RRRRRRRRRFRRkb0_sRCo<F=Rkb0_s_Co#O$M;R
RRRRRRRRRRMRHNs_bC<oR=MRHNs_bC#o_$;MO
RRRRRRRRRRRR0Fk_osCRR<=F_k0s_Co#O$M;R

RRRRRCRRMR8
RCRRM
8
RRRR/D/O	C,O,#sCCl0RkRG
R/RR/ q)tR
RRDRNI#N$R5@@B2pi
RRRRoLCHRM
RRRRRHRRVqR5)_ tBRpi="=RBjpi"R2
RRRRRRRRRqRR_iBpRB=Rpjir9R;
RRRRRCRRDR#CH5VRqt) _iBpRR=="iBp4
"2RRRRRRRRRRRRqp_BiRR=Brpi4
9;RRRRC
M8
RRRRINDNR$#@B@5 R2
RLRRCMoH
RRRRRRRRRHV5 q)t _BRR=="jB "R2
RRRRRRRRRqRR_RB = RBr;j9
RRRRRRRR#CDCVRHR)5q Bt_ =R=R "B4
"2RRRRRRRRRRRRq _BRB=R 9r4;R
RRMRC8R

RNRRD$IN#@R@51)  
a2RRRRLHCoMR
RRRRRRVRHR)5q )t_ a1 RR=="1)  "aj2R
RRRRRRRRRR_Rq)  1aRR=)  1a9rj;R
RRRRRRDRC#HCRVqR5)_ t)  1a=R=R ")14 a"R2
RRRRRRRRRqRR_1)  =aRR1)  4ar9R;
RCRRM
8
RRRR/)/A Rt
RNRRD$IN#@R@5iBp2R
RRCRLo
HMRRRRRRRRH5VRAt) _iBpRR=="iBpj
"2RRRRRRRRRRRRAp_BiRR=Brpij
9;RRRRRRRRCCD#RRHV5 A)tp_Bi=R=Rp"Bi24"
RRRRRRRRRRRRBA_p=iRRiBpr;49
RRRR8CM
R
RRDRNI#N$R5@@B
 2RRRRLHCoMR
RRRRRRVRHR)5A Bt_ =R=R "Bj
"2RRRRRRRRRRRRA _BRB=R 9rj;R
RRRRRRDRC#HCRVAR5)_ tB= R=BR" 24"
RRRRRRRRRRRRBA_ RR=B4 r9R;
RCRRM
8
RRRRNNDI$@#R@ 5)12 a
RRRRoLCHRM
RRRRRHRRVAR5)_ t)  1a=R=R ")1j a"R2
RRRRRRRRRARR_1)  =aRR1)  jar9R;
RRRRRCRRDR#CH5VRAt) _1)  =aR=)R" a1 4
"2RRRRRRRRRRRRA _)1R a= R)1r a4
9;RRRRC
M8
RRRRB//)
 tRRRRNNDI$@#R@p5BiR2
RLRRCMoH
RRRRRRRRRHV5 B)tp_Bi=R=Rp"Bi2j"
RRRRRRRRRRRRBB_p=iRRiBpr;j9
RRRRRRRR#CDCVRHR)5B Bt_p=iR=BR"p"i42R
RRRRRRRRRR_RBBRpi=pRBi9r4;R
RRMRC8R

RNRRD$IN#@R@52B 
RRRRoLCHRM
RRRRRHRRVBR5)_ tB= R=BR" 2j"
RRRRRRRRRRRRBB_ RR=Bj r9R;
RRRRRCRRDR#CH5VRBt) _RB ="=RB" 42R
RRRRRRRRRR_RBB= RRrB 4
9;RRRRC
M8
RRRRINDNR$#@)@5 a1 2R
RRCRLo
HMRRRRRRRRH5VRBt) _1)  =aR=)R" a1 j
"2RRRRRRRRRRRRB _)1R a= R)1r aj
9;RRRRRRRRCCD#RRHV5 B)t _)1R a="=R)  1a24"
RRRRRRRRRRRR)B_ a1 R)=R a1 r;49
RRRR8CM
RRRRR
RR/R/Qt) 
RRRRINDNR$#@B@5p
i2RRRRLHCoMR
RRRRRRVRHRB5qBqpm7)_Q Bt_p=iR=BR"p"ij2R
RRRRRRRRRRBRqBqpm7B_Qp=iRRiBpr;j9
RRRRRRRR#CDCVRHRB5qBqpm7)_Q Bt_p=iR=BR"p"i42R
RRRRRRRRRRBRqBqpm7B_Qp=iRRiBpr;49
RRRR8CM
R
RRDRNI#N$R5@@B
 2RRRRLHCoMR
RRRRRRVRHRB5qBqpm7)_Q Bt_ =R=R "Bj
"2RRRRRRRRRRRRqpBBm_q7QRB = RBr;j9
RRRRRRRR#CDCVRHRB5qBqpm7)_Q Bt_ =R=R "B4
"2RRRRRRRRRRRRqpBBm_q7QRB = RBr;49
RRRR8CM
R
RRDRNI#N$R5@@)  1aR2
RLRRCMoH
RRRRRRRRRHV5BqBp7mq_ Q)t _)1R a="=R)  1a2j"
RRRRRRRRRRRRBqBp7mq_ Q)1R a= R)1r aj
9;RRRRRRRRCCD#RRHV5BqBp7mq_ Q)t _)1R a="=R)  1a24"
RRRRRRRRRRRRBqBp7mq_ Q)1R a= R)1r a4
9;RRRRC
M8
RRRRINDNR$#@B@5p
i2RRRRLHCoMR
RRRRRRVRHR75q7A1z_ Q)tp_Bi=R=Rp"Bi2j"
RRRRRRRRRRRR7q71_zAQiBpRB=Rpjir9R;
RRRRRCRRDR#CH5VRq177zQA_)_ tBRpi="=RB4pi"R2
RRRRRRRRRqRR7z71AB_Qp=iRRiBpr;49
RRRR8CM
R
RRDRNI#N$R5@@B
 2RRRRLHCoMR
RRRRRRVRHR75q7A1z_ Q)t _BRR=="jB "R2
RRRRRRRRRqRR7z71AB_Q RR=Bj r9R;
RRRRRCRRDR#CH5VRq177zQA_)_ tB= R=BR" 24"
RRRRRRRRRRRR7q71_zAQRB = RBr;49
RRRR8CM
R
RRDRNI#N$R5@@)  1aR2
RLRRCMoH
RRRRRRRRRHV57q71_zAQt) _1)  =aR=)R" a1 j
"2RRRRRRRRRRRRq177zQA_)  1aRR=)  1a9rj;R
RRRRRRDRC#HCRVqR57z71A)_Q )t_ a1 RR=="1)  "a42R
RRRRRRRRRR7Rq7A1z_ Q)1R a= R)1r a4
9;RRRRC
M8
RRRRu//)
 tRRRRNNDI$@#R@p5BiR2
RLRRCMoH
RRRRRRRRRHV5 u)tp_Bi=R=Rp"Bi2j"
RRRRRRRRRRRRBu_p=iRRiBpr;j9
RRRRRRRR#CDCVRHR)5u Bt_p=iR=BR"p"i42R
RRRRRRRRRR_RuBRpi=pRBi9r4;R
RRMRC8R

RNRRD$IN#@R@52B 
RRRRoLCHRM
RRRRRHRRVuR5)_ tB= R=BR" 2j"
RRRRRRRRRRRRBu_ RR=Bj r9R;
RRRRRCRRDR#CH5VRut) _RB ="=RB" 42R
RRRRRRRRRR_RuB= RRrB 4
9;RRRRC
M8
RRRRINDNR$#@)@5 a1 2R
RRCRLo
HMRRRRRRRRH5VRut) _1)  =aR=)R" a1 j
"2RRRRRRRRRRRRu _)1R a= R)1r aj
9;RRRRRRRRCCD#RRHV5 u)t _)1R a="=R)  1a24"
RRRRRRRRRRRR)u_ a1 R)=R a1 r;49
RRRR8CM
R
RRDRNI#N$R5@@B2pi
RRRRoLCHRM
RRRRRHRRVqR5BmBpqu7_)_ tBRpi="=RBjpi"R2
RRRRRRRRRqRRBmBpqu7_BRpi=pRBi9rj;R
RRRRRRDRC#HCRVqR5BmBpqu7_)_ tBRpi="=RB4pi"R2
RRRRRRRRRqRRBmBpqu7_BRpi=pRBi9r4;R
RRMRC8R

RNRRD$IN#@R@52B 
RRRRoLCHRM
RRRRRHRRVqR5BmBpqu7_)_ tB= R=BR" 2j"
RRRRRRRRRRRRBqBp7mq_ uBRB=R 9rj;R
RRRRRRDRC#HCRVqR5BmBpqu7_)_ tB= R=BR" 24"
RRRRRRRRRRRRBqBp7mq_ uBRB=R 9r4;R
RRMRC8R

RNRRD$IN#@R@51)  
a2RRRRLHCoMR
RRRRRRVRHRB5qBqpm7)_u )t_ a1 RR=="1)  "aj2R
RRRRRRRRRRBRqBqpm7)_u a1 R)=R a1 r;j9
RRRRRRRR#CDCVRHRB5qBqpm7)_u )t_ a1 RR=="1)  "a42R
RRRRRRRRRRBRqBqpm7)_u a1 R)=R a1 r;49
RRRR8CM
R
RRDRNI#N$R5@@B2pi
RRRRoLCHRM
RRRRRHRRVqR57z71A)_u Bt_p=iR=BR"p"ij2R
RRRRRRRRRR7Rq7A1z_puBiRR=Brpij
9;RRRRRRRRCCD#RRHV57q71_zAut) _iBpRR=="iBp4
"2RRRRRRRRRRRRq177zuA_BRpi=pRBi9r4;R
RRMRC8R

RNRRD$IN#@R@52B 
RRRRoLCHRM
RRRRRHRRVqR57z71A)_u Bt_ =R=R "Bj
"2RRRRRRRRRRRRq177zuA_B= RRrB j
9;RRRRRRRRCCD#RRHV57q71_zAut) _RB ="=RB" 42R
RRRRRRRRRR7Rq7A1z_ uBRB=R 9r4;R
RRMRC8R

RNRRD$IN#@R@51)  
a2RRRRLHCoMR
RRRRRRVRHR75q7A1z_ u)t _)1R a="=R)  1a2j"
RRRRRRRRRRRR7q71_zAu1)  =aRR1)  jar9R;
RRRRRCRRDR#CH5VRq177zuA_)_ t)  1a=R=R ")14 a"R2
RRRRRRRRRqRR7z71A)_u a1 R)=R a1 r;49
RRRR8CM
R
RR/R/mt) 
RRRRINDNR$#@B@5p
i2RRRRLHCoMR
RRRRRRVRHR)5m Bt_p=iR=BR"p"ij2R
RRRRRRRRRR_RmBRpi=pRBi9rj;R
RRRRRRDRC#HCRVmR5)_ tBRpi="=RB4pi"R2
RRRRRRRRRmRR_iBpRB=Rp4ir9R;
RCRRM
8
RRRRNNDI$@#R@ 5B2R
RRCRLo
HMRRRRRRRRH5VRmt) _RB ="=RB" j2R
RRRRRRRRRR_RmB= RRrB j
9;RRRRRRRRCCD#RRHV5 m)t _BRR=="4B "R2
RRRRRRRRRmRR_RB = RBr;49
RRRR8CM
R
RRDRNI#N$R5@@)  1aR2
RLRRCMoH
RRRRRRRRRHV5 m)t _)1R a="=R)  1a2j"
RRRRRRRRRRRR)m_ a1 R)=R a1 r;j9
RRRRRRRR#CDCVRHR)5m )t_ a1 RR=="1)  "a42R
RRRRRRRRRR_Rm)  1aRR=)  1a9r4;R
RRMRC8R

R/RR/7uq7sRFR0MF
RRRRINDNR$#@q@5RRFs1RQqFqsR12 p
RRRRoLCHRM
RRRRRHRRV15q =pR='R4L
j2RRRRRRRRLHCoMR
RRRRRRRRRR_RN#RsO=;Rq
RRRRRRRR8CMR#CDCCRLo
HMRRRRRRRRRRRRNs_#ORR=1;Qq
RRRRRRRR8CM
RRRR8CM
R
RR#RN#MHoRNHM_0CGR{=RHrMN.,69HrMN.j6:9
};RRRRNH##oHMRMCO_G=0RRM{HO6r.9M,HO6r.:}j9;R

RNRRD$IN#5@@H_MNCRG0FHsRMCO_GF0RsMRHNR2
RLRRCMoH
RRRRRRRR5HVu7q7_R h="=Ra )z"R2
RRRRRLRRCMoH
RRRRRRRRRRRR5HVu7q7_7q71RzA=4=R'2LjRoLCHRM
RRRRRRRRRRRRRNRR_RHM=MRHNG_C0RR+H_MOC;G0
RRRRRRRRRRRR8CMR#CDCCRLo
HMRRRRRRRRRRRRRRRRNM_HRH=RMCN_G-0RROHM_0CG;R
RRRRRRRRRRMRC8R
RRRRRRMRC8DRC#LCRCMoH
RRRRRRRRRRRRHN_MRR=H;MN
RRRRRRRR8CM
RRRR8CM
R
RR/R/RRHMs
CoRRRRNNDI$@#R@F5b#oC8C_RqBRpiFbsRF8#CoqCR_1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRNHM_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR_5q)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHM_osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5qB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHNC_so#_N$RMO<N=R_O#s;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRBq_pFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRNHM_osC_M#$O=R<RRj;
RRRRRRRR8CMR#CDCVRHR_5q)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHM_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5Bq_ =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHM_osC_M#$O=R<R#N_s
O;RRRRRRRRC
M8RRRRC
M8RRRR
RRRRINDNR$#@N@5_O#sRRFsH_MNs2Co
RRRRoLCHRM
RRRRRHRRVqR5)_ tBRpi="=RAqYu121"
RRRRRRRRoLCHRM
RRRRRRRRRHRRM=NRR#N_s
O;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRRHRRM=NRRNHM_osC;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRBA_pFiRsFRb#oC8C_RA)  1asRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRH_MLs_CoNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5)A_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH_MLs_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5BA_ =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRLHM_osC_$N#M<OR=;RA
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCAp_BisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRH_MLs_Co#O$MRR<=j
;RRRRRRRRRCRM8CCD#RRHV5)A_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH_MLs_Co#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRA _BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH_MLs_Co#O$MRR<=AR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8C_RBBRpiFbsRF8#CoBCR_1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRROHM_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR_5B)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRROHM_osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5BB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHOC_so#_N$RMO<B=R;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRBB_pFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRROHM_osC_M#$O=R<RRj;
RRRRRRRR8CMR#CDCVRHR_5B)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRROHM_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5BB_ =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRROHM_osC_M#$O=R<R
B;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@A@5RRFsH_MLs2Co
RRRRoLCHRM
RRRRRHRRVAR5)_ tBRpi="=RAqYu121"
RRRRRRRRoLCHRM
RRRRRRRRRHRRM=LRR
A;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRRHRRM=LRRLHM_osC;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5FBRsMRHOC_soR2
RLRRCMoH
RRRRRRRRRHV5 B)tp_Bi=R=RY"Au1q1"R2
RRRRRLRRCMoH
RRRRRRRRRRRROHMRB=R;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRROHMRH=RMsO_C
o;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoqCRBmBpqQ7_BRpiFbsRF8#CoqCRBmBpqQ7_)  1asRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRNDOOFjN8_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHRB5qBqpm7)_Q a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRNDOOFjN8_osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHRB5qBqpm7B_Q =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FNjC_so#_N$RMO<q=RBmBpq
7;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoqCRBmBpqQ7_BRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRORNONDF8sj_C#o_$RMO<j=R;RR
RRRRRCRRMC8RDR#CH5VRqpBBm_q7Q1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8sj_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVqR5BmBpqQ7_B= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8sj_C#o_$RMO<q=RBmBpq
7;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@q@5BmBpqF7RsORNONDF8sj_C
o2RRRRLHCoMR
RRRRRRVRHRB5qBqpm7)_Q Bt_p=iR=AR"Y1uq1
"2RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8R_j<q=RBmBpq
7;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRRNRROFODNj8_RR<=NDOOFjN8_osC;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRBqBp7mq_puBisRFR#bFCC8oRBqBp7mq_ u)1R aFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRORNONDF8s4_CNo_#O$MRR<=jR;
RRRRRCRRMC8RDR#CH5VRqpBBm_q7u1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8s4_CNo_#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRqpBBm_q7uRB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRROFODN_84s_CoNM#$O=R<RONOD8FN_
j;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoqCRBmBpqu7_BRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRORNONDF8s4_C#o_$RMO<j=R;RR
RRRRRCRRMC8RDR#CH5VRqpBBm_q7u1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8s4_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVqR5BmBpqu7_B= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8s4_C#o_$RMO<N=ROFODNj8_;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5ONOD8FN_FjRsORNONDF8s4_C
o2RRRRLHCoMR
RRRRRRVRHRB5qBqpm7)_u Bt_p=iR=AR"Y1uq1
"2RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8R_4<N=ROFODNj8_;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FN_<4R=ORNONDF8s4_C
o;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoqCR7z71AB_QpFiRsFRb#oC8C7Rq7A1z_ Q)1R aFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRR8RN8L#k_osCj#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRVqR57z71A)_Q a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRN#88ksL_C_ojNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV57q71_zAQRB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#LC_soNj_#O$MRR<=q177z
A;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoqCR7z71AB_QpFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR8N8#_kLsjCo_M#$O=R<RRj;
RRRRRRRR8CMR#CDCVRHR75q7A1z_ Q)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#LC_so#j_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVqR57z71AB_Q =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR8N8#_kLsjCo_M#$O=R<R7q71;zA
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@q177zFARs8RN8L#k_osCjR2
RLRRCMoH
RRRRRRRRRHV57q71_zAQt) _iBpRR=="uAYq"112R
RRRRRRCRLo
HMRRRRRRRRRRRRN#88kjL_RR<=q177z
A;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#LR_j<N=R8k8#LC_so
j;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoqCR7z71AB_upFiRsFRb#oC8C7Rq7A1z_ u)1R aFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRR8RN8L#k_osC4#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRVqR57z71A)_u a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRN#88ksL_C_o4NM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV57q71_zAuRB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#LC_soN4_#O$MRR<=N#88kjL_;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oR7q71_zAuiBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRNRR8k8#LC_so#4_$RMO<j=R;RR
RRRRRCRRMC8RDR#CH5VRq177zuA_)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR8N8#_kLs4Co_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV57q71_zAuRB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#LC_so#4_$RMO<N=R8k8#L;_j
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@N#88kjL_RRFsN#88ksL_C2o4
RRRRoLCHRM
RRRRRHRRVqR57z71A)_u Bt_p=iR=AR"Y1uq1
"2RRRRRRRRLHCoMR
RRRRRRRRRR8RN8L#k_<4R=8RN8L#k_
j;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRRNRR8k8#LR_4<N=R8k8#LC_so
4;RRRRRRRRC
M8RRRRC
M8
RRRR#N#HRoMNcjrc9:jR{=R{{4UNM_Hr9.n}N},_rHM.jn:9
};RRRRNH##oLMRjcrc:Rj9={R{.H({M4Lr(}9},LHMr:4(j;9}
R
RR#RN#MHoRDlk0k_F0RR=5j!NRR||!2Lj?RRj:jRNRL*Rj
R;
RRRRR//bCHbDCHMRosC
RRRRINDNR$#@b@5F8#CouCR_iBpRRFsbCF#8RoCu _)1R aFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRkRF0sj_CNo_#O$MRR<=jR;
RRRRRCRRMC8RDR#CH5VRu _)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRk_0js_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5Bu_ =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0FkjC_so#_N$RMO<l=Rk_D0F;k0
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCup_BisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRFjk0_osC_M#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5)u_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRFjk0_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5Bu_ =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0FkjC_so$_#M<OR=kRlDF0_k
0;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#ComCR_iBpRRFsbCF#8RoCm _)1R aFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRkRF0s_bCNo_#O$MRR<=jR;
RRRRRCRRMC8RDR#CH5VRm _)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRkb0_s_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5Bm_ =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0Fk_Cbso#_N$RMO<8=R_0Fk;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRBm_pFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR0Fk_Cbso$_#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR_5m)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0Fk_Cbso$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5mB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0s_bC#o_$RMO<8=R_0Fk;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5Dlk0k_F0sRFR0FkjC_soR2
RLRRCMoH
RRRRRRRRRHV5 u)tp_Bi=R=RY"Au1q1"R2
RRRRRLRRCMoH
RRRRRRRRRRRR0FkjRR=l0kD_0Fk;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRR0FkjRR=Fjk0_osC;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5F8_kF0RskRF0s_bC
o2RRRRLHCoMR
RRRRRRVRHRA5w_ u)t=R=RL4'jR2
RRRRRLRRCMoH
RRRRRRRRRRRRk8F0C_soRR=8k_F0R;
RRRRRCRRMC8RD
#CRRRRRRRRLHCoMR
RRRRRRRRRRFR8ks0_C=oRR0Fk_CbsoR;
RRRRRCRRMR8
RCRRM
8
RRRRNH##olMR_0FkjRR={4{4{0Fkjcrc9,}}Fjk0r:ccj;9}
R
RR#RN#MHoRONO_NDF8RR=5ONOD8FN_R42?FR8ks0_C:oRR u)_qpm7R;
RNRR#o#HM_R8OHN#R5=RBQq1_R h="=Ra )z"?2RR1BqQRR:6Ln'j
;
RRRRNNDI$@#R@O5NOF_DNF8Rs_RlFjk0RRFs8N_O#FHRs8RN8L#k_
42RRRRLHCoMR
RRRRRRVRH58N8#_kL4=R=RL4'jL2RCMoH
RRRRRRRRRRRRkND_0FkRR<=N_OOD8FNRl+R_0FkjRR+8N_O#
H;RRRRRRRRCRM8CCD#R5HVN#88k4L_RR==44'L2CRLo
HMRRRRRRRRRRRRN_DkFRk0<N=RODO_FRN8-_RlFjk0R8+R_#ONHR;RRRRRRRR
RRRRRCRRMR8
RCRRM
8
RRRR/m/1qR
RRDRNI#N$R5@@bCF#8RoCqp_BisRFR#bFCC8oR)q_ a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRHRRMbN_s_CoNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5)q_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH_MNbosC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5qB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHNs_bCNo_#O$MRR<=H;MN
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCqp_BisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRH_MNbosC_M#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5)q_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH_MNbosC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5Bq_ =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHM_Cbso$_#M<OR=MRHNR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@M5HNsRFRNHM_CbsoR2
RLRRCMoH
RRRRRRRRRHV5q1m_ u)t=R=RL4'jR2
RRRRRLRRCMoH
RRRRRRRRRRRRq1mRH=RM
N;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRR1RRm=qRRNHM_CbsoR;
RRRRRCRRMR8
RCRRMR8
RRRRRR
RR/R/R0FkbRk0s
CoRRRRNNDI$@#R@F5b#oC8C_RmBRpiFbsRF8#ComCR_1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR0Fk_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR_5m)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0Fk_osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5mB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0C_so#_N$RMO<N=RDFk_k
0;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#ComCR_iBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRFRRks0_C#o_$RMO<j=R;R
RRRRRRMRC8DRC#HCRVmR5_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0C_so$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5mB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0C_so$_#M<OR=DRNkk_F0R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@D5Nkk_F0sRFR0Fk_osC2R
RRCRLo
HMRRRRRRRRH5VRmt) _iBpRR=="uAYq"112R
RRRRRRCRLo
HMRRRRRRRRRRRR8k_F0RR=N_DkF;k0
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRR8k_F0RR=F_k0s;Co
RRRRRRRR8CM
RRRR8CM
R
RR#RN#MHoRz7maRR=8k_F06r6:;j9
RRRR#N#HRoMBmq1R8=R_0Fkr:66j
9;
8CMlkF8D
C
/1/7u_6n44.X.F
l8CkDRu7164n_..X4Rm57zRa,qA,R,pRBiB,R ),R a1 2
;
bNNslCC0s)Rq Bt_p=iRRY"Au1q1"/;R/AR"Y1uq1"",Bjpi"B,"p"i4
sbNN0lCCqsR)_ tB= RR "BjR";/"/RB" j, "B4b"
NlsNCs0CR q)t _)1R a=)R" a1 jR";/)/" a1 jR","1)  "a4
N
bsCNl0RCsAt) _iBpR"=RAqYu1;1"RR//"uAYq"11,p"Bi,j""iBp4b"
NlsNCs0CR A)t _BR"=RB" j;/R/R "Bj"",B" 4
sbNN0lCCAsR)_ t)  1aRR="1)  "aj;/R/"1)  "aj,)R" a1 4
"
bNNslCC0s)Ru Bt_p=iRRY"Au1q1"/;R/AR"Y1uq1"",Bjpi"B,"p"i4
sbNN0lCCusR)_ tB= RR "BjR";/"/RB" j, "B4b"
NlsNCs0CR u)t _)1R a=)R" a1 jR";/)/" a1 jR","1)  "a4
N
bsCNl0RCsmt) _iBpR"=RAqYu1;1"RR//"uAYq"11,p"Bi,j""iBp4b"
NlsNCs0CR m)t _BR"=RB" j;/R/R "Bj"",B" 4
sbNN0lCCmsR)_ t)  1aRR="1)  "aj;/R/"1)  "aj,)R" a1 4
"
bNNslCC0szRvp)a_ a1 _7vm RR="h1YB/";/YR1hqB,1BYh
k
F00bkRdr.:Rj97amz;M
HbRk0R4r4:Rj9qA,R;M
HbRk0R:r4jB9RpRi,BR ,)  1a
;
sRCoqp_Bi_,qBq ,_1)  Aa,_iBp,BA_ _,A)  1a_,uB,piu _B,)u_ a1 ,Bm_pmi,_,B m _)1; a
osCR4r4:Rj9H_MNs_CoNM#$OM,HNC_so$_#MHO,MHN,MsN_C
o;sRCor:44jH9RMsL_CNo_#O$M,LHM_osC_M#$OM,HLM,HLC_soI;
HRsCr:.djN9Rjj,L,Dlk0k_F0
j;sRCor:.djF9Rk_0js_CoNM#$Ok,F0sj_C#o_$,MOFjk0,0FkjC_soI;
HRsCr:.djl9R_0Fkjs;
CroR.jd:9kRF0C_so#_N$,MOF_k0s_Co#O$M,0Fk_osC,F8_k
0;#bkbDR$jt;h7Rk
#b$bD4BReB
;RRsIHCsRo#;0MRR//=1Rt)13t)
m;R#N#HRoMo0s#MRR=e;BB
R

RNRRD$IN#@R@5NHM_osC_$N#MFORsMRHNC_so$_#MFORsMRHLC_so#_N$RMOFHsRMsL_C#o_$RMOFFsRk_0js_CoNM#$OsRFR0FkjC_so$_#MFORskRF0C_so$_#MFORskRF0C_so#_N$2MO
RRRRoLCHRM
RRRRRHRRVvR5z_pa)  1am_v7= R=qR"1BYh"R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHM_osCRR<=H_MNs_CoNM#$OR;
RRRRRRRRRHRRMsL_C<oR=MRHLC_so#_N$;MO
RRRRRRRRRRRR0FkjC_so=R<R0FkjC_so#_N$;MO
RRRRRRRRRRRR0Fk_osCRR<=F_k0s_CoNM#$OR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRvazp_1)  va_mR7 ="=R1BYh"R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHM_osCRR<=H_MNs_Co#O$M;R
RRRRRRRRRRMRHLC_so=R<RLHM_osC_M#$OR;
RRRRRRRRRFRRk_0jsRCo<F=Rk_0js_Co#O$M;R
RRRRRRRRRRkRF0C_so=R<R0Fk_osC_M#$OR;
RRRRRCRRMR8
RCRRM
8
RRRR/D/O	C,O,#sCCl0RkRG
R/RR/ q)tR
RRDRNI#N$R5@@B2pi
RRRRoLCHRM
RRRRRHRRVqR5)_ tBRpi="=RBjpi"R2
RRRRRRRRRqRR_iBpRB=Rpjir9R;
RRRRRCRRDR#CH5VRqt) _iBpRR=="iBp4
"2RRRRRRRRRRRRqp_BiRR=Brpi4
9;RRRRC
M8
RRRRINDNR$#@B@5 R2
RLRRCMoH
RRRRRRRRRHV5 q)t _BRR=="jB "R2
RRRRRRRRRqRR_RB = RBr;j9
RRRRRRRR#CDCVRHR)5q Bt_ =R=R "B4
"2RRRRRRRRRRRRq _BRB=R 9r4;R
RRMRC8R

RNRRD$IN#@R@51)  
a2RRRRLHCoMR
RRRRRRVRHR)5q )t_ a1 RR=="1)  "aj2R
RRRRRRRRRR_Rq)  1aRR=)  1a9rj;R
RRRRRRDRC#HCRVqR5)_ t)  1a=R=R ")14 a"R2
RRRRRRRRRqRR_1)  =aRR1)  4ar9R;
RCRRM
8
RRRR/)/A Rt
RNRRD$IN#@R@5iBp2R
RRCRLo
HMRRRRRRRRH5VRAt) _iBpRR=="iBpj
"2RRRRRRRRRRRRAp_BiRR=Brpij
9;RRRRRRRRCCD#RRHV5 A)tp_Bi=R=Rp"Bi24"
RRRRRRRRRRRRBA_p=iRRiBpr;49
RRRR8CM
R
RRDRNI#N$R5@@B
 2RRRRLHCoMR
RRRRRRVRHR)5A Bt_ =R=R "Bj
"2RRRRRRRRRRRRA _BRB=R 9rj;R
RRRRRRDRC#HCRVAR5)_ tB= R=BR" 24"
RRRRRRRRRRRRBA_ RR=B4 r9R;
RCRRM
8
RRRRNNDI$@#R@ 5)12 a
RRRRoLCHRM
RRRRRHRRVAR5)_ t)  1a=R=R ")1j a"R2
RRRRRRRRRARR_1)  =aRR1)  jar9R;
RRRRRCRRDR#CH5VRAt) _1)  =aR=)R" a1 4
"2RRRRRRRRRRRRA _)1R a= R)1r a4
9;RRRRC
M8
RRRRu//)
 tRRRRNNDI$@#R@p5BiR2
RLRRCMoH
RRRRRRRRRHV5 u)tp_Bi=R=Rp"Bi2j"
RRRRRRRRRRRRBu_p=iRRiBpr;j9
RRRRRRRR#CDCVRHR)5u Bt_p=iR=BR"p"i42R
RRRRRRRRRR_RuBRpi=pRBi9r4;R
RRMRC8R

RNRRD$IN#@R@52B 
RRRRoLCHRM
RRRRRHRRVuR5)_ tB= R=BR" 2j"
RRRRRRRRRRRRBu_ RR=Bj r9R;
RRRRRCRRDR#CH5VRut) _RB ="=RB" 42R
RRRRRRRRRR_RuB= RRrB 4
9;RRRRC
M8
RRRRINDNR$#@)@5 a1 2R
RRCRLo
HMRRRRRRRRH5VRut) _1)  =aR=)R" a1 j
"2RRRRRRRRRRRRu _)1R a= R)1r aj
9;RRRRRRRRCCD#RRHV5 u)t _)1R a="=R)  1a24"
RRRRRRRRRRRR)u_ a1 R)=R a1 r;49
RRRR8CM
R
RR/R/mt) 
RRRRINDNR$#@B@5p
i2RRRRLHCoMR
RRRRRRVRHR)5m Bt_p=iR=BR"p"ij2R
RRRRRRRRRR_RmBRpi=pRBi9rj;R
RRRRRRDRC#HCRVmR5)_ tBRpi="=RB4pi"R2
RRRRRRRRRmRR_iBpRB=Rp4ir9R;
RCRRM
8
RRRRNNDI$@#R@ 5B2R
RRCRLo
HMRRRRRRRRH5VRmt) _RB ="=RB" j2R
RRRRRRRRRR_RmB= RRrB j
9;RRRRRRRRCCD#RRHV5 m)t _BRR=="4B "R2
RRRRRRRRRmRR_RB = RBr;49
RRRR8CM
R
RRDRNI#N$R5@@)  1aR2
RLRRCMoH
RRRRRRRRRHV5 m)t _)1R a="=R)  1a2j"
RRRRRRRRRRRR)m_ a1 R)=R a1 r;j9
RRRRRRRR#CDCVRHR)5m )t_ a1 RR=="1)  "a42R
RRRRRRRRRR_Rm)  1aRR=)  1a9r4;R
RRMRC8R

R/RR/MRHRosC
RRRRINDNR$#@b@5F8#CoqCR_iBpRRFsbCF#8RoCq _)1R aFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHNC_so#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRVqR5_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHNC_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVqR5_RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRMsN_CNo_#O$MRR<=qR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8C_RqBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHNC_so$_#M<OR=;RjRR
RRRRRRMRC8DRC#HCRVqR5_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHNC_so$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5qB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHNC_so$_#M<OR=;Rq
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@qsRFRNHM_osC2R
RRCRLo
HMRRRRRRRRH5VRqt) _iBpRR=="uAYq"112R
RRRRRRCRLo
HMRRRRRRRRRRRRHRMN=;Rq
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRHRMN=MRHNC_soR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8C_RABRpiFbsRF8#CoACR_1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRLHM_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR_5A)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRLHM_osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5AB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHLC_so#_N$RMO<A=R;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRBA_pFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRLHM_osC_M#$O=R<RRj;
RRRRRRRR8CMR#CDCVRHR_5A)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRLHM_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5BA_ =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRLHM_osC_M#$O=R<R
A;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@A@5RRFsH_MLs2Co
RRRRoLCHRM
RRRRRHRRVAR5)_ tBRpi="=RAqYu121"
RRRRRRRRoLCHRM
RRRRRRRRRHRRM=LRR
A;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRRHRRM=LRRLHM_osC;R
RRRRRRMRC8R
RRMRC8R

RNRR#o#HMjRNr:.dj=9RR4{{.M{HN4r49,}}HrMN4j4:9
};RRRRNH##oLMRjdr.:Rj9={R{4H.{M4Lr4}9},LHMr:44j;9}
R
RR#RN#MHoRDlk0k_F0=jRRN5!j|R|Rj!L2j?RRN:RjRR*L;jR
R
RR/R/RbbHCMDHCCRsoR
RRDRNI#N$R5@@bCF#8RoCup_BisRFR#bFCC8oR)u_ a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRFRRk_0js_CoNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5)u_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRFjk0_osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5uB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0sj_CNo_#O$MRR<=l0kD_0FkjR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8C_RuBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRkRF0sj_C#o_$RMO<j=R;R
RRRRRRMRC8DRC#HCRVuR5_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0sj_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVuR5_RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRk_0js_Co#O$MRR<=l0kD_0FkjR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@k5lDF0_kR0jFFsRk_0js2Co
RRRRoLCHRM
RRRRRHRRVuR5)_ tBRpi="=RAqYu121"
RRRRRRRRoLCHRM
RRRRRRRRRFRRkR0j=kRlDF0_k;0j
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRFjk0RF=Rk_0js;Co
RRRRRRRR8CM
RRRR8CM
R
RR/R/R0FkbRk0s
CoRRRRNNDI$@#R@F5b#oC8C_RmBRpiFbsRF8#ComCR_1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR0Fk_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR_5m)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0Fk_osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5mB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0C_so#_N$RMO<F=Rk;0j
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCmp_BisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRF_k0s_Co#O$MRR<=jR;
RRRRRCRRMC8RDR#CH5VRm _)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRks0_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVmR5_RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRks0_C#o_$RMO<F=Rk;0j
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@Fjk0RRFsF_k0s2Co
RRRRoLCHRM
RRRRRHRRVmR5)_ tBRpi="=RAqYu121"
RRRRRRRRoLCHRM
RRRRRRRRR8RR_0FkRF=Rk;0j
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRR8k_F0RR=F_k0s;Co
RRRRRRRR8CM
RRRR8CM
R
RR#RN#MHoRz7maRR=8k_F0dr.:;j9
M
C88lFk
DC
7//1nu6_X.(dln
FD8kC1R7u_6n.d(Xn7R5m,zaRRq,AB,R,pRBiB,R ),R a1 2
;
bNNslCC0s)Rq Bt_p=iRRY"Au1q1"/;R/AR"Y1uq1"",Bjpi"B,"p"i4
sbNN0lCCqsR)_ tB= RR "BjR";/"/RB" j, "B4b"
NlsNCs0CR q)t _)1R a=)R" a1 jR";/)/" a1 jR","1)  "a4
N
bsCNl0RCsAt) _iBpR"=RAqYu1;1"RR//"uAYq"11,p"Bi,j""iBp4b"
NlsNCs0CR A)t _BR"=RB" j;/R/R "Bj"",B" 4
sbNN0lCCAsR)_ t)  1aRR="1)  "aj;/R/"1)  "aj,)R" a1 4
"
bNNslCC0s)RB Bt_p=iRRY"Au1q1"/;R/AR"Y1uq1"",Bjpi"B,"p"i4
sbNN0lCCBsR)_ tB= RR "BjR";/"/RB" j, "B4b"
NlsNCs0CR B)t _)1R a=)R" a1 jR";/)/" a1 jR","1)  "a4
N
bsCNl0RCsut) _iBpR"=RAqYu1;1"RR//"uAYq"11,p"Bi,j""iBp4b"
NlsNCs0CR u)t _BR"=RB" j;/R/R "Bj"",B" 4
sbNN0lCCusR)_ t)  1aRR="1)  "aj;/R/"1)  "aj,)R" a1 4
"
bNNslCC0s)Rm Bt_p=iRRY"Au1q1"/;R/AR"Y1uq1"",Bjpi"B,"p"i4
sbNN0lCCmsR)_ tB= RR "BjR";/"/RB" j, "B4b"
NlsNCs0CR m)t _)1R a=)R" a1 jR";/)/" a1 jR","1)  "a4
N
bsCNl0RCsvazp_1)  va_mR7 =1R"Y"hB;R//1BYh,Yq1hbB
NlsNCs0CR7uq7h_ R"=Rw1qp /";/)"az, ""pwq1
 "bNNslCC0sqRu7q7_7z71ARR=4j'L;4//':LjN;88RL4'4k:#LF

kk0b0nRr.9:jRz7maH;
M0bkR.Rrn9:jR
q;HkMb0rRRdj6:9;RA
bHMkR0Rr:.6jB9R;M
HbRk0R:r4jB9RpRi,BR ,)  1a
;
sRCoqp_Bi_,qBq ,_1)  Aa,_iBp,BA_ _,A)  1a_,BB,piB _B,)B_ a1 ,Bu_pui,_,B u _)1, amp_Bi_,mBm ,_1)  
a;sRCor:.njH9RMsN_CNo_#O$M,NHM_osC_M#$OM,HNM,HNC_so_,NH
M;sRCor:d6jH9RMsL_CNo_#O$M,LHM_osC_M#$OM,HLM,HLC_sos;
CroR.j6:9MRHOC_so#_N$,MOH_MOs_Co#O$M,OHM,OHM_osC;H
IsrCR.jn:9MRHNG_C0M,HOG_C0I;
HRsCr:n.jN9Rjj,L,Dlk0k_F0
j;sRCor:n.jF9Rk_0js_CoNM#$Ok,F0sj_C#o_$,MOFjk0,0FkjC_sos;
CroRnj.:9kRF0C_so#_N$,MOF_k0s_Co#O$M,0Fk_osC,F8_k
0;
I//HRsCo0s#MRR=t31)tm1);k
#b$bDjhRt7
;R#bkbDR$4e;BBRI
RHRsCo0s#M/;R/RR=t31)tm1);N
R#o#HMsRo#R0M=BReB
;
NNDI$@#R@M5HNC_so#_N$RMOFHsRMsN_C#o_$RMOFHsRMsL_CNo_#O$MRRFsH_MLs_Co#O$MRRFsH_MOs_CoNM#$OsRFROHM_osC_M#$OsRFR0FkjC_so#_N$RMOFFsRk_0js_Co#O$MRRFsF_k0s_Co#O$MRRFsF_k0s_CoNM#$OR2
RLRRCMoH
RRRRRRRRRHV5pvza _)1_ av m7RR=="Yq1h2B"
RRRRRRRRoLCHRM
RRRRRRRRRHRRMsN_C<oR=MRHNC_so#_N$;MO
RRRRRRRRRRRRLHM_osCRR<=H_MLs_CoNM#$OR;
RRRRRRRRRHRRMsO_C<oR=MRHOC_so#_N$;MO
RRRRRRRRRRRR0FkjC_so=R<R0FkjC_so#_N$;MO
RRRRRRRRRRRR0Fk_osCRR<=F_k0s_CoNM#$OR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRvazp_1)  va_mR7 ="=R1BYh"R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHM_osCRR<=H_MNs_Co#O$M;R
RRRRRRRRRRMRHLC_so=R<RLHM_osC_M#$OR;
RRRRRRRRRHRRMsO_C<oR=MRHOC_so$_#M
O;RRRRRRRRRRRRFjk0_osCRR<=Fjk0_osC_M#$OR;
RRRRRRRRRFRRks0_C<oR=kRF0C_so$_#M
O;RRRRRRRRC
M8RRRRC
M8
RRRRO//DO	,CC,s#RC0l
kGRRRR/)/q Rt
RNRRD$IN#@R@5iBp2R
RRCRLo
HMRRRRRRRRH5VRqt) _iBpRR=="iBpj
"2RRRRRRRRRRRRqp_BiRR=Brpij
9;RRRRRRRRCCD#RRHV5 q)tp_Bi=R=Rp"Bi24"
RRRRRRRRRRRRBq_p=iRRiBpr;49
RRRR8CM
R
RRDRNI#N$R5@@B
 2RRRRLHCoMR
RRRRRRVRHR)5q Bt_ =R=R "Bj
"2RRRRRRRRRRRRq _BRB=R 9rj;R
RRRRRRDRC#HCRVqR5)_ tB= R=BR" 24"
RRRRRRRRRRRRBq_ RR=B4 r9R;
RCRRM
8
RRRRNNDI$@#R@ 5)12 a
RRRRoLCHRM
RRRRRHRRVqR5)_ t)  1a=R=R ")1j a"R2
RRRRRRRRRqRR_1)  =aRR1)  jar9R;
RRRRRCRRDR#CH5VRqt) _1)  =aR=)R" a1 4
"2RRRRRRRRRRRRq _)1R a= R)1r a4
9;RRRRC
M8
RRRRA//)
 tRRRRNNDI$@#R@p5BiR2
RLRRCMoH
RRRRRRRRRHV5 A)tp_Bi=R=Rp"Bi2j"
RRRRRRRRRRRRBA_p=iRRiBpr;j9
RRRRRRRR#CDCVRHR)5A Bt_p=iR=BR"p"i42R
RRRRRRRRRR_RABRpi=pRBi9r4;R
RRMRC8R

RNRRD$IN#@R@52B 
RRRRoLCHRM
RRRRRHRRVAR5)_ tB= R=BR" 2j"
RRRRRRRRRRRRBA_ RR=Bj r9R;
RRRRRCRRDR#CH5VRAt) _RB ="=RB" 42R
RRRRRRRRRR_RAB= RRrB 4
9;RRRRC
M8
RRRRINDNR$#@)@5 a1 2R
RRCRLo
HMRRRRRRRRH5VRAt) _1)  =aR=)R" a1 j
"2RRRRRRRRRRRRA _)1R a= R)1r aj
9;RRRRRRRRCCD#RRHV5 A)t _)1R a="=R)  1a24"
RRRRRRRRRRRR)A_ a1 R)=R a1 r;49
RRRR8CM
R
RR/R/Bt) 
RRRRINDNR$#@B@5p
i2RRRRLHCoMR
RRRRRRVRHR)5B Bt_p=iR=BR"p"ij2R
RRRRRRRRRR_RBBRpi=pRBi9rj;R
RRRRRRDRC#HCRVBR5)_ tBRpi="=RB4pi"R2
RRRRRRRRRBRR_iBpRB=Rp4ir9R;
RCRRM
8
RRRRNNDI$@#R@ 5B2R
RRCRLo
HMRRRRRRRRH5VRBt) _RB ="=RB" j2R
RRRRRRRRRR_RBB= RRrB j
9;RRRRRRRRCCD#RRHV5 B)t _BRR=="4B "R2
RRRRRRRRRBRR_RB = RBr;49
RRRR8CM
R
RRDRNI#N$R5@@)  1aR2
RLRRCMoH
RRRRRRRRRHV5 B)t _)1R a="=R)  1a2j"
RRRRRRRRRRRR)B_ a1 R)=R a1 r;j9
RRRRRRRR#CDCVRHR)5B )t_ a1 RR=="1)  "a42R
RRRRRRRRRR_RB)  1aRR=)  1a9r4;R
RRMRC8R

R/RR/ u)tR
RRDRNI#N$R5@@B2pi
RRRRoLCHRM
RRRRRHRRVuR5)_ tBRpi="=RBjpi"R2
RRRRRRRRRuRR_iBpRB=Rpjir9R;
RRRRRCRRDR#CH5VRut) _iBpRR=="iBp4
"2RRRRRRRRRRRRup_BiRR=Brpi4
9;RRRRC
M8
RRRRINDNR$#@B@5 R2
RLRRCMoH
RRRRRRRRRHV5 u)t _BRR=="jB "R2
RRRRRRRRRuRR_RB = RBr;j9
RRRRRRRR#CDCVRHR)5u Bt_ =R=R "B4
"2RRRRRRRRRRRRu _BRB=R 9r4;R
RRMRC8R

RNRRD$IN#@R@51)  
a2RRRRLHCoMR
RRRRRRVRHR)5u )t_ a1 RR=="1)  "aj2R
RRRRRRRRRR_Ru)  1aRR=)  1a9rj;R
RRRRRRDRC#HCRVuR5)_ t)  1a=R=R ")14 a"R2
RRRRRRRRRuRR_1)  =aRR1)  4ar9R;
RCRRM
8
RRRR/)/m Rt
RNRRD$IN#@R@5iBp2R
RRCRLo
HMRRRRRRRRH5VRmt) _iBpRR=="iBpj
"2RRRRRRRRRRRRmp_BiRR=Brpij
9;RRRRRRRRCCD#RRHV5 m)tp_Bi=R=Rp"Bi24"
RRRRRRRRRRRRBm_p=iRRiBpr;49
RRRR8CM
R
RRDRNI#N$R5@@B
 2RRRRLHCoMR
RRRRRRVRHR)5m Bt_ =R=R "Bj
"2RRRRRRRRRRRRm _BRB=R 9rj;R
RRRRRRDRC#HCRVmR5)_ tB= R=BR" 24"
RRRRRRRRRRRRBm_ RR=B4 r9R;
RCRRM
8
RRRRNNDI$@#R@ 5)12 a
RRRRoLCHRM
RRRRRHRRVmR5)_ t)  1a=R=R ")1j a"R2
RRRRRRRRRmRR_1)  =aRR1)  jar9R;
RRRRRCRRDR#CH5VRmt) _1)  =aR=)R" a1 4
"2RRRRRRRRRRRRm _)1R a= R)1r a4
9;RRRRC
M8
RRRRR//HsMRCRo
RNRRD$IN#@R@5#bFCC8oRBq_pFiRsFRb#oC8C_Rq)  1asRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRH_MNs_CoNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5)q_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH_MNs_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5Bq_ =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHM_osC_$N#M<OR=;Rq
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCqp_BisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRH_MNs_Co#O$MRR<=j
;RRRRRRRRRCRM8CCD#RRHV5)q_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH_MNs_Co#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRq _BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH_MNs_Co#O$MRR<=qR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@R5qFHsRMsN_C
o2RRRRLHCoMR
RRRRRRVRHR)5q Bt_p=iR=AR"Y1uq1
"2RRRRRRRRLHCoMR
RRRRRRRRRRMRHNRR=qR;
RRRRRCRRMC8RD
#CRRRRRRRRLHCoMR
RRRRRRRRRRMRHNRR=H_MNs;Co
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCAp_BisRFR#bFCC8oR)A_ a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRHRRMsL_CNo_#O$MRR<=jR;
RRRRRCRRMC8RDR#CH5VRA _)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRMsL_CNo_#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRA _BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH_MLs_CoNM#$O=R<R
A;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoACR_iBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRHRRMsL_C#o_$RMO<j=R;RR
RRRRRCRRMC8RDR#CH5VRA _)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRMsL_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVAR5_RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRMsL_C#o_$RMO<A=R;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5FARsMRHLC_soR2
RLRRCMoH
RRRRRRRRRHV5 A)tp_Bi=R=RY"Au1q1"R2
RRRRRLRRCMoH
RRRRRRRRRRRRLHMRA=R;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRRLHMRH=RMsL_C
o;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoBCR_iBpRRFsbCF#8RoCB _)1R aFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHOC_so#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRVBR5_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHOC_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5_RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRMsO_CNo_#O$MRR<=BR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8C_RBBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHOC_so$_#M<OR=;RjRR
RRRRRRMRC8DRC#HCRVBR5_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHOC_so$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR_5BB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHOC_so$_#M<OR=;RB
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@BsRFROHM_osC2R
RRCRLo
HMRRRRRRRRH5VRBt) _iBpRR=="uAYq"112R
RRRRRRCRLo
HMRRRRRRRRRRRRHRMO=;RB
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRHRMO=MRHOC_soR;
RRRRRCRRMR8
RCRRM
8
RRRR/q/u7F7RsFRM0R
RR#RN#MHoRNHM_0CGR{=RHrMN.,69HrMN.j6:9
};RRRRNH##oHMRMCO_G=0RRM{HO6r.9M,HO6r.:}j9;R

RNRRD$IN#5@@H_MNCRG0FHsRMCO_GF0RsMRHNR2
RLRRCMoH
RRRRRRRR5HVu7q7_R h="=Ra )z"R2
RRRRRLRRCMoH
RRRRRRRRRRRR5HVu7q7_7q71RzA=4=R'2LjRoLCHRM
RRRRRRRRRRRRRNRR_RHM=MRHNG_C0RR+H_MOC;G0
RRRRRRRRRRRR8CMR#CDCCRLo
HMRRRRRRRRRRRRRRRRNM_HRH=RMCN_G-0RROHM_0CG;R
RRRRRRRRRRMRC8R
RRRRRRMRC8DRC#LCRCMoH
RRRRRRRRRRRRHN_MRR=H;MN
RRRRRRRR8CM
RRRR8CM
R
RR#RN#MHoRrNjnj.:9RR={n{d{HN_Mnr.9,}}NM_Hr:.nj;9}
RRRR#N#HRoMLnjr.9:jR{=R{{.(HrMLd}69}M,HL6rd:}j9;R

RNRR#o#HMkRlDF0_kR0j=!R5N|jR|LR!jR2?jRR:N*jRRRLj;R

R/RR/HRbbHCDMsCRCRo
RNRRD$IN#@R@5#bFCC8oRBu_pFiRsFRb#oC8C_Ru)  1asRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRFjk0_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR_5u)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0FkjC_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVuR5_RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRk_0js_CoNM#$O=R<RDlk0k_F0
j;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CouCR_iBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRFRRk_0js_Co#O$MRR<=jR;
RRRRRCRRMC8RDR#CH5VRu _)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRk_0js_Co#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRu _BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRFjk0_osC_M#$O=R<RDlk0k_F0
j;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@l@5k_D0Fjk0RRFsFjk0_osC2R
RRCRLo
HMRRRRRRRRH5VRut) _iBpRR=="uAYq"112R
RRRRRRCRLo
HMRRRRRRRRRRRRFjk0Rl=Rk_D0Fjk0;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRR0FkjRR=Fjk0_osC;R
RRRRRRMRC8R
RRMRC8R

R/RR/kRF00bkRosC
RRRRINDNR$#@b@5F8#ComCR_iBpRRFsbCF#8RoCm _)1R aFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRkRF0C_so#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRVmR5_1)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0C_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVmR5_RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRks0_CNo_#O$MRR<=Fjk0;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRBm_pFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR0Fk_osC_M#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5)m_ a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRF_k0s_Co#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRm _BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRF_k0s_Co#O$MRR<=Fjk0;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@50FkjsRFR0Fk_osC2R
RRCRLo
HMRRRRRRRRH5VRmt) _iBpRR=="uAYq"112R
RRRRRRCRLo
HMRRRRRRRRRRRR8k_F0RR=Fjk0;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRRF8_k=0RR0Fk_osC;R
RRRRRRMRC8R
RRMRC8R

RNRR#o#HMmR7z=aRRF8_kn0r.9:j;C

MF8l8CkD
