// --------------------------------------------------------------------
@ER//>>>>>>>>>>>>>>>>>>>>>>>>>mRBuQY)tR]ahQmaB< R<<<<<<<<<<<<<<<<<<<<<<<<
R//--------------------------------------------------------------------
C`ODCD8VCHM
H`0lOC#NRDC4#RMR4/RR
b#
8lFkRDCvazpqq77pUz4XR4U5z7maB,Rq,1mRq1m,mR1Aq,RjA,Rjq,R4A,R4B,R,QR1q1,RQRA,BQq1,BRqBqpm7q,R1, pR A1pq,R1hQt,1RAQ,thRiBp, RB, R)12 a;H

M0bkR(r4:Rj9q
j;HkMb04Rr(9:jR;Aj
bHMkr0R4j(:94Rq;M
HbRk0r:4(jA9R4H;
M0bkRdr6:Rj9BH;
M0bkR(r4:Rj91,QqRA1Q;M
HbRk0rj4:91RqQ,thRQA1t
h;HkMb04Rr:Rj9qp1 ,1RA 
p;HkMb06Rrc9:jR1BqQH;
M0bkR;B 
bHMkB0Rp
i;HkMb0 R)1; a
bHMkq0RBmBpq
7;Fbk0kr0R6jd:9mR7z
a;Fbk0kr0R6jc:9qRB1
m;Fbk0kr0R4j(:9mR1q1,Rm
A;
b#kbjD$R7th;#R
kDbb$e4RBRB;
N
bsCNl0RCsq j)tRR=4j'L;/R/RL4'jL:R$#bN#FRl8RC;44'L:CRso0H#C8sCR8lFCN
bsCNl0RCsq 4)tRR=4j'L;N
bsCNl0RCsA j)tRR=4j'L;N
bsCNl0RCsA 4)tRR=4j'L;N
bsCNl0RCsBt) R4=R';Lj
sbNN0lCCusRQju _t) R4=R';Lj
sbNN0lCCusRQ4u _t) R4=R';Lj
sbNN0lCCmsRz)a_ =tRRL4'jb;
NlsNCs0CRQq1t_hj)R t='R4L
j;bNNslCC0s1RqQ4th_t) R4=R';Lj
sbNN0lCCqsRBmBpq)7_ Rtj='R4L
j;bNNslCC0sBRqBqpm7 _)t=4RRL4'jb;
NlsNCs0CRQA1t_hj)R t='R4L
j;bNNslCC0s1RAQ4th_t) R4=R';Lj
sbNN0lCC1sRm)q_ =tRRL4'jb;
NlsNCs0CRqA_717_z=ARRL4'j/;R/'R4LNj:8R8;44'L:L#k
sbNN0lCCBsR_7q7_A1zR4=R';Lj
sbNN0lCCvsRzqpa7p7qzX4U4vU_mR7 =;Rj/:/j44UGU/R+-UR4GR4U+R/-BR;R4q:RBjB/R4+RUUG4R-+/RG4U4RU;.U:4GR4U+R/-44UGURR+BQq1
sbNN0lCCvsRz_pa)  1am_v7= RRY"1h;B"/1/RY,hBqh1YBR

RsRRCNoR#MHoj__js_CoNM#$O#,NHjoM_sj_C#o_$,MONo#HMj4__osC_$N#MNO,#MHo4__js_Co#O$M,#NLH_oMjC_so#_N$,MONHL#ojM__osC_M#$OL,N#MHo_s4_CNo_#O$M,#NLH_oM4C_so$_#M
O;RRRRsRCoNo#HMjj__osC,HN#o_M4jC_soL,N#MHo_sj_CNo,Lo#HM__4s,CoRHN#o_Mjj#,NH4oM_Nj,Lo#HMjj_,#NLH4oM_Nj,Lo#HM,_jNHL#o4M_;R
RRCRso#RLHjoM_sj_CNo_#O$M,HL#o_MjjC_so$_#MLO,#MHo4__js_CoNM#$O#,LH4oM_sj_C#o_$;MO
RRRRosCRHL#o_Mjj#,LHjoM_sj_CLo,#MHo4__js,CoLo#HMj4_;R
RRCRsoORNONDF8sj_CNo_#O$M,ORNONDF8sj_C#o_$,MORONOD8FN_Rj,NDOOFjN8_osC,ORNONDF8s4_CNo_#O$M,ORNONDF8s4_C#o_$,MORONOD8FN4C_soO,NONDF8;_4
R
RRCRsorRR4j(:9HRlM,NjlNHM4H,lM,LjlLHM4M,HNsj_CRo,HjML_osC,NHM4C_soH,RM_L4s,CoH.MN_osC;R
RRCRsorRR4j(:9MRHNRj,HjML,NHM4H,RM,L4H.MN;R
RRCRso4Rr(9:jRNHMjC_so#_N$,MOHjMN_osC_M#$OM,HNs4_CNo_#O$M,NHM4C_so$_#MHO,M_Ljs_CoNM#$OM,HLsj_C#o_$,MOH4ML_osC_$N#MHO,M_L4s_Co#O$M,NHM.C_so#_N$,MOH.MN_osC_M#$OR;
RsRRCroR6jd:9MRHOC_so#_N$,MOH_MOs_Co#O$M,OHM_osC,OHM;R
RRHRIsrCRdj6:9kRlDF0_k,0jl0kD_0Fk4R;
RsRRCroR6jc:9kRF0jj_,0Fk4;_j
R
RRCRsodRr69:jR0FkjC_so#_N$,MOFjk0_osC_M#$Ok,F0s4_CNo_#O$M,0Fk4C_so$_#MFO,k,0jFjk0_osC,0Fk4C_sok,F0
4;RRRRICHsR#NLH,oMNHL#ojM__Nj,Lo#HM__4jR;
RsRRCroR6jc:9FR8kl0,_0Fk,0Fk_osC,0Fk_M#$Ok,F0#_N$;MO
RRRRsIHC6Rrc9:jROHM_0CG,ONO_NDF8R;
RsRRCroRdj6:9jRN,jRL,,N4R;L4
RRRRsIHCsRo#;0MRR//=1Rt)13t)
m;S#N#HRoMo0s#MRR=e;BB
R
RRDRNI#N$R5@@HjMN_osC_$N#MFORsMRHNsj_C#o_$RMOFHsRM_N4s_CoNM#$OsRFRNHM4C_so$_#MFORsMRHNs._CNo_#O$MRRFsH.MN_osC_M#$OsRFRLHMjC_so#_N$RMOFHsRM_Ljs_Co#O$MRRFsH4ML_osC_$N#MFORsMRHLs4_C#o_$RMOFHsRMsO_CNo_#O$MRRFsH_MOs_Co#O$MRRFsNo#HMjj__osC_$N#MFORs#RNHjoM_sj_C#o_$RMOFNsRLo#HM__js_CoNM#$OsRFR#NLH_oMjC_so$_#MFORsLRN#MHo_s4_CNo_#O$MRRFsNHL#o4M__osC_M#$OsRFRHN#o_M4jC_so#_N$RMOFNsR#MHo4__js_Co#O$MRRFsLo#HMjj__osC_$N#MFORs#RLHjoM_sj_C#o_$RMOFLsR#MHo4__js_CoNM#$OsRFRHL#o_M4jC_so$_#MFORsORNONDF8sj_CNo_#O$MRRFsNDOOF4N8_osC_$N#MFORsORNONDF8sj_C#o_$RMOFNsROFODN_84s_Co#O$MRRFsFjk0_osC_$N#MFORskRF0sj_C#o_$RMOFFsRk_04s_CoNM#$OsRFR0Fk4C_so$_#MFORskRF0$_#MFORskRF0#_N$2MO
RRRRoLCHRM
RRRRRHRRVvR5z_pa)  1am_v7= R=qR"1BYh"R2
RRRRRLRRCMoH
RRRRRRRRRRRRNHMjC_so=R<RNHMjC_so#_N$;MO
RRRRRRRRRRRRNHM4C_so=R<RNHM4C_so#_N$;MO
RRRRRRRRRRRRNHM.C_so=R<RNHM.C_so#_N$;MO
RRRRRRRRRRRRLHMjC_so=R<RLHMjC_so#_N$;MO
RRRRRRRRRRRRLHM4C_so=R<RLHM4C_so#_N$;MO
RRRRRRRRRRRROHM_osCRR<=H_MOs_CoNM#$OR;
RRRRRRRRRNRR#MHoj__jsRCo<N=R#MHoj__js_CoNM#$OR;
RRRRRRRRRNRR#MHo4__jsRCo<N=R#MHo4__js_CoNM#$OR;
RRRRRRRRRLRR#MHoj__jsRCo<L=R#MHoj__js_CoNM#$OR;
RRRRRRRRRLRR#MHo4__jsRCo<L=R#MHo4__js_CoNM#$OR;
RRRRRRRRRNRRLo#HM__jsRCo<N=RLo#HM__js_CoNM#$OR;
RRRRRRRRRNRRLo#HM__4sRCo<N=RLo#HM__4s_CoNM#$OR;
RRRRRRRRRNRROFODN_8jsRCo<N=ROFODN_8js_CoNM#$OR;
RRRRRRRRRNRROFODN_84sRCo<N=ROFODN_84s_CoNM#$OR;
RRRRRRRRRFRRk_0jsRCo<F=Rk_0js_CoNM#$OR;
RRRRRRRRRFRRk_04sRCo<F=Rk_04s_CoNM#$OR;
RRRRRRRRRFRRks0_C<oR=kRF0#_N$;MO
RRRRRRRR8CM
RRRRRRRR#CDCVRHRz5vp)a_ a1 _7vm =R=RY"1h2B"
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_NjsRCo<H=RM_Njs_Co#O$M;R
RRRRRRRRRRMRHNs4_C<oR=MRHNs4_C#o_$;MO
RRRRRRRRRRRRNHM.C_so=R<RNHM.C_so$_#M
O;RRRRRRRRRRRRHjML_osCRR<=HjML_osC_M#$OR;
RRRRRRRRRHRRM_L4sRCo<H=RM_L4s_Co#O$M;R
RRRRRRRRRRMRHOC_so=R<ROHM_osC_M#$OR;
RRRRRRRRRNRR#MHoj__jsRCo<N=R#MHoj__js_Co#O$M;R
RRRRRRRRRR#RNH4oM_sj_C<oR=#RNH4oM_sj_C#o_$;MO
RRRRRRRRRRRRHL#o_MjjC_so=R<RHL#o_MjjC_so$_#M
O;RRRRRRRRRRRRLo#HMj4__osCRR<=Lo#HMj4__osC_M#$OR;
RRRRRRRRRNRRLo#HM__jsRCo<N=RLo#HM__js_Co#O$M;R
RRRRRRRRRRLRN#MHo_s4_C<oR=LRN#MHo_s4_C#o_$;MO
RRRRRRRRRRRRONOD8FNjC_so=R<RONOD8FNjC_so$_#M
O;RRRRRRRRRRRRNDOOF4N8_osCRR<=NDOOF4N8_osC_M#$OR;
RRRRRRRRRFRRk_0jsRCo<F=Rk_0js_Co#O$M;R
RRRRRRRRRRkRF0s4_C<oR=kRF0s4_C#o_$;MO
RRRRRRRRRRRR0Fk_osCRR<=F_k0#O$M;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@Rj5qRRFs1RQqFqsR12 pRR
RRCRLo
HMRRRRRRRRHqV51r pj=9R='R4LRj2
RRRRRRRRoLCHRM
RRRRRRRRRlRRHjMNRq=RjR;
RRRRRCRRMC8RDR#CLHCoMR
RRRRRRRRRRHRlMRNj=QR1qR;
RRRRRCRRMR8
RCRRM
8
RRRR/H/RMCRsoR
RRDRNI#N$R5@@bCF#8RoCBRpiFbsRF8#Co)CR a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRHRRM_Njs_CoNM#$O=R<RRj;
RRRRRRRR8CMR#CDCVRHR 5)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_Njs_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_Njs_CoNM#$O=R<RMlHN
j;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoBCRpFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRNHMjC_so$_#M<OR=;RjRR
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRHjMN_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_Njs_Co#O$MRR<=lNHMjR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@HR5M,NjR,q4R q1pR2
RLRRCMoH
RRRRRRRR5HVqp1 rR49=4=R'2LjRR
RRRRRRCRLo
HMRRRRRRRRRRRRlNHM4RR=q
4;RRRRRRRRCRM8CCD#RoLCHRM
RRRRRRRRRlRRH4MNRH=RM;Nj
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCBRpiFbsRF8#Co)CR a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRHRRM_N4s_CoNM#$O=R<R
j;RRRRRRRRRRRRH.MN_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR 5)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_N4s_CoNM#$O=R<R
j;RRRRRRRRRRRRH.MN_osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR 5BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH4MN_osC_$N#M<OR=HRlM;N4
RRRRRRRRRRRRNHM.C_so#_N$RMO<H=RM;N4
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHNs4_C#o_$RMO<j=R;RR
RRRRRRRRRHRRM_N.s_Co#O$MRR<=j
;RRRRRRRRRCRM8CCD#RRHV51)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHNs4_C#o_$RMO<j=R;R
RRRRRRRRRRMRHNs._C#o_$RMO<j=R;RR
RRRRRCRRMR8
RRRRRCRRDR#CH5VRB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHNs4_C#o_$RMO<l=RH4MN;R
RRRRRRRRRRMRHNs._C#o_$RMO<H=RM;N4RR
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5MlHNFjRsMRHNsj_C
o2RRRRLHCoMR
RRRRRRVRHRj5q)R t=4=R'2Lj
RRRRRRRRoLCHRM
RRRRRRRRRHRRMRNj=HRlM;Nj
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRHjMNRH=RM_Njs;Co
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@lNHM4sRFRNHM4C_soR2
RLRRCMoH
RRRRRRRRRHV5)q4 =tR='R4L
j2RRRRRRRRLHCoMR
RRRRRRRRRRMRHN=4RRMlHN
4;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRRHRRMRN4=MRHNs4_C
o;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@H@5MRN4FHsRM_N.s2Co
RRRRoLCHRM
RRRRRHRRV1R5m)q_ =tR='R4L
j2RRRRRRRRLHCoMR
RRRRRRRRRRMRHN=.RRNHM4R;
RRRRRCRRMC8RD
#CRRRRRRRRLHCoMR
RRRRRRRRRRMRHN=.RRNHM.C_soR;
RRRRRCRRMR8
RCRRM
8
RRRRNH##o1MRm=qRRNHM.
;
RRRRNNDI$@#R@j5ARRFs1RQAFAsR12 pRR
RRCRLo
HMRRRRRRRRHAV51r pj=9R='R4LRj2
RRRRRRRRoLCHRM
RRRRRRRRRlRRHjMLRA=RjR;
RRRRRCRRMC8RDR#CLHCoMR
RRRRRRRRRRHRlMRLj=QR1AR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFR#bFCC8oR1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRLHMjC_so#_N$RMO<j=R;RR
RRRRRCRRMC8RDR#CH5VR)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRLHMjC_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRLHMjC_so#_N$RMO<l=RHjML;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRiBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRHRRM_Ljs_Co#O$MRR<=j
;RRRRRRRRRCRM8CCD#RRHV51)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHLsj_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRLHMjC_so$_#M<OR=HRlM;Lj
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$RR@@5RA4FHsRMRLjFAsR12 pRR
RRCRLo
HMRRRRRRRRHAV51r p4=9R='R4L
j2RRRRRRRRLHCoMR
RRRRRRRRRRHRlMRL4=4RA;R
RRRRRRMRC8DRC#LCRCMoH
RRRRRRRRRRRRMlHL=4RRLHMjR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFR#bFCC8oR1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRLHM4C_so#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH4ML_osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR 5BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH4ML_osC_$N#M<OR=HRlM;L4
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHLs4_C#o_$RMO<j=R;R
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH4ML_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_L4s_Co#O$MRR<=lLHM4R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFR#bFCC8oR1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRROHM_osC_$N#M<OR=;RjRR
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH_MOs_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRMsO_CNo_#O$MRR<=BR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRH_MOs_Co#O$MRR<=j
;RRRRRRRRRCRM8CCD#RRHV51)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHOC_so$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR 5BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH_MOs_Co#O$MRR<=BR;
RRRRRCRRMR8
RCRRMR8
R
RRRRRRNNDI$@#R@H5lMRLjFHsRM_Ljs2Co
RRRRoLCHRM
RRRRRHRRVAR5jt) RR==4j'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRHjMLRl=RHjML;R
RRRRRRMRC8DRC#
CRRRRRRRRRLHCoMR
RRRRRRRRRRMRHL=jRRLHMjC_soR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@H5lMRL4FHsRM_L4s2Co
RRRRoLCHRM
RRRRRHRRVAR54t) RR==4j'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRH4MLRl=RH4ML;R
RRRRRRMRC8DRC#LCRCMoH
RRRRRRRRRRRRLHM4RR=H4ML_osC;R
RRRRRRMRC8R
RRMRC8R

RNRR#o#HMmR1ARR=H4ML;R

RNRRD$IN#@R@5FBRsMRHOC_soR2
RLRRCMoH
RRRRRRRRRHV5 B)t=R=RL4'jR2
RRRRRLRRCMoH
RRRRRRRRRRRROHMRB=R;R
RRRRRRMRC8DRC#LCRCMoH
RRRRRRRRRRRROHMRH=RMsO_C
o;RRRRRRRRC
M8RRRRC
M8
RRRRN//#MHoRosC
RRRRINDNR$#@b@5F8#CoBCRpFiRsFRb#oC8C R)1R aFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRR#RNHjoM_sj_CNo_#O$MRR<=jR;R
RRRRRRRR8CMR#CDCVRHR 5)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR#MHoj__js_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR#MHoj__js_CoNM#$O=R<RQq1tjhr9R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRNo#HMjj__osC_M#$O=R<RRj;RR
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRNo#HMjj__osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR#MHoj__js_Co#O$MRR<=qt1Qh9rj;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRiBpRRFsbCF#8RoC)  1asRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRNo#HMj4__osC_$N#M<OR=;RjRRR
RRRRRCRRMC8RDR#CH5VR)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRHN#o_M4jC_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRHN#o_M4jC_so#_N$RMO<q=R1hQtr;49
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRR#RNH4oM_sj_C#o_$RMO<j=R;
RRRRRRRRRRCRM8CCD#RRHV51)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRR#RNH4oM_sj_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRHN#o_M4jC_so$_#M<OR=1RqQrth4
9;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@q@51hQtrRj9FNsR#MHoj__js2Co
RRRRoLCHRM
RRRRRHRRVqR51hQtj _)t=R=RL4'jR2
RRRRRLRRCMoH
RRRRRRRRRRRRHN#o_MjjRR=qt1Qh9rj;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRRHN#o_MjjRR=No#HMjj__osC;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5Qq1t4hr9sRFRHN#o_M4jC_soR2
RLRRCMoH
RRRRRRRRRHV5Qq1t_h4)R t=4=R'2Lj
RRRRRRRRoLCHRM
RRRRRRRRRNRR#MHo4R_j=1RqQrth4
9;RRRRRRRRCRM8CCD#RR
RRRRRRCRLo
HMRRRRRRRRRRRRNo#HMj4_RN=R#MHo4__js;Co
RRRRRRRR8CM
RRRR8CM
R
RR/R/Lo#HMCRsoR
RRDRNI#N$R5@@bCF#8RoCBRpiFbsRF8#Co)CR a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRLRR#MHoj__js_CoNM#$O=R<RRj;RR
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRLo#HMjj__osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR 5BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRLo#HMjj__osC_$N#M<OR=1RAQrthj
9;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoBCRpFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRHL#o_MjjC_so$_#M<OR=;RjRRR
RRRRRCRRMC8RDR#CH5VR)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRHL#o_MjjC_so$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR 5BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRLo#HMjj__osC_M#$O=R<RQA1tjhr9R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFR#bFCC8oR1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRHL#o_M4jC_so#_N$RMO<j=R;
RRRRRRRRRRCRM8CCD#RRHV51)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRR#RLH4oM_sj_CNo_#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRR#RLH4oM_sj_CNo_#O$MRR<=At1Qh9r4;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRiBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRLRR#MHo4__js_Co#O$MRR<=jR;R
RRRRRRRR8CMR#CDCVRHR 5)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRLRR#MHo4__js_Co#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRR#RLH4oM_sj_C#o_$RMO<A=R1hQtr;49
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@At1Qh9rjRRFsLo#HMjj__osC2R
RRCRLo
HMRRRRRRRRH5VRAt1Qh)j_ =tR='R4L
j2RRRRRRRRLHCoMR
RRRRRRRRRR#RLHjoM_=jRRQA1tjhr9R;
RRRRRCRRMC8RD
#CRRRRRRRRLHCoMR
RRRRRRRRRR#RLHjoM_=jRRHL#o_MjjC_soR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@15AQrth4F9Rs#RLH4oM_sj_C
o2RRRRLHCoMR
RRRRRRVRHR15AQ4th_t) RR==4j'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRLo#HMj4_RA=R1hQtr;49
RRRRRRRR8CMR#CDCCRLo
HMRRRRRRRRRRRRLo#HMj4_RL=R#MHo4__js;Co
RRRRRRRR8CM
RRRR8CM
R
RR#RN#MHoR#NLH_oMjR_j=#RNHjoM_|jR|#RLHjoM_
j;RRRRNH##oNMRLo#HM__4jRR=No#HMj4_RR||Lo#HMj4_;R

RNRRD$IN#@R@5#bFCC8oRiBpRRFsbCF#8RoC)  1asRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRNDOOFjN8_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR 5)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRROFODN_8js_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRROFODN_8js_CoNM#$O=R<RBqBp7mq;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRiBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRNRROFODN_8js_Co#O$MRR<=j
;RRRRRRRRRCRM8CCD#RRHV51)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8sj_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FNjC_so$_#M<OR=BRqBqpm7R;
RRRRRCRRMR8
RCRRMR8

RRRRINDNR$#@q@5BmBpqF7RsORNONDF8sj_C
o2RRRRLHCoMR
RRRRRRVRHRB5qBqpm7 _)t=jR='R4L
j2RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8R_j<q=RBmBpq
7;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRRNRROFODNj8_RR<=NDOOFjN8_osC;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRiBpRRFsbCF#8RoC)  1asRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRNDOOF4N8_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR 5)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRROFODN_84s_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRROFODN_84s_CoNM#$O=R<RONOD8FN_
j;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoBCRpFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRONOD8FN4C_so$_#M<OR=;RjRR
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRNDOOF4N8_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRROFODN_84s_Co#O$MRR<=NDOOF_N8jR;
RRRRRCRRMR8
RCRRMR8

RRRRINDNR$#@N@5OFODNj8_RRFsNDOOF4N8_osC2R
RRCRLo
HMRRRRRRRRH5VRqpBBm_q7)4 tRR==4j'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRNDOOF_N84=R<RONOD8FN_
j;RRRRRRRRCRM8CCD#RR
RRRRRRCRLo
HMRRRRRRRRRRRRNDOOF_N84=R<RONOD8FN4C_soR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@M5HNFjRs#RNHjoM_
j2RRRRLHCoMR
RRRRRRVRHR#5NHjoM_=jR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRjRNr:4(j=9RRNHMj(r4:;j9
RRRRRRRRRRRRrNjd46:U=9RRM{HN4jr(H9,MrNj4,(9HjMNr94(,NHMj(r49M,HN4jr(H9,MrNj4,(9HjMNr94(,NHMj(r49M,HN4jr(H9,MrNj4,(9HjMNr94(,NHMj(r49M,HN4jr(H9,MrNj4,(9HjMNr94(,NHMj(r49M,HN4jr(H9,MrNj4}(9;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRRrNj4j(:9RR=RNHMj(r4:;j9
RRRRRRRRRRRRrNjd46:U=9RR
j;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@H@5MRN4FNsR#MHo42_j
RRRRoLCHRM
RRRRRHRRVNR5#MHo4R_j=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR4(r4:Rj9=MRHN44r(9:j;R
RRRRRRRRRR4RNr:d64RU9=HR{MrN44,(9H4MNr94(,NHM4(r49M,HN44r(H9,MrN44,(9H4MNr94(,NHM4(r49M,HN44r(H9,MrN44,(9H4MNr94(,NHM4(r49M,HN44r(H9,MrN44,(9H4MNr94(,NHM4(r49M,HN44r(H9,MrN44,(9H4MNr94(}R;
RRRRRCRRMC8RD
#CRRRRRRRRLHCoMR
RRRRRRRRRR4RNr:4(j=9RRMRHN44r(9:j;R
RRRRRRRRRR4RNr:d64RU9=;Rj
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@HjMLRRFsLo#HMjj_2R
RRCRLo
HMRRRRRRRRH5VRLo#HMjj_RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRL4jr(9:jRH=RMrLj4j(:9R;
RRRRRRRRRLRRj6rd:94UR{=RHjMLr94(,LHMj(r49M,HL4jr(H9,MrLj4,(9HjMLr94(,LHMj(r49M,HL4jr(H9,MrLj4,(9HjMLr94(,LHMj(r49M,HL4jr(H9,MrLj4,(9HjMLr94(,LHMj(r49M,HL4jr(H9,MrLj4,(9HjMLr94(,LHMj(r49
};RRRRRRRRCRM8CCD#RR
RRRRRRCRLo
HMRRRRRRRRRRRRL4jr(9:jRH=RMrLj4j(:9R;
RRRRRRRRRLRRj6rd:94URj=R;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5LHM4sRFRHL#o_M4jR2
RLRRCMoH
RRRRRRRRRHV5HL#o_M4j=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRrL44j(:9RR=H4MLr:4(j
9;RRRRRRRRRRRRLd4r6U:49RR={LHM4(r49M,HL44r(H9,MrL44,(9H4MLr94(,LHM4(r49M,HL44r(H9,MrL44,(9H4MLr94(,LHM4(r49M,HL44r(H9,MrL44,(9H4MLr94(,LHM4(r49M,HL44r(H9,MrL44,(9H4MLr94(,LHM4(r49M,HL44r(;9}
RRRRRRRR8CMR#CDCRR
RRRRRLRRCMoH
RRRRRRRRRRRRrL44j(:9RR=H4MLr:4(j
9;RRRRRRRRRRRRLd4r6U:49RR=jR;
RRRRRCRRMR8
RCRRM
8
RRRRNH##olMRk_D0Fjk0R5=R!RNj|!|RL?j2R:jRRRNj*jRLRR;
RNRR#o#HMkRlDF0_kR04=!R5N|4R|LR!4R2?jRR:N*4RRRL4;R

R/RR/HRbbHCDMsCRCRo
RNRRD$IN#@R@5#bFCC8oRiBpRRFsbCF#8RoC)  1asRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRFjk0_osC_$N#M<OR=;Rj
RRRRRRRRRRRR#NLH_oMjC_so#_N$RMO<4=R';Lj
RRRRRRRR8CMR#CDCVRHR 5)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRk_0js_CoNM#$O=R<R
j;RRRRRRRRRRRRNHL#ojM__osC_$N#M<OR='R4L
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRk_0js_CoNM#$O=R<RDlk0k_F0
j;RRRRRRRRRRRRNHL#ojM__osC_$N#M<OR=LRN#MHo_jj_;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRiBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRFRRk_0js_Co#O$MRR<=jR;
RRRRRRRRRNRRLo#HM__js_Co#O$MRR<=4j'L;R
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRFjk0_osC_M#$O=R<R
j;RRRRRRRRRRRRNHL#ojM__osC_M#$O=R<RL4'jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRkRF0sj_C#o_$RMO<l=Rk_D0Fjk0;R
RRRRRRRRRRLRN#MHo_sj_C#o_$RMO<N=RLo#HM__jjR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFR#bFCC8oR1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRR0Fk4C_so#_N$RMO<j=R;R
RRRRRRRRRRLRN#MHo_s4_CNo_#O$MRR<=4j'L;R
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRF4k0_osC_$N#M<OR=;Rj
RRRRRRRRRRRR#NLH_oM4C_so#_N$RMO<4=R';Lj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR 5BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRF4k0_osC_$N#M<OR=kRlDF0_k;04
RRRRRRRRRRRR#NLH_oM4C_so#_N$RMO<N=RLo#HM__4jR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRF4k0_osC_M#$O=R<R
j;RRRRRRRRRRRRNHL#o4M__osC_M#$O=R<RL4'jR;
RRRRRCRRMC8RDR#CH5VR)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0Fk4C_so$_#M<OR=;Rj
RRRRRRRRRRRR#NLH_oM4C_so$_#M<OR='R4L
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRk_04s_Co#O$MRR<=l0kD_0Fk4R;
RRRRRRRRRNRRLo#HM__4s_Co#O$MRR<=NHL#o4M__
j;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@l@5k_D0Fjk0RRFsFjk0_osCRRFsNHL#ojM__FjRsLRN#MHo_sj_C
o2RRRRLHCoMR
RRRRRRVRHRQ5uu_ j)R t=4=R'2Lj
RRRRRRRRoLCHRM
RRRRRRRRRFRRkR0j=kRlDF0_k;0j
RRRRRRRRRRRR#NLH_oMjRR=NHL#ojM__
j;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRRFRRkR0j=kRF0sj_C
o;RRRRRRRRRRRRNHL#ojM_RN=RLo#HM__js;Co
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@l0kD_0Fk4sRFR0Fk4C_sosRFR#NLH_oM4R_jFNsRLo#HM__4s2Co
RRRRoLCHRM
RRRRRHRRVuR5Q4u _t) RR==4j'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRF4k0Rl=Rk_D0F4k0;R
RRRRRRRRRRLRN#MHo_=4RR#NLH_oM4;_j
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRF4k0RF=Rk_04s;Co
RRRRRRRRRRRR#NLH_oM4RR=NHL#o4M__osC;R
RRRRRRMRC8R
RRMRC8R

RNRR#o#HMLRN#MHoRN=RLo#HMR_j|N|RLo#HM;_4
R
RRDRNI#N$R5@@Fjk0RRFsNHL#ojM_2R
RRCRLo
HMRRRRRRRRH5VRNHL#ojM_RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRFjk0_djr69:jRF=Rkr0jdj6:9R;
RRRRRRRRRFRRk_0jjcr6:9dnR{=RFjk0r9d6,kRF0djr6R9,Fjk0r9d6,kRF0djr6R9,Fjk0r9d6,kRF0djr6R9,Fjk0r9d6,kRF0djr6R9,Fjk0r9d6,kRF0djr6R9,Fjk0r9d6,kRF0djr6R9,Fjk0r9d6,kRF0djr6R9,Fjk0r9d6,kRF0djr6R9,Fjk0r9d6,kRF0djr6R9,Fjk0r9d6}R;
RRRRRCRRMC8RDR#C
RRRRRRRRoLCHRM
RRRRRRRRRFRRk_0jj6rd:Rj9=kRF0djr69:j;R
RRRRRRRRRRkRF0jj_r:6cdRn9=gR4';Lj
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@F4k0RRFsNHL#o4M_2R
RRCRLo
HMRRRRRRRRH5VRNHL#o4M_RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRF4k0_djr69:jRF=Rkr04dj6:9R;
RRRRRRRRRFRRk_04jcr6:9dnR{=RF4k0r9d6,kRF0d4r6R9,F4k0r9d6,kRF0d4r6R9,F4k0r9d6,kRF0d4r6R9,F4k0r9d6,kRF0d4r6R9,F4k0r9d6,kRF0d4r6R9,F4k0r9d6,kRF0d4r6R9,F4k0r9d6,kRF0d4r6R9,F4k0r9d6,kRF0d4r6R9,F4k0r9d6,kRF0d4r6R9,F4k0r9d6}R;
RRRRRCRRMC8RD
#CRRRRRRRRLHCoMR
RRRRRRRRRRkRF0j4_r:d6j=9RR0Fk46rd:;j9
RRRRRRRRRRRR0Fk4r_j6dc:n=9RR'4gL
j;RRRRRRRRC
M8RRRRC
M8
RRRR#N#HRoMH_MOCRG0=4R{',LjROHMr:6dj;9}
RRRR#N#HRoMN_OOD8FNR5=RNDOOF_N84?2RRFl_k:0RR
j;RRRR
RRRRINDNR$#@5@RH_MOCRG0FBsRqR1QFFsRk_0jjsRFR0Fk4R_jFNsRODO_F2N8
RRRRoLCHRM
RRRRRHRRVz5vp7aq7zqp44UXUm_v7= R=2RjRoLCHRMRR4//UUG4R-+/RG4U4+UR/B-R
RRRRRRRRRRRR5HVA7_q7z_1A=R=RL4'j&R&RqB_717_z=AR='R4LRj2LHCoMR
RRRRRRRRRRRRRRFR8k=0RR0FkjR_j+kRF0j4_RH+RMCO_G
0;RRRRRRRRRRRRCRM8CCD#R5HVA7_q7z_1A=R=RL4'j&R&RqB_717_z=AR='R4LR42LHCoMR
RRRRRRRRRRRRRRFR8k=0RR0FkjR_j+kRF0j4_RH-RMCO_G
0;RRRRRRRRRRRRCRM8CCD#R5HVA7_q7z_1A=R=RL4'4&R&RqB_717_z=AR='R4LRj2LHCoMR
RRRRRRRRRRRRRRFR8k=0RR0FkjR_j-kRF0j4_RH+RMCO_G
0;RRRRRRRRRRRRCRM8CCD#R5HVA7_q7z_1A=R=RL4'4&R&RqB_717_z=AR='R4LR42LHCoMR
RRRRRRRRRRRRRRFR8k=0RR0FkjR_j-kRF0j4_RH-RMCO_G
0;RRRRRRRRRRRRC
M8RRRRRRRRCRM8CCD#R5HVvazpqq77pUz4X_4Uv m7RR==4L2RCMoHR/RR/ONOkDlkNs0F,BqB/+jRRG4U4+UR/4-RUUG4
RRRRRRRRRRRR5HVA7_q7z_1A=R=RL4'jL2RCMoH
RRRRRRRRRRRRRRRRk8F0RR=N_OOD8FNRF+Rk_0jjRR+F4k0_
j;RRRRRRRRRRRRCRM8CCD#RoLCHRM
RRRRRRRRRRRRR8RRFRk0=ORNOF_DN+8RR0FkjR_j-kRF0j4_;R
RRRRRRRRRRMRC8R
RRRRRRMRC8DRC#HCRVvR5zqpa7p7qzX4U4vU_mR7 =.=R2CRLoRHMR4//UUG4R-+/RG4U4+URR1BqQR
RRRRRRRRRRVRH5qA_717_z=AR='R4LRj2LHCoMR
RRRRRRRRRRRRRRFR8k=0RR0FkjR_j+kRF0j4_RB+Rq;1Q
RRRRRRRRRRRR8CMR#CDCCRLo
HMRRRRRRRRRRRRRRRR80FkRF=Rk_0jjRR-F4k0_+jRR1BqQR;
RRRRRRRRRCRRMR8
RRRRRCRRMR8
RCRRM
8
RRRR/F/Rkk0b0CRsoR
RRDRNI#N$R5@@bCF#8RoCBRpiFbsRF8#Co)CR a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRFRRkN0_#O$MRR<=jR;
RRRRRCRRMC8RDR#CH5VR)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0Fk_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR 5BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRF_k0NM#$O=R<Rk8F0R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRF_k0#O$MRR<=jR;
RRRRRCRRMC8RDR#CH5VR)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRR0Fk_M#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRFRRk#0_$RMO<8=RF;k0
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@80FkRRFsF_k0s2Co
RRRRoLCHRM
RRRRRHRRVmR5z)a_ =tR='R4L
j2RRRRRRRRLHCoMR
RRRRRRRRRR_RlFRk0=FR8k
0;RRRRRRRRCRM8CCD#
RRRRRRRRoLCHRM
RRRRRRRRRlRR_0FkRF=Rks0_C
o;RRRRRRRRC
M8RRRRC
M8
RRRR#N#HRoM7amzRl=R_0Fk;R
RR#RN#MHoR1BqmRR={Fl_k60rd&9RR#NLH,oMlk_F0dr6:}j9;C

MF8l8CkD
/
/q-pz8CHsOl0RF
8ClkF8DqCRpcz677R5m,zaR1Bqmq,R,,RAR1BqQq,RBmBpqR7,qt1QhA,R1hQt,pRBiB,R ),R a1 2H;
M0bkRdr6:Rj9qA,R;M
HbRk0qt1Qh1,AQ;th
bHMkq0RBmBpq
7;HkMb06Rrc9:jR1BqQH;
M0bkRiBp, RB, R)1; a
0FkbRk0r:6dj79Rm;za
0FkbRk0r:6cjB9Rq;1m
N
bsCNl0RCsqt) R4=R';LjR4//':LjLN$b#l#RF;8CRL4'4s:RC#oH0RCslCF8
sbNN0lCCAsR)R t='R4L
j;bNNslCC0s1RqQ_th)R t='R4L
j;bNNslCC0s1RAQ_th)R t='R4L
j;bNNslCC0sBRqBqpm7 _)tRR=4j'L;N
bsCNl0RCsm_za)R t='R4L
j;bNNslCC0s_RAq_771RzA='R4LRj;/'/4LRj:N;88RL4'4k:#Lb;
NlsNCs0CRqB_717_z=ARRL4'jb;
NlsNCs0CRzqp7m_v7= RR/j;/qj:BjB/R-+/R+AR/q-R;:R4q/BBj/R+-RRA+qRB1RQ;.R:q+R/-ARR+BQq1;N
bsCNl0RCsq_pz)  1am_v7= RRY"1h;B"/Y/1hRB,qh1YB#

kDbb$tjRhR7;
b#kb4D$RBeB;R

RsRRCroR6jd:9MRHNsj_CNo_#O$M,MRHNsj_C#o_$,MORNHMjC_soH,RM_Ljs,CoHjMN_o#H,LHMjH_#oH,RM_Ljs_CoNM#$OH,RM_Ljs_Co#O$M;R
RRCRso#RNHjoM_osCj#_N$,MONo#HMsj_C_oj#O$M,HL#o_MjsjCo_$N#MLO,#MHojC_so#j_$,MONo#HMjj_,HL#o_Mjj#,NHjoM_osCjL,R#MHojC_so
j;RRRRsRCoNDOOFjN8_osC_$N#MRO,NDOOFjN8_osC_M#$ON,ROFODNj8_,ORNONDF8sj_C
o;RRRRsRCor:6cjH9RM_NjC,G0HjML_0CG,k8F0C_so#_N$,MORk8F0C_so$_#MRO,80Fk_osC;R
RRHRIsrCR6jc:9ORNOF_DN
8;RRRRsRCor:6cjl9R_0Fk,k8F0R;
RIRRHRsCo0s#M/;S/t=R1t)31;)m
#SN#MHoR#os0=MRRBeB;R
RRMRHHN0HDR
RRCRLo
HMRRRRRRRR80Fk_osCR6=R6j'L;R
RRMRC8


RRRRNNDI$@#R@M5HNsj_C#o_$RMOFHsRM_Njs_CoNM#$OsRFRLHMjC_so$_#MFORsMRHLsj_CNo_#O$MRRFsNo#HMsj_C_ojNM#$OsRFRHN#o_MjsjCo_M#$OsRFRHL#o_MjsjCo_$N#MFORs#RLHjoM_osCj$_#MFORsORNONDF8sj_CNo_#O$MRRFsRONOD8FNjC_so$_#MFORsFR8ks0_CNo_#O$MRRFs80Fk_osC_M#$OR2
RLRRCMoH
RRRRRRRRRHV5zqp_1)  va_mR7 ="=Rqh1YB
"2RRRRRRRRLHCoMR
RRRRRRRRRRMRHNsj_C<oR=MRHNsj_CNo_#O$M;R
RRRRRRRRRRMRHLsj_C<oR=MRHLsj_CNo_#O$M;R
RRRRRRRRRR#RNHjoM_osCj=R<RHN#o_MjsjCo_$N#M
O;RRRRRRRRRRRRLo#HMsj_CRoj<L=R#MHojC_soNj_#O$M;R
RRRRRRRRRRORNONDF8sj_C<oR=ORNONDF8sj_CNo_#O$M;R
RRRRRRRRRRFR8ks0_C<oR=FR8ks0_CNo_#O$M;R
RRRRRRMRC8RR
RRRRRCRRDR#CH5VRq_pz)  1am_v7= R=1R"Y"hB2R
RRRRRRCRLo
HMRRRRRRRRRRRRHjMN_osCRR<=HjMN_osC_M#$OR;
RRRRRRRRRHRRM_LjsRCo<H=RM_Ljs_Co#O$M;R
RRRRRRRRRR#RNHjoM_osCj=R<RHN#o_MjsjCo_M#$OR;
RRRRRRRRRLRR#MHojC_so<jR=#RLHjoM_osCj$_#M
O;RRRRRRRRRRRRNDOOFjN8_osCRR<=NDOOFjN8_osC_M#$OR;
RRRRRRRRR8RRF_k0sRCo<8=RF_k0s_Co#O$M;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRiBpRRFsbCF#8RoC)  1asRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRHjMN_osC_$N#M<OR=;RjRR
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRHjMN_osC_$N#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR 5BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRHjMN_osC_$N#M<OR=;Rq
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHNsj_C#o_$RMO<j=R;R
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRHjMN_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_Njs_Co#O$MRR<=qR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@R5qFHsRM_Njs2Co
RRRRoLCHRM
RRRRRHRRVqR5)R t=4=R'2Lj
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_Nj#RHo=;Rq
RRRRRRRR8CMR#CDCCRLo
HMRRRRRRRRRRRRHjMN_o#HRH=RM_Njs;Co
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCBRpiFbsRF8#Co)CR a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRHRRM_Ljs_CoNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV51)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHLsj_CNo_#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHLsj_CNo_#O$MRR<=AR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRHjML_osC_M#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV51)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRMRHLsj_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRLHMjC_so$_#M<OR=;RA
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@AsRFRLHMjC_soR2
RLRRCMoH
RRRRRRRRRHV5 A)t=R=RL4'jR2
RRRRRLRRCMoH
RRRRRRRRRRRRLHMjH_#oRR=AR;
RRRRRCRRMC8RDR#CLHCoMR
RRRRRRRRRRMRHL#j_H=oRRLHMjC_soR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFR#bFCC8oR1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRHN#o_MjsjCo_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR 5)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRNRR#MHojC_soNj_#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRR#RNHjoM_osCj#_N$RMO<q=R1hQt;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRiBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRNRR#MHojC_so#j_$RMO<j=R;R
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRNo#HMsj_C_oj#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRR#RNHjoM_osCj$_#M<OR=1RqQ;th
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@qt1QhsRFRHN#o_MjsjCo2R
RRCRLo
HMRRRRRRRRH5VRqt1Qh _)t=R=RL4'jR2
RRRRRLRRCMoH
RRRRRRRRRRRRHN#o_MjjRR=qt1QhR;
RRRRRCRRMC8RD
#CRRRRRRRRLHCoMR
RRRRRRRRRR#RNHjoM_=jRRHN#o_MjsjCo;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRiBpRRFsbCF#8RoC)  1asRFRoMCCC8oR#os0
M2RRRRLHCoMR
RRRRRRVRHRo5!sM#02CRLo
HMRRRRRRRRRRRRLo#HMsj_C_ojNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV51)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRR#RLHjoM_osCj#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRHL#o_MjsjCo_$N#M<OR=1RAQ;th
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRR#RLHjoM_osCj$_#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR 5)1R a=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRLRR#MHojC_so#j_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRHL#o_MjsjCo_M#$O=R<RQA1t
h;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@A@51hQtRRFsLo#HMsj_C2oj
RRRRoLCHRM
RRRRRHRRVAR51hQt_t) RR==4j'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRLo#HMjj_RA=R1hQt;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRRHL#o_MjjRR=Lo#HMsj_C;oj
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCBRpiFbsRF8#Co)CR a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRNRROFODN_8js_CoNM#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV51)  =aR='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8sj_CNo_#O$MRR<=jR;
RRRRRCRRMR8
RRRRRCRRDR#CH5VRB= R='R4L
42RRRRRRRRLHCoMR
RRRRRRRRRRORNONDF8sj_CNo_#O$MRR<=qpBBm;q7
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRORNONDF8sj_C#o_$RMO<j=R;RR
RRRRRCRRMC8RDR#CH5VR)  1a=R=RL4'4R2
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FNjC_so$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR 5BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRNDOOFjN8_osC_M#$O=R<RBqBp7mq;R
RRRRRRMRC8R
RRMRC8

RRRRRNNDI$@#R@B5qBqpm7sRFRONOD8FNjC_soR2
RLRRCMoH
RRRRRRRRRHV5BqBp7mq_t) RR==4j'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRNDOOF_N8j=R<RBqBp7mq;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRRONOD8FN_<jR=ORNONDF8sj_C
o;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@N@5#MHojR_jFLsR#MHojR_jFHsRM_Nj#RHoFHsRM_Lj#2Ho
RRRRoLCHRM
RRRRRHRRVNR5#MHojR_j=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_NjCrG06jd:9RR=HjMN_o#Hr:6dj
9;RRRRRRRRRRRRHjMN_0CGr96cRH=RM_Nj#rHo6;d9
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRHjMN_0CGr:6dj=9RRNHMjH_#odr6:;j9
RRRRRRRRRRRRNHMjG_C0cr69RR=4j'L;R
RRRRRRMRC8R

RRRRRHRRVLR5#MHojR_j=4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRRHRRM_LjCrG06jd:9RR=HjML_o#Hr:6dj
9;RRRRRRRRRRRRHjML_0CGr96cRH=RM_Lj#rHo6;d9
RRRRRRRR8CMR#CDCR
RRRRRRCRLo
HMRRRRRRRRRRRRHjML_0CGr:6dj=9RRLHMjH_#odr6:;j9
RRRRRRRRRRRRLHMjG_C0cr69RR=4j'L;R
RRRRRRMRC8R

RCRRM
8
RRRRNH##oNMRODO_FRN8=NR5OFODNj8_2RR?lk_F0RR:jR;
R
RRRRRRNNDI$@#R@O5NOF_DNF8RsqRB1FQRsMRHNCj_GF0RsMRHLCj_G
02RRRRLHCoMR
RRRRRRVRH5zqp7m_v7= R=2RjRRRRRRRRR/RR/BqB/+jR/A-RR-+/RRq
RRRRRLRRCMoH
RRRRRRRRRRRR5HVA7_q7z_1A=R=RL4'j&R&RqB_717_z=AR='R4L
j2RRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRRFR8k=0RRONO_NDF8RR+HjML_0CGRH+RM_NjC;G0
RRRRRRRRRRRR8CMR#CDCVRH5qA_717_z=AR='R4L&jR&_RBq_771RzA=4=R'2L4
RRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRR8RRFRk0=ORNOF_DN+8RRLHMjG_C0RR-HjMN_0CG;R
RRRRRRRRRRMRC8DRC#HCRV_5Aq_771RzA=4=R'RL4&B&R_7q7_A1zRR==4j'L2R
RRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRR80FkRN=RODO_FRN8-MRHLCj_G+0RRNHMjG_C0R;
RRRRRRRRRCRRMC8RD
#CRRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRRFR8k=0RRONO_NDF8RR-HjML_0CGRH-RM_NjC;G0
RRRRRRRRRRRR8CM
RRRRRRRR8CMR#CDCVRH5zqp7m_v7= R=2R4R/R/q/BBj/R+-RRA+qRB1RQ
RRRRRLRRCMoH
RRRRRRRRRRRR5HVA7_q7z_1A=R=RL4'jR2
RRRRRRRRRLRRCMoH
RRRRRRRRRRRRRRRRk8F0RR=N_OOD8FNRH+RM_LjCRG0+qRB1
Q;RRRRRRRRRRRRCRM8CCD#
RRRRRRRRRRRRoLCHRM
RRRRRRRRRRRRR8RRFRk0=ORNOF_DN-8RRLHMjG_C0RR+BQq1;R
RRRRRRRRRRMRC8RRRRRRRRR
RRRRRRMRC8DRC#HCRVp5qzv7_mR7 =.=R2/RR/+qR/A-RRB+Rq
1QRRRRRRRRLHCoMR
RRRRRRRRRRVRH5qA_717_z=AR='R4L
j2RRRRRRRRRRRRLHCoMR
RRRRRRRRRRRRRRFR8k=0RRNHMjG_C0RR+HjML_0CGRB+Rq;1Q
RRRRRRRRRRRR8CMR#CDCR
RRRRRRRRRRCRLo
HMRRRRRRRRRRRRRRRR80FkRH=RM_NjCRG0-MRHLCj_G+0RR1BqQR;
RRRRRRRRRCRRMR8
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFR#bFCC8oR1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRk8F0C_so#_N$RMO<j=R;R
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRR80Fk_osC_$N#M<OR=;Rj
RRRRRRRR8CMR#CDCVRHR 5BRR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRR80Fk_osC_$N#M<OR=FR8k
0;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoBCRpFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRk8F0C_so$_#M<OR=;Rj
RRRRRRRR8CMR#CDCHRRV)R5 a1 RR==44'L2R
RRRRRRCRLo
HMRRRRRRRRRRRR80Fk_osC_M#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV5RB =4=R'2L4
RRRRRRRRoLCHRM
RRRRRRRRR8RRF_k0s_Co#O$MRR<=80Fk;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5k8F0C_sosRFRk8F0R2
RLRRCMoH
RRRRRRRRRHV5amz_t) RR==4j'L2R
RRRRRRCRLo
HMRRRRRRRRRRRRlk_F0RR=80Fk;R
RRRRRRMRC8DRC#RC
RRRRRLRRCMoH
RRRRRRRRRRRRFl_k=0RRk8F0C_soR;
RRRRRCRRMR8
RCRRM
8
RRRRNH##o7MRmRza=_RlFrk06jd:9R;
RNRR#o#HMqRB1=mRRFl_k
0;ClM8FD8kC


/*/******1*7usRbH0lHHRPC****************
R//u7q74lU
FD8kCqRu7U74Rm57zRa,1Rm,1,AmRRq,A1,RQ1,RARQ,qp1 ,pRBiB,R ),R a1 2
;
HkMb0rRR4j(:9;Rq
bHMkR0Rr:4(jA9R;M
HbRk0R q1pH;
M0bkR RB,iBp,1)  
a;HkMb0rRR4j(:9QR1,Q1A;k
F00bkR(r4:Rj911m,A
m;Fbk0kr0R4j(:9mR7z
a;
sbNN0lCCqsR)R t='R4LRj;/4/R':LjRbL$NR##lCF8;'R4LR4:sHCo#s0CCl8RF
8CbNNslCC0s)RA =tRRL4'jb;
NlsNCs0CR7q7_A1zR4=R';LjR4//':LjR8N8;'R4L#4:kbL
NlsNCs0CR7uq7 _)1_ av m7R"=R1BYh"/;R/YR1hRB,qh1YBN
bsCNl0RCsAp1 _7vm RR=44'L;/R/RL4'4#:RE0HV,'R4LRj:bNNsDDDCRbHMkA0R3N
bsCNl0RCs1 m)tRR=4j'L;#

kDbb$tjRhR7;
b#kb4D$RBeB;
R
RRRRsRCor:4(jH9RMHL,M,NjHjML,NHMjC_soM,HNs4_CHo,MsL_CHo,MsO_CHo,M,N4H.MN;R
RRCRso4Rr(9:jRNHMjC_so#_N$,MOHjMN_osC_M#$OM,HNs4_CNo_#O$M,NHM4C_so$_#MHO,MsL_CNo_#O$M,LHM_osC_M#$OR;
RsRRCroR4j(:98R#FjL_;I
SHRsCo0s#M/;S/t=R1t)31;)m
#SN#MHoR#os0=MRRBeB;R

RNRRD$IN#@R@5NHMjC_so$_#MFORsMRHNsj_CNo_#O$MRRFsH_MLs_Co#O$MRRFsH_MLs_CoNM#$OsRFRNHM4C_so#_N$RMOFHsRM_N4s_Co#O$M2R
RRCRLo
HMRRRRRRRRH5VRu7q7_1)  va_mR7 ="=Rqh1YBR"2LHCoMR
RRRRRRRRRRMRHNsj_C<oR=MRHNsj_CNo_#O$M;R
RRRRRRRRRRMRHNs4_C<oR=MRHNs4_CNo_#O$M;R
RRRRRRRRRRMRHLC_so=R<RLHM_osC_$N#M
O;RRRRRRRRC
M8RRRRRRRRCCD#RRHV57uq7 _)1_ av m7RR=="h1YBR"2LHCoMR
RRRRRRRRRRMRHNsj_C<oR=MRHNsj_C#o_$;MO
RRRRRRRRRRRRNHM4C_so=R<RNHM4C_so$_#M
O;RRRRRRRRRRRRH_MLsRCo<H=RMsL_C#o_$;MO
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@1FQRsRRqFqsR12 pR
RRRRRRLHCoMR
RRRRRRVRHR15q =pR='R4LR42LHCoMR
RRRRRRRRRRMRHN=jRR;1Q
RRRRRRRR8CMR#CDCVRH5 q1p=R=RL4'jL2RCMoH
RRRRRRRRRRRRNHMjRR=qR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@R5AF1sRARQ2RRRRRRRR
RRRRoLCHRM
RRRRRHRRVAR51_ pv m7RR==44'L2CRLo
HMRRRRRRRRRRRRHjMLR1=RA
Q;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5 A1pm_v7= R='R4LRj2LHCoMR
RRRRRRRRRRMRHL=jRR
A;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoBCRpFiRsFRb#oC8C R)1R aFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHNsj_CNo_#O$MRR<=j
;RRRRRRRRRRRRRH4MN_osC_$N#M<OR=;RjRR
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2CRLo
HMRRRRRRRRRRRRHjMN_osC_$N#M<OR=;Rj
RRRRRRRRRRRRNHM4C_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4L2RCMoH
RRRRRRRRRRRRNHMjC_so#_N$RMO<H=RM;Nj
RRRRRRRRRRRRNHM4C_so#_N$RMO<H=RM;N4
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHNsj_C#o_$RMO<j=R;RR
RRRRRRRRRHRRM_N4s_Co#O$MRR<=j
;RRRRRRRRRCRM8CCD#RRHV51)  =aR='R4LR42LHCoMR
RRRRRRRRRRMRHNsj_C#o_$RMO<j=R;R
RRRRRRRRRRMRHNs4_C#o_$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4L2RCMoH
RRRRRRRRRRRRNHMjC_so$_#M<OR=MRHN
j;RRRRRRRRRRRRH4MN_osC_M#$O=R<RNHM4R;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@F5b#oC8CpRBisRFR#bFCC8oR1)  FaRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRLHM_osC_$N#M<OR=;RjRR
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2CRLo
HMRRRRRRRRRRRRH_MLs_CoNM#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4RoLCHRM
RRRRRRRRRHRRMsL_CNo_#O$MRR<=HjML;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5#bFCC8oRiBpRRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRHRRMsL_C#o_$RMO<j=R;RR
RRRRRCRRMC8RDR#CH5VR)  1a=R=RL4'4L2RCMoH
RRRRRRRRRRRRLHM_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4RoLCHRM
RRRRRRRRRHRRMsL_C#o_$RMO<H=RM;Lj
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@HjMN_osCRRFsHjMN2R
RRCRLo
HMRRRRRRRRH5VRqt) RR==4j'L2CRLo
HMRRRRRRRRRRRRH4MNRH=RM;Nj
RRRRRRRR8CM
RRRRRRRR#CDCCRLo
HMRRRRRRRRRRRRH4MNRH=RM_Njs;Co
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@H4MNRRFsH4MN_osC2R
RRCRLo
HMRRRRRRRRH5VR1 m)t=R=RL4'jL2RCMoH
RRRRRRRRRRRRNHM.RR=H4MN;R
RRRRRRMRC8R
RRRRRRDRC#LCRCMoH
RRRRRRRRRRRRNHM.RR=H4MN_osC;R
RRRRRRMRC8R
RRMRC8R

RNRR#o#HMmR1RH=RM;N.
R
RRDRNI#N$R5@@H_MLsRCoFHsRM2Lj
RRRRoLCHRM
RRRRRHRRVAR5)R t=4=R'2LjRoLCHRM
RRRRRRRRRHRRM=LRRLHMjR;
RRRRRCRRMR8
RRRRRCRRDR#CLHCoMR
RRRRRRRRRRMRHLRR=H_MLs;Co
RRRRRRRR8CM
RRRR8CM
R
RR#RN#MHoRm1ARH=RM
L;R
RRRRRRNH##o7MRmRza=qR5717_z=AR='R4LR42?HR5MRN4-MRHL:2RRM5HN+4RRLHM2
;
ClM8FD8kC/

/qRu7
7glkF8DuCRqg77Rm57zRa,1Rm,1,AmRRq,A1,RQ1,RARQ,qp1 ,pRBiB,R ),R a1 2
;
HkMb0rRRU9:jR
q;HkMb0rRRU9:jR
A;HkMb0qRR1; p
bHMkR0RBB ,p)i, a1 ;M
HbRk0R:rUj19RQA,1QF;
kk0b0URr:Rj911m,A
m;Fbk0kr0RU9:jRz7ma
;
bNNslCC0s)Rq =tRRL4'j/;R/'R4LRj:LN$b#l#RF;8CRL4'4s:RC#oH0CCs8FRl8bC
NlsNCs0CR A)tRR=4j'L;bR
NlsNCs0CR7q7_A1zR4=R';LjR4//':LjN;88RL4'4k:#LN
bsCNl0RCsu7q7_1)  va_mR7 =1R"Y"hB;/R/Rh1YBq,R1BYh
sbNN0lCCAsR1_ pv m7R4=R';L4RR//44'L:ER#H,V0RL4'jb:RNDsNDRCDHkMb03RA
sbNN0lCC1sRmt) R4=R';Lj
k
#b$bDjhRt7
;R#bkbDR$4e;BBRR

RsRRCroRU9:jRLHM,NHMjM,HLHj,M_Njs,CoH4MN_osC,LHM_osC,NHM4M,HN
.;RRRRsRCorjU:9MRHNsj_CNo_#O$M,NHMjC_so$_#MHO,M_N4s_CoNM#$OM,HNs4_C#o_$,MOH_MLs_CoNM#$OM,HLC_so$_#M
O;RRRR/H/IsoCRsM#0Rt=R1t)31;)m
HSIsoCRsM#0;/S/=1Rt)13t)
m;S#N#HRoMo0s#MRR=e;BB
R
RRDRNI#N$R5@@HjMN_osC_M#$OsRFRNHMjC_so#_N$RMOFHsRMsL_C#o_$RMOFHsRMsL_CNo_#O$MRRFsH4MN_osC_$N#MFORsMRHNs4_C#o_$2MO
RRRRoLCHRM
RRRRRHRRVuR5q_77)  1am_v7= R=qR"1BYh"L2RCMoH
RRRRRRRRRRRRNHMjC_so=R<RNHMjC_so#_N$;MO
RRRRRRRRRRRRNHM4C_so=R<RNHM4C_so#_N$;MO
RRRRRRRRRRRRLHM_osCRR<=H_MLs_CoNM#$OR;
RRRRRCRRM
8RRRRRRRRRCCD#RRHV57uq7 _)1_ av m7RR=="h1YBR"2LHCoMR
RRRRRRRRRRMRHNsj_C<oR=MRHNsj_C#o_$;MO
RRRRRRRRRRRRNHM4C_so=R<RNHM4C_so$_#M
O;RRRRRRRRRRRRH_MLsRCo<H=RMsL_C#o_$;MO
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@1FQRsRRqFqsR12 pR
RRRRRRLHCoMR
RRRRRRVRHR15q =pR='R4LR42LHCoMR
RRRRRRRRRRMRHN=jRR;1Q
RRRRRRRR8CMR#CDCVRH5 q1p=R=RL4'jL2RCMoH
RRRRRRRRRRRRNHMjRR=qR;
RRRRRCRRMR8
RCRRM
8
RRRRNNDI$@#R@R5AF1sRARQ2RRRRRRRR
RRRRoLCHRM
RRRRRHRRVAR51_ pv m7RR==44'L2CRLo
HMRRRRRRRRRRRRHjMLR1=RA
Q;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5 A1pm_v7= R='R4LRj2LHCoMR
RRRRRRRRRRMRHL=jRR
A;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoBCRpFiRsFRb#oC8C R)1R aFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHNsj_CNo_#O$MRR<=j
;RRRRRRRRRRRRRH4MN_osC_$N#M<OR=;RjRR
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2CRLo
HMRRRRRRRRRRRRHjMN_osC_$N#M<OR=;Rj
RRRRRRRRRRRRNHM4C_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4L2RCMoH
RRRRRRRRRRRRNHMjC_so#_N$RMO<H=RM;Nj
RRRRRRRRRRRRNHM4C_so#_N$RMO<H=RM;N4
RRRRRRRR8CM
RRRR8CM
R
RRDRNI#N$R5@@bCF#8RoCBRpiFMsRC8oCooCRsM#02R
RRCRLo
HMRRRRRRRRH5VR!#os0RM2LHCoMR
RRRRRRRRRRMRHNsj_C#o_$RMO<j=R;R
RRRRRRRRRRMRHNs4_C#o_$RMO<j=R;R
RRRRRRMRC8DRC#HCRV)R5 a1 RR==44'L2CRLo
HMRRRRRRRRRRRRHjMN_osC_M#$O=R<R
j;RRRRRRRRRRRRH4MN_osC_M#$O=R<R
j;RRRRRRRRC
M8RRRRRRRRCCD#RRHV5RB =4=R'2L4RoLCHRM
RRRRRRRRRHRRM_Njs_Co#O$MRR<=HjMN;R
RRRRRRRRRRMRHNs4_C#o_$RMO<H=RM;N4
RRRRRRRR8CM
RRRR8CM
RRRRR
RRDRNI#N$R5@@bCF#8RoCBRpiFbsRF8#Co)CR a1 RRFsMCCo8RoCo0s#MR2
RLRRCMoH
RRRRRRRRRHV5s!o#20MRoLCHRM
RRRRRRRRRHRRMsL_CNo_#O$MRR<=j
;RRRRRRRRRCRM8CCD#RRHV51)  =aR='R4LR42LHCoMR
RRRRRRRRRRMRHLC_so#_N$RMO<j=R;R
RRRRRRMRC8R
RRRRRRDRC#HCRVBR5 =R=RL4'4L2RCMoH
RRRRRRRRRRRRLHM_osC_$N#M<OR=MRHL
j;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@b@5F8#CoBCRpFiRsCRMooC8CsRo#20M
RRRRoLCHRM
RRRRRHRRV!R5o0s#ML2RCMoH
RRRRRRRRRRRRLHM_osC_M#$O=R<R
j;RRRRRRRRCRM8CCD#RRHV51)  =aR='R4LR42LHCoMR
RRRRRRRRRRMRHLC_so$_#M<OR=;Rj
RRRRRRRR8CM
RRRRRRRR#CDCVRHR 5BRR==44'L2CRLo
HMRRRRRRRRRRRRH_MLs_Co#O$MRR<=HjML;R
RRRRRRMRC8R
RRMRC8R

RNRRD$IN#@R@5NHMjC_sosRFRNHMjR2
RLRRCMoH
RRRRRRRRRHV5 q)t=R=RL4'jL2RCMoH
RRRRRRRRRRRRNHM4=R<RNHMjR;
RRRRRCRRMR8
RRRRRCRRDR#CLHCoMR
RRRRRRRRRRMRHN<4R=MRHNsj_C
o;RRRRRRRRC
M8RRRRC
M8
RRRRINDNR$#@H@5MRN4FHsRM_N4s2Co
RRRRoLCHRM
RRRRRHRRV1R5mt) RR==4j'L2CRLo
HMRRRRRRRRRRRRH.MNRH=RM;N4
RRRRRRRR8CM
RRRRRRRR#CDCCRLo
HMRRRRRRRRRRRRH.MNRH=RM_N4s;Co
RRRRRRRR8CM
RRRR8CM
R
RR#RN#MHoRmR1RH=RM;N.
R
RRDRNI#N$R5@@H_MLsRCoFHsRM2Lj
RRRRoLCHRM
RRRRRHRRVAR5)R t=4=R'2LjRoLCHRM
RRRRRRRRRHRRM=LRRLHMjR;
RRRRRCRRMR8
RRRRRCRRDR#CLHCoMR
RRRRRRRRRRMRHLRR=H_MLs;Co
RRRRRRRR8CM
RRRR8CM
R
RR#RN#MHoRm1ARH=RM
L;
RRRR#N#HRoM7amzR5=Rq_771RzA=4=R'2L4R5?RH4MNRH-RMRL2:HR5MRN4+MRHL
2;
8CMlkF8D
C
`8CMODCD8HCVM
C

