@ER//qCOODsDCN0R1NNM8se8R4R3UmMbCRseCHOVHNF0HMHRpLssN$mR5e3p2
R//qCOODsDCNFRBbH$soRE05RO2.6jj-j.jnq3RDsDRH0oE#CRs#PCsC
83
R//qC888FRVs$R1MHbDV
$
`V8CHRMCm_epq 11)ma_h8
`CMVHCeRmp _e)mQpt8
`CMVHCeRmpB_X]i B_wmw
C`8VCHMRpme_uQvpQQBaB_X]i B_wmw



`8HVCmVRe1p_a77_ hwQ ]1_
R//8MFRFH0EM`o
CCD#
C`8VCHMRpme_71a_w7 Q1h _
]
`V8CHRMCm_epe1 )QRmh"3e4U
"
`8HVCmVReqp_1)1 ah_m
`RRHCV8VeRmp1_upR
RR`RRHCV8VeRmp _e)mQptR
RRRRRRkR`MV8CRpme_pu1
RRRRCR`MV8H
RRRRHR`VV8CRpme_q1e
RRRRRRRRV`H8RCVm_epu
1pRRRRRRRRRkR`MV8CRpme_pu1
RRRRRRRRM`C8
HVRRRRRM`C8
HVRCR`D
#CRRRR`8HVCmVReep_ p)QmRt
R`RRCCD#
RRRR`RR8HCVMmCReep_ p)QmRt
R`RRCHM8VR
RRHR`VV8CRpme_q1e
RRRRRRR`8kMCmVReep_ p)QmRt
R`RRCHM8VR
R`8CMH`V
CHM8V`

HCV8VeRmpm_Be_ )m`h
HCV8VeRmp1_upR
RR`RRHCV8VeRmp _e)mQptR
RRRRRRkR`MV8CRpme_pu1
RRRRCR`MV8H
RRRRHR`VV8CRpme_q1e
RRRRRRRRV`H8RCVm_epu
1pRRRRRRRRRkR`MV8CRpme_pu1
RRRRRRRRM`C8
HVRRRRRM`C8
HVRCR`D
#CRRRR`8HVCmVReep_ p)QmRt
R`RRCCD#
RRRR`RR8HCVMmCReep_ p)QmRt
R`RRCHM8VR
RRHR`VV8CRpme_q1e
RRRRRRR`8kMCmVReep_ p)QmRt
R`RRCHM8VR
R`8CMH`V
CHM8V`

HCV8VeRmp1_q1a )_
mhRHR`VV8CRpme_q1])_ 7B m7
`RRCCD#
RRRRC`8VCHMRpme_q1])_ 7B m7
`RRCHM8VC
`D
#CRHR`VV8CRpme_eBm m)_hR
RRHR`VV8CRpme_q1])_ 7B m7
RRRRD`C#RC
RRRRRC`8VCHMRpme_q1])_ 7B m7
RRRRM`C8
HVRCR`MV8H
M`C8
HV
R//#ObCHHV$MHoRMs0CVCNORsVFR#1$0RCleHCsD
Fo
V`H8RCVm_ep1_eqQ ha)Bwq R
R`V8CHRMClkF8DHCRMs0CVCNO
`RR8HCVMCCRMF8l8CkDR8CMHCM0sOVNCC
`D
#CR8R`CMVHCFRl8CkDR8lFk
DCR8R`CMVHCMRC88lFkRDCClM8FD8kCC
`MV8H
/
/RD1CCHO0MooRDNFLDCRs#RC0FDsRFDONR#sCCV0RF0sREOCRE	COCssRC0#CRo#HM
ND
V`H8RCVm_eptApmq)p_ a1 
`RR8HCVMmCRe)p_ a1 _t1QhRqp`pme_mtpA_qp)  1aC
`D
#CR8R`CMVHCeRmp _)1_ a1hQtqspRC0#C_`M
CHM8V/

/ORN0CHPRoC8C
#
`V8CHRMCm_eph7m tR Rj8
`CMVHCeRmpm_u1t 7 
R4`V8CHRMCm_eph  t7Rt .8
`CMVHCeRmph_qYt 7 
Rd
R//#CCPs$H0RPDCC
D#
C`8VCHMRpme_awqqRpRR`j
8HCVMmCRe p_)))mR4RR
C`8VCHMRpme_)WqhtQhR`.
8HCVMmCReQp_hRwmRdRR
/
/RPOFCosNCCRDP#CD
8
`CMVHCeRmpm_Be_ )h mhRRRRR
Rj`V8CHRMCm_epB me)q_1hYQaRRRR48
`CMVHCeRmpm_Be_ )AQq1BRRRR
R.`V8CHRMCm_epB me)m_B))h RRRRc8
`CMVHCeRmpm_Be_ )1aaqQQ1aB
RU`V8CHRMCm_epB me)p_qpRRRRRRR4
6
/8/RCkVNDO0RFsPCNRoCDCCPD`

8HCVMmCReBp_m)e _w7 qazpRe`mpm_Be_ )AQq1B/

/sRbFsbC00$R$
bC
C`8VCHMRpme_1q1 R)aj8
`CMVHCeRmp1_q1 zvR`4
8HCVMmCReQp_t)hm 
R.
R//MCCO#s#N$FROM08HH
FM
C`8VCHMRpme_Qa)t)t __mhvam1_uuQ RRRR`j
8HCVMmCReap_)tQt m)_hQ_w)_1au QuR4RR
C`8VCHMRpme_Qa)t)t __mhw1Q)am_hu QuR
.
/N/ROF0HMMRFRIMCRN#0s
0
`V8CHRMCm_epQmth)h _ 1W_aaq)RjRR
C`8VCHMRpme_1)  ma_h _hWa_1qR)a48
`CMVHCeRmp)_ )_m)mhh_ 1W_aaq)R
.
/H/RM0NOHRPCDCCPD
#
`V8CHRMCm_epq_ppZm )1
Rj`V8CHRMCm_epq_ppm1h R
R4`V8CHRMCm_epm_h B7mpR
R.
R//FRPDs0kMHRlCNCV0sNRV0RNDCFsss`

8HCVMmCRe)p_zQhavq _w)a _awqq4pRj
j
`8CMH/VR/eRmpa_17 _7w Qh1
_]
