`ifndef NDS_GLOBAL_INC
`define NDS_GLOBAL_INC
`include "ae250_config.vh"
`include "ae250_const.vh"

`include "ae250_config.vh"
`include "ae250_const.vh"
`include "ae250_smu_config.vh"
`include "ae250_smu_const.vh"
`include "atcapbbrg100_config.vh"
`include "atcapbbrg100_const.vh"
`include "atcbmc200_config.vh"
`include "atcbmc200_const.vh"
`include "atcdmac100_config.vh"
`include "atcdmac100_const.vh"
`include "atcgpio100_config.vh"
`include "atcgpio100_const.vh"
`include "atciic100_config.vh"
`include "atciic100_const.vh"
`include "atcmstmux100_config.vh"
`include "atcmstmux100_const.vh"
`include "atcpit100_config.vh"
`include "atcpit100_const.vh"
`include "atcrtc100_config.vh"
`include "atcrtc100_const.vh"
`include "atcspi200_config.vh"
`include "atcspi200_const.vh"
`include "atcuart100_config.vh"
`include "atcuart100_const.vh"
`include "atcwdt200_config.vh"
`include "atcwdt200_const.vh"

`endif // NDS_GLOBAL_INC

